/*
 * Copyright (C) 2014-2017 Stichting Mapcode Foundation (http://www.mapcode.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef __INTERNAL_TERRITORY_NAMES_ES_H__
#define __INTERNAL_TERRITORY_NAMES_ES_H__

#ifdef __cplusplus
extern "C" {
#endif

// *** GENERATED FILE (coords.cpp), DO NOT CHANGE OR PRETTIFY ***

static const char *TERRITORY_FULL_NAME_ES[] = {
#ifdef MAPCODE_SUPPORT_LANGUAGE_ES // Spanish
        /*     VAT */ "Vaticano|Ciudad del Vaticano|Santa Sede",
        /*     MCO */ "Mónaco",
        /*     GIB */ "Gibraltar",
        /*     TKL */ "Tokelau",
        /*     CCK */ "Islas Cocos|Islas Keeling",
        /*     BLM */ "San Bartolomé",
        /*     NRU */ "Nauru",
        /*     TUV */ "Tuvalu",
        /*     MAC */ "Macau",
        /*     SXM */ "Sint Maarten",
        /*     MAF */ "San Martín",
        /*     NFK */ "Norfolk y Phillip Island|isla de Phillip|isla de Norfolk",
        /*     PCN */ "Islas Pitcairn",
        /*     BVT */ "Isla Bouvet",
        /*     BMU */ "Islas Bermudas|Bermudas",
        /*     IOT */ "Territorio Británico del Océano Índico",
        /*     SMR */ "San Marino",
        /*     GGY */ "Guernesey",
        /*     AIA */ "Anguila",
        /*     MSR */ "Montserrat",
        /*     JEY */ "Jersey",
        /*     CXR */ "Isla de Navidad",
        /*     WLF */ "Wallis y Futuna|Futuna",
        /*     VGB */ "Islas Vírgenes Británicas",
        /*     LIE */ "Liechtenstein",
        /*     ABW */ "Aruba",
        /*     MHL */ "Islas Marshall",
        /*     ASM */ "Samoa Americana",
        /*     COK */ "Islas Cook",
        /*     SPM */ "San Pedro y Miquelón|Miquelón",
        /*     NIU */ "Niue",
        /*     KNA */ "San Cristóbal y Nieves|Nevis",
        /*     CYM */ "Islas Caimán",
        /*     BES */ "Bonaire, St Eustatuis y Saba|Saba|San Eustaquio",
        /*     MDV */ "Maldivas",
        /*     SHN */ "Santa Helena, Ascensión y Tristán da Cunha|Ascensión|Tristan da Cunha",
        /*     MLT */ "Malta",
        /*     GRD */ "Granada",
        /*     VIR */ "Islas Vírgenes de EE.UU",
        /*     MYT */ "Mayotte",
        /*     SJM */ "Svalbard y Jan Mayen|Jan Mayen",
        /*     VCT */ "San Vicente y las Granadinas|Granadinas",
        /*     HMD */ "Islas Heard y McDonald|Islas McDonald",
        /*     BRB */ "Barbados",
        /*     ATG */ "Antigua y Barbuda|Barbuda",
        /*     CUW */ "Curazao",
        /*     SYC */ "Seychelles",
        /*     PLW */ "Palau",
        /*     MNP */ "Islas Marianas del Norte",
        /*     AND */ "Andorra",
        /*     GUM */ "Guam",
        /*     IMN */ "Isla de Man",
        /*     LCA */ "Santa Lucía",
        /*     FSM */ "Micronesia|Estados Federados de Micronesia",
        /*     SGP */ "Singapur",
        /*     TON */ "Tonga",
        /*     DMA */ "Dominica",
        /*     BHR */ "Bahrein",
        /*     KIR */ "Kiribati",
        /*     TCA */ "Islas Turcas y Caicos|Islas Caicos",
        /*     STP */ "Santo Tomé y Príncipe|Príncipe",
        /*     HKG */ "Hong Kong",
        /*     MTQ */ "Martinica",
        /*     FRO */ "Islas Faroe",
        /*     GLP */ "Guadalupe",
        /*     COM */ "Comoras",
        /*     MUS */ "Mauricio",
        /*     REU */ "Reunión",
        /*     LUX */ "Luxemburgo",
        /*     WSM */ "Samoa",
        /*     SGS */ "Georgia del Sur y las Islas Sandwich del Sur|Islas Sandwich del Sur",
        /*     PYF */ "Polinesia francés",
        /*     CPV */ "Cabo Verde",
        /*     TTO */ "Trinidad y Tobago|Tobago",
        /*     BRN */ "Brunei",
        /*     ATF */ "Tierras Australes y Antárticas Francesas",
        /*     PRI */ "Puerto Rico",
        /*     CYP */ "Chipre",
        /*     LBN */ "Líbano",
        /*     JAM */ "Jamaica",
        /*     GMB */ "Gambia",
        /*     QAT */ "Katar",
        /*     FLK */ "Islas Malvinas",
        /*     VUT */ "Vanuatu",
        /*     MNE */ "Montenegro",
        /*     BHS */ "Bahamas",
        /*     TLS */ "Timor Oriental",
        /*     SWZ */ "Swazilandia",
        /*     KWT */ "Kuwait",
        /*     FJI */ "Islas Fiji",
        /*     NCL */ "Nueva Caledonia",
        /*     SVN */ "Eslovenia",
        /*     ISR */ "Israel",
        /*     PSE */ "Territorio Palestino",
        /*     SLV */ "El Salvador",
        /*     BLZ */ "Belice",
        /*     DJI */ "Djibouti",
        /*     MKD */ "macedonia",
        /*     RWA */ "Ruanda",
        /*     HTI */ "Haití",
        /*     BDI */ "Burundi",
        /*     GNQ */ "Guinea Ecuatorial",
        /*     ALB */ "Albania",
        /*     SLB */ "Islas Salomón",
        /*     ARM */ "Armenia",
        /*     LSO */ "Lesoto",
        /*     BEL */ "Bélgica",
        /*     MDA */ "Moldavia",
        /*     GNB */ "Guinea-Bissau",
        /*     TWN */ "Taiwán",
        /*     BTN */ "Bután",
        /*     CHE */ "Suiza",
        /*     NLD */ "Países Bajos",
        /*     DNK */ "Dinamarca",
        /*     EST */ "Estonia",
        /*     DOM */ "República Dominicana",
        /*     SVK */ "Eslovaquia",
        /*     CRI */ "Costa Rica",
        /*     BIH */ "Bosnia y Herzegovina",
        /*     HRV */ "Croacia",
        /*     TGO */ "Togo",
        /*     LVA */ "Letonia",
        /*     LTU */ "Lituania",
        /*     LKA */ "Sri Lanka",
        /*     GEO */ "Georgia",
        /*     IRL */ "Irlanda",
        /*     SLE */ "Sierra Leona",
        /*     PAN */ "Panamá",
        /*     CZE */ "República Checa",
        /*     GUF */ "Guayana francés",
        /*     ARE */ "Emiratos Árabes Unidos",
        /*     AUT */ "Austria",
        /*     AZE */ "Azerbaiyán",
        /*     SRB */ "Serbia",
        /*     JOR */ "Jordán",
        /*     PRT */ "Portugal",
        /*     HUN */ "Hungría",
        /*     KOR */ "Corea del Sur",
        /*     ISL */ "Islandia",
        /*     GTM */ "Guatemala",
        /*     CUB */ "Cuba",
        /*     BGR */ "Bulgaria",
        /*     LBR */ "Liberia",
        /*     HND */ "Honduras",
        /*     BEN */ "Benin",
        /*     ERI */ "Eritrea",
        /*     MWI */ "malawi",
        /*     PRK */ "Corea del Norte",
        /*     NIC */ "Nicaragua",
        /*     GRC */ "Grecia",
        /*     TJK */ "Tayikistán",
        /*     BGD */ "Bangladesh",
        /*     NPL */ "Nepal",
        /*     TUN */ "Túnez",
        /*     SUR */ "Suriname",
        /*     URY */ "Uruguay",
        /*     KHM */ "Camboya",
        /*     SYR */ "Siria",
        /*     SEN */ "Senegal",
        /*     KGZ */ "Kirguistán",
        /*     BLR */ "Bielorrusia",
        /*     GUY */ "Guayana",
        /*     LAO */ "Laos",
        /*     ROU */ "Rumania",
        /*     GHA */ "Ghana",
        /*     UGA */ "Uganda",
        /*     GBR */ "Reino Unido|Escocia|Gran Bretaña|Irlanda del Norte|Irlanda, Norte",
        /*     GIN */ "Guinea",
        /*     ECU */ "Ecuador",
        /*     ESH */ "Sahara Occidental|Saharaui",
        /*     GAB */ "Gabón",
        /*     NZL */ "Nueva Zelanda",
        /*     BFA */ "Burkina Faso",
        /*     PHL */ "Filipinas",
        /*     ITA */ "Italia",
        /*     OMN */ "Omán",
        /*     POL */ "Polonia",
        /*     CIV */ "Costa de Marfil",
        /*     NOR */ "Noruega",
        /*     MYS */ "Malasia",
        /*     VNM */ "Vietnam",
        /*     FIN */ "Finlandia",
        /*     COG */ "Congo-Brazzaville",
        /*     DEU */ "Alemania",
        /*     JPN */ "Japón",
        /*     ZWE */ "Zimbabue",
        /*     PRY */ "Paraguay",
        /*     IRQ */ "Irak",
        /*     MAR */ "Marruecos",
        /*     UZB */ "Uzbekistán",
        /*     SWE */ "Suecia",
        /*     PNG */ "Papúa Nueva Guinea",
        /*     CMR */ "Camerún",
        /*     TKM */ "Turkmenistán",
        /*     ESP */ "España",
        /*     THA */ "Tailandia",
        /*     YEM */ "Yemen",
        /*     FRA */ "Francia",
        /*     ALA */ "Islas Aland",
        /*     KEN */ "Kenia",
        /*     BWA */ "Botswana",
        /*     MDG */ "Madagascar",
        /*     UKR */ "Ucrania",
        /*     SSD */ "Sudán del Sur",
        /*     CAF */ "República Centroafricana",
        /*     SOM */ "Somalia",
        /*     AFG */ "Afganistán",
        /*     MMR */ "Myanmar|Birmania",
        /*     ZMB */ "Zambia",
        /*     CHL */ "Chile",
        /*     TUR */ "Turquía",
        /*     PAK */ "Pakistán",
        /*     MOZ */ "Mozambique",
        /*     NAM */ "Namibia",
        /*     VEN */ "Venezuela",
        /*     NGA */ "Nigeria",
        /*     TZA */ "Tanzania",
        /*     EGY */ "Egipto",
        /*     MRT */ "Mauritania",
        /*     BOL */ "Bolivia",
        /*     ETH */ "Etiopía",
        /*     COL */ "Colombia",
        /*     ZAF */ "Sudáfrica",
        /*     MLI */ "Malí",
        /*     AGO */ "Angola",
        /*     NER */ "Níger",
        /*     TCD */ "Chad",
        /*     PER */ "Perú",
        /*     MNG */ "Mongolia",
        /*     IRN */ "Irán",
        /*     LBY */ "Libia",
        /*     SDN */ "Sudán",
        /*     IDN */ "Indonesia",
        /*     DIF */ "Distrito Federal",
        /*     TLA */ "Tlaxcala",
        /*     MOR */ "Morelos",
        /*     AGU */ "Aguascalientes",
        /*   MX-CL */ "Colima",
        /*     QUE */ "Queretaro",
        /*     HID */ "Hidalgo",
        /*   MX-MX */ "Estado de México",
        /*     TAB */ "Tabasco",
        /*     NAY */ "Nayarit",
        /*     GUA */ "Guanajuato",
        /*     PUE */ "Puebla",
        /*     YUC */ "Yucatán",
        /*     ROO */ "Quintana Roo",
        /*     SIN */ "Sinaloa",
        /*     CAM */ "Campeche",
        /*     MIC */ "Michoacán",
        /*     SLP */ "San Luis Potosí",
        /*     GRO */ "Guerrero",
        /*     NLE */ "Nuevo Leon",
        /*     BCN */ "Baja California",
        /*     VER */ "Veracruz",
        /*     CHP */ "Chiapas",
        /*     BCS */ "Baja California Sur",
        /*     ZAC */ "Zacatecas",
        /*     JAL */ "Jalisco",
        /*     TAM */ "Tamaulipas",
        /*     OAX */ "Oaxaca",
        /*     DUR */ "Durango",
        /*     COA */ "Coahuila",
        /*     SON */ "Sonora",
        /*     CHH */ "Chihuahua",
        /*     GRL */ "Tierra Verde",
        /*     SAU */ "Arabia Saudita",
        /*     COD */ "Congo-Kinshasa",
        /*     DZA */ "Argelia",
        /*     KAZ */ "Kazajstán",
        /*     ARG */ "Argentina",
        /*   IN-DD */ "Daman y Diu",
        /*   IN-DN */ "Dadra y Nagar Haveli",
        /*   IN-CH */ "Chandigarh",
        /*   IN-AN */ "Andaman y Nicobar",
        /*   IN-LD */ "Lakshadweep|Laquedivas",
        /*   IN-DL */ "Delhi",
        /*   IN-ML */ "Meghalaya",
        /*   IN-NL */ "Nagaland",
        /*   IN-MN */ "Manipur",
        /*   IN-TR */ "Tripura",
        /*   IN-MZ */ "Mizoram",
        /*   IN-SK */ "Sikkim",
        /*   IN-PB */ "Punjab",
        /*   IN-HR */ "Haryana",
        /*   IN-AR */ "Arunachal Pradesh",
        /*   IN-AS */ "Assam",
        /*   IN-BR */ "Bihar",
        /*   IN-UT */ "Uttarakhand",
        /*   IN-GA */ "Goa",
        /*   IN-KL */ "Kerala",
        /*   IN-TN */ "Tamil Nadu",
        /*   IN-HP */ "Himachal Pradesh",
        /*   IN-JK */ "Jammu y Cachemira",
        /*   IN-CT */ "Chhattisgarh",
        /*   IN-JH */ "Jharkhand",
        /*   IN-KA */ "Karnataka",
        /*   IN-RJ */ "Rajasthan",
        /*   IN-OR */ "Odisha|Orissa",
        /*   IN-GJ */ "Gujarat",
        /*   IN-WB */ "Bengala Occidental",
        /*   IN-MP */ "Madhya Pradesh",
        /*   IN-TG */ "Telangana",
        /*   IN-AP */ "Andhra Pradesh",
        /*   IN-MH */ "Maharashtra",
        /*   IN-UP */ "Uttar Pradesh",
        /*   IN-PY */ "Puducherry",
        /*     NSW */ "Nueva Gales del Sur",
        /*     ACT */ "Territorio de la Capital Australiana|Australian Capital Territory",
        /*     JBT */ "Territorio de Jervis Bay",
        /*   AU-NT */ "Territorio del Norte",
        /*   AU-SA */ "Australia del Sur",
        /*     TAS */ "Tasmania",
        /*     VIC */ "Victoria",
        /*   AU-WA */ "Australia Occidental",
        /*     QLD */ "Queensland",
        /*   BR-DF */ "Distrito Federal",
        /*   BR-SE */ "Sergipe",
        /*   BR-AL */ "Alagoas",
        /*   BR-RJ */ "Rio de Janeiro",
        /*   BR-ES */ "Espirito Santo",
        /*   BR-RN */ "Rio Grande do Norte",
        /*   BR-PB */ "Paraiba",
        /*   BR-SC */ "Santa Catarina",
        /*   BR-PE */ "Pernambuco",
        /*   BR-AP */ "Amapá",
        /*   BR-CE */ "Ceara",
        /*   BR-AC */ "Acre",
        /*   BR-PR */ "Paraná",
        /*   BR-RR */ "Roraima",
        /*   BR-RO */ "Rondonia",
        /*   BR-SP */ "Sao Paulo",
        /*   BR-PI */ "Piaui",
        /*   BR-TO */ "Tocantins",
        /*   BR-RS */ "Rio Grande do Sul",
        /*   BR-MA */ "Marañón",
        /*   BR-GO */ "Goias",
        /*   BR-MS */ "Mato Grosso do Sul",
        /*   BR-BA */ "Bahia",
        /*   BR-MG */ "Minas Gerais",
        /*   BR-MT */ "Mato Grosso",
        /*   BR-PA */ "Paraca",
        /*   BR-AM */ "Amazonas",
        /*   US-DC */ "Distrito de Columbia",
        /*   US-RI */ "Rhode Island",
        /*   US-DE */ "Delaware",
        /*   US-CT */ "Connecticut",
        /*   US-NJ */ "New Jersey",
        /*   US-NH */ "Nueva Hampshire",
        /*   US-VT */ "Vermont",
        /*   US-MA */ "Massachusetts",
        /*   US-HI */ "Hawai",
        /*   US-MD */ "Maryland",
        /*   US-WV */ "Virginia Occidental",
        /*   US-SC */ "Carolina del Sur",
        /*   US-ME */ "Maine",
        /*   US-IN */ "Indiana",
        /*   US-KY */ "Kentucky",
        /*   US-TN */ "Tennesse",
        /*   US-VA */ "Virginia",
        /*   US-OH */ "Ohio",
        /*   US-PA */ "Pensilvania",
        /*   US-MS */ "Misisipí",
        /*   US-LA */ "Luisiana",
        /*   US-AL */ "Alabama",
        /*   US-AR */ "Arkansas",
        /*   US-NC */ "Carolina del Norte",
        /*   US-NY */ "Nueva York",
        /*   US-IA */ "Iowa",
        /*   US-IL */ "Illinois",
        /*   US-GA */ "Georgia",
        /*   US-WI */ "Wisconsin",
        /*   US-FL */ "Florida",
        /*   US-MO */ "Misuri",
        /*   US-OK */ "Oklahoma",
        /*   US-ND */ "Dakota del Norte",
        /*   US-WA */ "Washington",
        /*   US-SD */ "Dakota del Sur",
        /*   US-NE */ "Nebraska",
        /*   US-KS */ "Kansas",
        /*   US-ID */ "Idaho",
        /*   US-UT */ "Utah",
        /*   US-MN */ "Minnesota",
        /*   US-MI */ "Michigan",
        /*   US-WY */ "Wyoming",
        /*   US-OR */ "Oregón",
        /*   US-CO */ "Colorado",
        /*   US-NV */ "Nevada",
        /*   US-AZ */ "Arizona",
        /*   US-NM */ "Nuevo Mexico",
        /*   US-MT */ "Montana",
        /*   US-CA */ "California",
        /*   US-TX */ "Texas",
        /*   US-AK */ "Alaska",
        /*   CA-BC */ "Columbia Británica",
        /*   CA-AB */ "Alberta",
        /*   CA-ON */ "Ontario",
        /*   CA-QC */ "Quebec",
        /*   CA-SK */ "Saskatchewan",
        /*   CA-MB */ "Manitoba",
        /*   CA-NL */ "Terranova",
        /*   CA-NB */ "Nuevo Brunswick",
        /*   CA-NS */ "Nueva Escocia",
        /*   CA-PE */ "Isla del Príncipe Eduardo",
        /*   CA-YT */ "Yukon",
        /*   CA-NT */ "Territorios del Noroeste",
        /*   CA-NU */ "Nunavut",
        /*     IND */ "India",
        /*     AUS */ "Australia",
        /*     BRA */ "Brasil",
        /*     USA */ "USA|Estados Unidos de América|América",
        /*     MEX */ "Méjico",
        /*     MOW */ "Moscú",
        /*     SPE */ "San Petersburgo",
        /*     KGD */ "Kaliningrad Oblast",
        /*   RU-IN */ "República de Ingushetia",
        /*   RU-AD */ "República de Adygea",
        /*   RU-SE */ "República de Osetia del Norte-Alania",
        /*   RU-KB */ "República de Kabardino-Balkar",
        /*   RU-KC */ "República Karachay-Cherkess",
        /*   RU-CE */ "República Chechena",
        /*   RU-CU */ "República de Chuvash",
        /*     IVA */ "Óblast de Ivanovo",
        /*     LIP */ "Óblast de Lipetsk",
        /*     ORL */ "Oryol Oblast",
        /*     TUL */ "Tula Oblast",
        /*   RU-BE */ "Belgorod Oblast",
        /*     VLA */ "Vladimir Oblast",
        /*     KRS */ "Óblast de Kursk",
        /*     KLU */ "Kaluga Oblast",
        /*   RU-TT */ "Óblast de Tambov",
        /*     BRY */ "Oblast de Bryansk",
        /*     YAR */ "Yaroslavl Oblast",
        /*     RYA */ "Ryazan Oblast",
        /*     AST */ "Óblast de Astrakhan",
        /*     MOS */ "Oblast de Moscú",
        /*     SMO */ "Oblast de Smolensk",
        /*   RU-DA */ "República de Daguestán",
        /*     VOR */ "Óblast de Voronezh",
        /*     NGR */ "Óblast de Novgorod",
        /*     PSK */ "Óblast de Pskov",
        /*     KOS */ "Kostroma Oblast",
        /*     STA */ "Stavropol Krai",
        /*     KDA */ "Krasnodar Krai",
        /*   RU-KL */ "República de Kalmykia",
        /*     TVE */ "Oblast de Tver",
        /*     LEN */ "Oblast de Leningrado",
        /*     ROS */ "Óblast de Rostov",
        /*     VGG */ "Óblast de Volgogrado",
        /*     VLG */ "Óblast de Vologda",
        /*     MUR */ "Murmansk Oblast",
        /*   RU-KR */ "República de Carelia",
        /*     NEN */ "Nenets Autónoma Okrug",
        /*   RU-KO */ "República de Komi",
        /*     ARK */ "Arkhangelsk Oblast",
        /*   RU-MO */ "República de Mordovia",
        /*     NIZ */ "Óblast de Nizhny Novgorod",
        /*     PNZ */ "Penza Oblast",
        /*   RU-KI */ "Óblast de Kirov",
        /*   RU-ME */ "Mari El Republic",
        /*     ORE */ "Orenburg Oblast",
        /*     ULY */ "Ulyanovsk Oblast",
        /*   RU-PM */ "Perm Krai",
        /*   RU-BA */ "República de Bashkortostán",
        /*   RU-UD */ "República de Udmurt",
        /*   RU-TA */ "República de Tatarstán",
        /*     SAM */ "Samara Oblast",
        /*     SAR */ "Óblast de Saratov",
        /*     YAN */ "Yamalo-Nenets",
        /*   RU-KM */ "Khanty-Mansi",
        /*     SVE */ "Óblast de Sverdlovsk",
        /*     TYU */ "Tyumen Oblast",
        /*     KGN */ "Oblast de Kurgan",
        /*   RU-CH */ "Chelyabinsk Oblast",
        /*   RU-BU */ "República de Buriatia",
        /*     ZAB */ "Zabaykalsky Krai",
        /*     IRK */ "Óblast de Irkutsk",
        /*     NVS */ "Óblast de Novosibirsk",
        /*     TOM */ "Tomsk Oblast",
        /*     OMS */ "Oblast de Omsk",
        /*   RU-KK */ "República de Khakassia",
        /*     KEM */ "Óblast de Kemerovo",
        /*   RU-AL */ "República de Altai",
        /*     ALT */ "Krai de Altai",
        /*   RU-TY */ "Tuva Republic",
        /*     KYA */ "Krasnoyarsk Krai",
        /*     MAG */ "Óblast de Magadan",
        /*     CHU */ "Chukotka Okrug",
        /*     KAM */ "Kamchatka Krai",
        /*     SAK */ "Óblast de Sajalín",
        /*   RU-PO */ "Primorsky Krai",
        /*     YEV */ "Oblast autónomo judío",
        /*     KHA */ "Krai de Jabárovsk",
        /*     AMU */ "Óblast de Amur",
        /*   RU-SA */ "República de Sakha|República de Yakutia",
        /*     CAN */ "Canadá",
        /*     RUS */ "Rusia",
        /*   CN-SH */ "Llevar a la fuerza",
        /*   CN-TJ */ "Tianjin",
        /*   CN-BJ */ "Beijing",
        /*   CN-HI */ "Hainan",
        /*   CN-NX */ "Ningxia Hui",
        /*   CN-CQ */ "Chongqing",
        /*   CN-ZJ */ "Zhejiang",
        /*   CN-JS */ "Jiangsu",
        /*   CN-FJ */ "Fujian",
        /*   CN-AH */ "Anhui",
        /*   CN-LN */ "Liaoning",
        /*   CN-SD */ "Shandong",
        /*   CN-SX */ "Shanxi",
        /*   CN-JX */ "Jiangxi",
        /*   CN-HA */ "Henan",
        /*   CN-GZ */ "Guizhou",
        /*   CN-GD */ "provincia de Guangdong",
        /*   CN-HB */ "Hubei",
        /*   CN-JL */ "Jilin",
        /*   CN-HE */ "Hebei",
        /*   CN-SN */ "Shaanxi",
        /*   CN-NM */ "Nei Mongol|Mongolia Interior",
        /*   CN-HL */ "Heilongjiang",
        /*   CN-HN */ "Hunan",
        /*   CN-GX */ "Guangxi Zhuang",
        /*   CN-SC */ "Sichuan",
        /*   CN-YN */ "Yunnan",
        /*   CN-XZ */ "Xizang|Tíbet",
        /*   CN-GS */ "Gansu",
        /*   CN-QH */ "Qinghai",
        /*   CN-XJ */ "Xinjiang Uyghur",
        /*     CHN */ "China",
        /*     UMI */ "Islas menores alejadas de los Estados Unidos",
        /*     CPT */ "Isla Clipperton",
        /*     ATA */ "Antártida",
        /*     AAA */ "Internacional|Mundial|Tierra"
#else // MAPCODE_SUPPORT_LANGUAGE_ES
        NULL
#endif // MAPCODE_SUPPORT_LANGUAGE_ES
};

#ifdef __cplusplus
}
#endif

#endif // __INTERNAL_TERRITORY_NAMES_ES_H__
