/*
 * Copyright (C) 2014-2017 Stichting Mapcode Foundation (http://www.mapcode.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef __INTERNAL_TERRITORY_NAMES_DE_H__
#define __INTERNAL_TERRITORY_NAMES_DE_H__

#ifdef __cplusplus
extern "C" {
#endif

// *** GENERATED FILE (coords.cpp), DO NOT CHANGE OR PRETTIFY ***

static const char *TERRITORY_FULL_NAME_DE[] = {
#ifdef MAPCODE_SUPPORT_LANGUAGE_DE // German
        /*     VAT */ "Vatikanstadt|Heiliger Stuhl",
        /*     MCO */ "Monaco",
        /*     GIB */ "Gibraltar",
        /*     TKL */ "Tokelau",
        /*     CCK */ "Kokosinseln|Keeling-Insel",
        /*     BLM */ "Sankt Bartholomäus",
        /*     NRU */ "Nauru",
        /*     TUV */ "Tuvalu",
        /*     MAC */ "Macau",
        /*     SXM */ "Sint Maarten",
        /*     MAF */ "Saint-Martin",
        /*     NFK */ "Norfolkinsel|Philip-Insel",
        /*     PCN */ "Pitcairninseln",
        /*     BVT */ "Bouvet-Insel",
        /*     BMU */ "Bermuda",
        /*     IOT */ "Britisches Territorium im Indischen Ozean",
        /*     SMR */ "San Marino",
        /*     GGY */ "Guernsey",
        /*     AIA */ "Anguilla",
        /*     MSR */ "Montserrat",
        /*     JEY */ "Jersey",
        /*     CXR */ "Weihnachtsinsel",
        /*     WLF */ "Wallis und Futuna|Futuna",
        /*     VGB */ "Britische Jungferninseln|Jungferninseln, Britisch",
        /*     LIE */ "Liechtenstein",
        /*     ABW */ "Aruba",
        /*     MHL */ "Marshall-Inseln",
        /*     ASM */ "Amerikanisch Samoa|Samoa, Amerikanisch",
        /*     COK */ "Cookinseln",
        /*     SPM */ "Saint-Pierre und Miquelon|Miquelon",
        /*     NIU */ "Niue",
        /*     KNA */ "Saint Kitts und Nevis|Nevis",
        /*     CYM */ "Cayman-Inseln",
        /*     BES */ "Bonaire, St. Eustatius und Saba|Saba|St Eustatius",
        /*     MDV */ "Malediven",
        /*     SHN */ "Saint Helena, Ascension und Tristan da Cunha|Christi Himmelfahrt|Tristan da Cunha",
        /*     MLT */ "Malta",
        /*     GRD */ "Grenada",
        /*     VIR */ "Amerikanische Jungferninseln|Virgin-Inseln, USA",
        /*     MYT */ "Mayotte",
        /*     SJM */ "Spitzbergen|Jan Mayen",
        /*     VCT */ "Saint Vincent und die Grenadinen|Grenadines",
        /*     HMD */ "Heard- und McDonald-Inseln|McDonald-Inseln",
        /*     BRB */ "Barbados",
        /*     ATG */ "Antigua und Barbuda|Barbuda",
        /*     CUW */ "Curaçao",
        /*     SYC */ "Seychellen",
        /*     PLW */ "Palau",
        /*     MNP */ "Nördliche Marianen",
        /*     AND */ "Andorra",
        /*     GUM */ "Guam",
        /*     IMN */ "Isle of Man",
        /*     LCA */ "Saint Lucia",
        /*     FSM */ "Micronesia|Föderierte Staaten von Mikronesien",
        /*     SGP */ "Singapur",
        /*     TON */ "Tonga",
        /*     DMA */ "Dominica",
        /*     BHR */ "Bahrain",
        /*     KIR */ "Kiribati",
        /*     TCA */ "Turks- und Caicosinseln|Caicos-Inseln",
        /*     STP */ "Sao Tome und Principe|Principe",
        /*     HKG */ "Hong Kong",
        /*     MTQ */ "Martinique",
        /*     FRO */ "Färöer-Inseln",
        /*     GLP */ "Guadeloupe",
        /*     COM */ "Komoren",
        /*     MUS */ "Mauritius",
        /*     REU */ "Reunion",
        /*     LUX */ "Luxemburg",
        /*     WSM */ "Samoa",
        /*     SGS */ "Südgeorgien und die Südlichen Sandwich-Inseln|South Sandwich-Inseln",
        /*     PYF */ "Französisch-Polynesien",
        /*     CPV */ "Kap Verde",
        /*     TTO */ "Trinidad und Tobago|Tobago",
        /*     BRN */ "Brunei",
        /*     ATF */ "Französisch Süd- und Antarktisgebiete",
        /*     PRI */ "Puerto Rico",
        /*     CYP */ "Zypern",
        /*     LBN */ "Libanon",
        /*     JAM */ "Jamaika",
        /*     GMB */ "Gambia",
        /*     QAT */ "Katar",
        /*     FLK */ "Falkland-Inseln",
        /*     VUT */ "Vanuatu",
        /*     MNE */ "Montenegro",
        /*     BHS */ "Bahamas",
        /*     TLS */ "Osttimor",
        /*     SWZ */ "Swasiland",
        /*     KWT */ "Kuwait",
        /*     FJI */ "Fidschi-Inseln",
        /*     NCL */ "Neukaledonien",
        /*     SVN */ "Slowenien",
        /*     ISR */ "Israel",
        /*     PSE */ "Palästinensische Autonomiegebiete",
        /*     SLV */ "El Salvador",
        /*     BLZ */ "Belize",
        /*     DJI */ "Dschibuti",
        /*     MKD */ "Mazedonien",
        /*     RWA */ "Ruanda",
        /*     HTI */ "Haiti",
        /*     BDI */ "Burundi",
        /*     GNQ */ "Äquatorial-Guinea",
        /*     ALB */ "Albanien",
        /*     SLB */ "Salomon-Inseln",
        /*     ARM */ "Armenien",
        /*     LSO */ "Lesotho",
        /*     BEL */ "Belgien",
        /*     MDA */ "Moldawien",
        /*     GNB */ "Guinea-Bissau",
        /*     TWN */ "Taiwan",
        /*     BTN */ "Bhutan",
        /*     CHE */ "Schweiz",
        /*     NLD */ "Niederlande",
        /*     DNK */ "Dänemark",
        /*     EST */ "Estland",
        /*     DOM */ "Dominikanische Republik",
        /*     SVK */ "Slowakei",
        /*     CRI */ "Costa Rica",
        /*     BIH */ "Bosnien und Herzegowina",
        /*     HRV */ "Kroatien",
        /*     TGO */ "Togo",
        /*     LVA */ "Lettland",
        /*     LTU */ "Litauen",
        /*     LKA */ "Sri Lanka",
        /*     GEO */ "Georgien",
        /*     IRL */ "Irland",
        /*     SLE */ "Sierra Leone",
        /*     PAN */ "Panama",
        /*     CZE */ "Tschechische Republik",
        /*     GUF */ "Französisch-Guayana",
        /*     ARE */ "Vereinigte Arabische Emirate",
        /*     AUT */ "Österreich",
        /*     AZE */ "Aserbaidschan",
        /*     SRB */ "Serbia",
        /*     JOR */ "Jordan",
        /*     PRT */ "Portugal",
        /*     HUN */ "Ungarn",
        /*     KOR */ "Südkorea",
        /*     ISL */ "Island",
        /*     GTM */ "Guatemala",
        /*     CUB */ "Kuba",
        /*     BGR */ "Bulgarien",
        /*     LBR */ "Liberia",
        /*     HND */ "Honduras",
        /*     BEN */ "Benin",
        /*     ERI */ "Eritrea",
        /*     MWI */ "Malawi",
        /*     PRK */ "Nordkorea",
        /*     NIC */ "Nicaragua",
        /*     GRC */ "Griechenland",
        /*     TJK */ "Tadschikistan",
        /*     BGD */ "Bangladesch",
        /*     NPL */ "Nepal",
        /*     TUN */ "Tunesien",
        /*     SUR */ "Surinam",
        /*     URY */ "Uruguay",
        /*     KHM */ "Kambodscha",
        /*     SYR */ "Syrien",
        /*     SEN */ "Senegal",
        /*     KGZ */ "Kirgisistan",
        /*     BLR */ "Weißrussland",
        /*     GUY */ "Guyana",
        /*     LAO */ "Laos",
        /*     ROU */ "Rumänien",
        /*     GHA */ "Ghana",
        /*     UGA */ "Uganda",
        /*     GBR */ "Vereinigtes Königreich",
        /*     GIN */ "Guinea",
        /*     ECU */ "Ecuador",
        /*     ESH */ "Western Sahara|Sahrawi",
        /*     GAB */ "Gabun",
        /*     NZL */ "Neuseeland",
        /*     BFA */ "Burkina Faso",
        /*     PHL */ "Philippinen",
        /*     ITA */ "Italien",
        /*     OMN */ "Oman",
        /*     POL */ "Polen",
        /*     CIV */ "Elfenbeinküste",
        /*     NOR */ "Norwegen",
        /*     MYS */ "Malaysia",
        /*     VNM */ "Vietnam",
        /*     FIN */ "Finnland",
        /*     COG */ "Kongo-Brazzaville",
        /*     DEU */ "Deutschland",
        /*     JPN */ "Japan",
        /*     ZWE */ "Simbabwe",
        /*     PRY */ "Paraguay",
        /*     IRQ */ "Irak",
        /*     MAR */ "Marokko",
        /*     UZB */ "Usbekistan",
        /*     SWE */ "Schweden",
        /*     PNG */ "Papua-Neuguinea",
        /*     CMR */ "Kamerun",
        /*     TKM */ "Turkmenistan",
        /*     ESP */ "Spanien",
        /*     THA */ "Thailand",
        /*     YEM */ "Jemen",
        /*     FRA */ "Frankreich",
        /*     ALA */ "Åland-Inseln|Aaland-Inseln",
        /*     KEN */ "Kenia",
        /*     BWA */ "Botswana",
        /*     MDG */ "Madagaskar",
        /*     UKR */ "Ukraine",
        /*     SSD */ "Süd-Sudan",
        /*     CAF */ "Zentralafrikanische Republik",
        /*     SOM */ "Somalia",
        /*     AFG */ "Afghanistan",
        /*     MMR */ "Myanmar|Birma",
        /*     ZMB */ "Sambia",
        /*     CHL */ "Chile",
        /*     TUR */ "Türkei",
        /*     PAK */ "Pakistan",
        /*     MOZ */ "Mosambik",
        /*     NAM */ "Namibia",
        /*     VEN */ "Venezuela",
        /*     NGA */ "Nigeria",
        /*     TZA */ "Tansania",
        /*     EGY */ "Ägypten",
        /*     MRT */ "Mauretanien",
        /*     BOL */ "Bolivien",
        /*     ETH */ "Äthiopien",
        /*     COL */ "Kolumbien",
        /*     ZAF */ "Südafrika",
        /*     MLI */ "Mali",
        /*     AGO */ "Angola",
        /*     NER */ "Niger",
        /*     TCD */ "Tschad",
        /*     PER */ "Peru",
        /*     MNG */ "Mongolei",
        /*     IRN */ "Iran",
        /*     LBY */ "Libyen",
        /*     SDN */ "Sudan",
        /*     IDN */ "Indonesien",
        /*     DIF */ "Federal District",
        /*     TLA */ "Tlaxcala",
        /*     MOR */ "Morelos",
        /*     AGU */ "Aguascalientes",
        /*   MX-CL */ "Colima",
        /*     QUE */ "Queretaro",
        /*     HID */ "Hidalgo",
        /*   MX-MX */ "Mexico State",
        /*     TAB */ "Tabasco",
        /*     NAY */ "Nayarit",
        /*     GUA */ "Guanajuato",
        /*     PUE */ "Puebla",
        /*     YUC */ "Yucatan",
        /*     ROO */ "Quintana Roo",
        /*     SIN */ "Sinaloa",
        /*     CAM */ "Campeche",
        /*     MIC */ "Michoacan",
        /*     SLP */ "San Luis Potosi",
        /*     GRO */ "Guerrero",
        /*     NLE */ "Nuevo Leon",
        /*     BCN */ "Baja California",
        /*     VER */ "Veracruz",
        /*     CHP */ "Chiapas",
        /*     BCS */ "Baja California Sur",
        /*     ZAC */ "Zacatecas",
        /*     JAL */ "Jalisco",
        /*     TAM */ "Tamaulipas",
        /*     OAX */ "Oaxaca",
        /*     DUR */ "Durango",
        /*     COA */ "Coahuila",
        /*     SON */ "Sonora",
        /*     CHH */ "Chihuahua",
        /*     GRL */ "Grönland",
        /*     SAU */ "Saudi-Arabien",
        /*     COD */ "Kongo-Kinshasa",
        /*     DZA */ "Algerien",
        /*     KAZ */ "Kasachstan",
        /*     ARG */ "Argentinien",
        /*   IN-DD */ "Daman und Diu",
        /*   IN-DN */ "Dadra und Nagar Haveli",
        /*   IN-CH */ "Chandigarh",
        /*   IN-AN */ "Andamanen-und Nikobaren",
        /*   IN-LD */ "Lakshadweep",
        /*   IN-DL */ "Delhi",
        /*   IN-ML */ "Meghalaya",
        /*   IN-NL */ "Nagaland",
        /*   IN-MN */ "Manipur",
        /*   IN-TR */ "Tripura",
        /*   IN-MZ */ "Mizoram",
        /*   IN-SK */ "Sikkim",
        /*   IN-PB */ "Punjab",
        /*   IN-HR */ "Haryana",
        /*   IN-AR */ "Arunachal Pradesh",
        /*   IN-AS */ "Assam",
        /*   IN-BR */ "Bihar",
        /*   IN-UT */ "Uttarakhand",
        /*   IN-GA */ "Goa",
        /*   IN-KL */ "Kerala",
        /*   IN-TN */ "Tamil Nadu",
        /*   IN-HP */ "Himachal Pradesh",
        /*   IN-JK */ "Jammu und Kaschmir",
        /*   IN-CT */ "Chhattisgarh",
        /*   IN-JH */ "Jharkhand",
        /*   IN-KA */ "Karnataka",
        /*   IN-RJ */ "Rajasthan",
        /*   IN-OR */ "Odisha|Orissa",
        /*   IN-GJ */ "Gujarat",
        /*   IN-WB */ "Westbengalen",
        /*   IN-MP */ "Madhya Pradesh",
        /*   IN-TG */ "Telangana",
        /*   IN-AP */ "Andhra Pradesh",
        /*   IN-MH */ "Maharashtra",
        /*   IN-UP */ "Uttar Pradesh",
        /*   IN-PY */ "Puducherry",
        /*     NSW */ "New South Wales",
        /*     ACT */ "Australian Capital Territory",
        /*     JBT */ "Jervis Bay Territory",
        /*   AU-NT */ "Northern Territory",
        /*   AU-SA */ "South Australia",
        /*     TAS */ "Tasmanien",
        /*     VIC */ "Victoria",
        /*   AU-WA */ "Western Australia",
        /*     QLD */ "Queensland",
        /*   BR-DF */ "Distrito Federal",
        /*   BR-SE */ "Sergipe",
        /*   BR-AL */ "Alagoas",
        /*   BR-RJ */ "Rio de Janeiro",
        /*   BR-ES */ "Espirito Santo",
        /*   BR-RN */ "Rio Grande do Norte",
        /*   BR-PB */ "Paraiba",
        /*   BR-SC */ "Santa Catarina",
        /*   BR-PE */ "Pernambuco",
        /*   BR-AP */ "Amapá",
        /*   BR-CE */ "Ceara",
        /*   BR-AC */ "Acre",
        /*   BR-PR */ "Parana",
        /*   BR-RR */ "Roraima",
        /*   BR-RO */ "Rondonia",
        /*   BR-SP */ "Sao Paulo",
        /*   BR-PI */ "Piaui",
        /*   BR-TO */ "Tocantins",
        /*   BR-RS */ "Rio Grande do Sul",
        /*   BR-MA */ "Maranhao",
        /*   BR-GO */ "Goias",
        /*   BR-MS */ "Mato Grosso do Sul",
        /*   BR-BA */ "Bahia",
        /*   BR-MG */ "Minas Gerais",
        /*   BR-MT */ "Mato Grosso",
        /*   BR-PA */ "Para",
        /*   BR-AM */ "Amazonas",
        /*   US-DC */ "District of Columbia",
        /*   US-RI */ "Rhode Island",
        /*   US-DE */ "Delaware",
        /*   US-CT */ "Connecticut",
        /*   US-NJ */ "New Jersey",
        /*   US-NH */ "New Hampshire",
        /*   US-VT */ "Vermont",
        /*   US-MA */ "Massachusetts",
        /*   US-HI */ "Hawaii",
        /*   US-MD */ "Maryland",
        /*   US-WV */ "West Virginia",
        /*   US-SC */ "South Carolina",
        /*   US-ME */ "Maine",
        /*   US-IN */ "Indiana",
        /*   US-KY */ "Kentucky",
        /*   US-TN */ "Tennessee",
        /*   US-VA */ "Virginia",
        /*   US-OH */ "Ohio",
        /*   US-PA */ "Pennsylvania",
        /*   US-MS */ "Mississippi",
        /*   US-LA */ "Louisiana",
        /*   US-AL */ "Alabama",
        /*   US-AR */ "Arkansas",
        /*   US-NC */ "North Carolina",
        /*   US-NY */ "New York",
        /*   US-IA */ "Iowa",
        /*   US-IL */ "Illinois",
        /*   US-GA */ "Georgia",
        /*   US-WI */ "Wisconsin",
        /*   US-FL */ "Florida",
        /*   US-MO */ "Missouri",
        /*   US-OK */ "Oklahoma",
        /*   US-ND */ "North Dakota",
        /*   US-WA */ "Washington",
        /*   US-SD */ "South Dakota",
        /*   US-NE */ "Nebraska",
        /*   US-KS */ "Kansas",
        /*   US-ID */ "Idaho",
        /*   US-UT */ "Utah",
        /*   US-MN */ "Minnesota",
        /*   US-MI */ "Michigan",
        /*   US-WY */ "Wyoming",
        /*   US-OR */ "Oregon",
        /*   US-CO */ "Colorado",
        /*   US-NV */ "Nevada",
        /*   US-AZ */ "Arizona",
        /*   US-NM */ "New Mexico",
        /*   US-MT */ "Montana",
        /*   US-CA */ "Kalifornien",
        /*   US-TX */ "Texas",
        /*   US-AK */ "Alaska",
        /*   CA-BC */ "British Columbia",
        /*   CA-AB */ "Alberta",
        /*   CA-ON */ "Ontario",
        /*   CA-QC */ "Quebec",
        /*   CA-SK */ "Saskatchewan",
        /*   CA-MB */ "Manitoba",
        /*   CA-NL */ "Newfoundland",
        /*   CA-NB */ "New Brunswick",
        /*   CA-NS */ "Nova Scotia",
        /*   CA-PE */ "Prince Edward-Insel",
        /*   CA-YT */ "Yukon",
        /*   CA-NT */ "Northwest Territories",
        /*   CA-NU */ "Nunavut",
        /*     IND */ "Indien",
        /*     AUS */ "Australien",
        /*     BRA */ "Brasilien",
        /*     USA */ "USA|Vereinigte Staaten von Amerika|Amerika",
        /*     MEX */ "Mexiko",
        /*     MOW */ "Moskau",
        /*     SPE */ "Saint Petersburg",
        /*     KGD */ "Kaliningrad Oblast",
        /*   RU-IN */ "Inguschetien Republik",
        /*   RU-AD */ "Adygea Republik",
        /*   RU-SE */ "Nordossetien-Alania Republic",
        /*   RU-KB */ "Kabardino-Balkarien",
        /*   RU-KC */ "Karatschai-Tscherkessien Republik",
        /*   RU-CE */ "Tschetschenische Republik",
        /*   RU-CU */ "Republik Tschuwaschien",
        /*     IVA */ "Ivanovo Oblast",
        /*     LIP */ "Lipetsk Oblast",
        /*     ORL */ "Orjol Oblast",
        /*     TUL */ "Tula Oblast",
        /*   RU-BE */ "Belgorod Oblast",
        /*     VLA */ "Vladimir Oblast",
        /*     KRS */ "Kursk Oblast",
        /*     KLU */ "Kaluga",
        /*   RU-TT */ "Tambov Oblast",
        /*     BRY */ "Brjansk",
        /*     YAR */ "Oblast Jaroslawl",
        /*     RYA */ "Ryazan Oblast",
        /*     AST */ "Astrakhan Oblast",
        /*     MOS */ "Oblast Moskau",
        /*     SMO */ "Smolensk Oblast",
        /*   RU-DA */ "Republik Dagestan",
        /*     VOR */ "Voronezh Oblast",
        /*     NGR */ "Novgorod Oblast",
        /*     PSK */ "Pskov Oblast",
        /*     KOS */ "Kostroma Oblast",
        /*     STA */ "Stawropol",
        /*     KDA */ "Krasnodar Krai",
        /*   RU-KL */ "Kalmykia Republik",
        /*     TVE */ "Oblast Twer",
        /*     LEN */ "Leningrad Oblast",
        /*     ROS */ "Rostov Oblast",
        /*     VGG */ "Volgograd Oblast",
        /*     VLG */ "Vologda",
        /*     MUR */ "Murmansk Oblast",
        /*   RU-KR */ "Republik Karelien",
        /*     NEN */ "Nenzen",
        /*   RU-KO */ "Republik Komi",
        /*     ARK */ "Archangelsk Oblast",
        /*   RU-MO */ "Mordovia Republic",
        /*     NIZ */ "Nizhny Novgorod Oblast",
        /*     PNZ */ "Penza Oblast",
        /*   RU-KI */ "Kirov Oblast",
        /*   RU-ME */ "Republik Mari El",
        /*     ORE */ "Orenburg Oblast",
        /*     ULY */ "Uljanowsk",
        /*   RU-PM */ "Perm Krai",
        /*   RU-BA */ "Republik Baschkortostan",
        /*   RU-UD */ "Republik Udmurtien",
        /*   RU-TA */ "Republik Tatarstan",
        /*     SAM */ "Samara Oblast",
        /*     SAR */ "Saratov Oblast",
        /*     YAN */ "Jamal-Nenzen",
        /*   RU-KM */ "Khanty-Mansi",
        /*     SVE */ "Oblast Swerdlowsk",
        /*     TYU */ "Tyumen Oblast",
        /*     KGN */ "Kurgan",
        /*   RU-CH */ "Chelyabinsk Oblast",
        /*   RU-BU */ "Burjatien Republik",
        /*     ZAB */ "Zabaykalsky Krai",
        /*     IRK */ "Irkutsk Oblast",
        /*     NVS */ "Novosibirsk Oblast",
        /*     TOM */ "Tomsk Oblast",
        /*     OMS */ "Omsk Oblast",
        /*   RU-KK */ "Chakassien Republik",
        /*     KEM */ "Kemerowo",
        /*   RU-AL */ "Altai Republik",
        /*     ALT */ "Altai Krai",
        /*   RU-TY */ "Tuva Republik",
        /*     KYA */ "Krasnoyarsk Krai",
        /*     MAG */ "Magadan Oblast",
        /*     CHU */ "Tschukotka Okrug",
        /*     KAM */ "Kamchatka Krai",
        /*     SAK */ "Sachalin Oblast",
        /*   RU-PO */ "Primorsky Krai",
        /*     YEV */ "Jüdischen Autonomen Oblast",
        /*     KHA */ "Khabarovsk Krai",
        /*     AMU */ "Amur Oblast",
        /*   RU-SA */ "Republik Sacha|Yakutia Republic",
        /*     CAN */ "Kanada",
        /*     RUS */ "Russland",
        /*   CN-SH */ "Shanghai",
        /*   CN-TJ */ "Tianjin",
        /*   CN-BJ */ "Peking",
        /*   CN-HI */ "Hainan",
        /*   CN-NX */ "Ningxia Hui",
        /*   CN-CQ */ "Chongqing",
        /*   CN-ZJ */ "Zhejiang",
        /*   CN-JS */ "Jiangsu",
        /*   CN-FJ */ "Fujian",
        /*   CN-AH */ "Anhui",
        /*   CN-LN */ "Liaoning",
        /*   CN-SD */ "Shandong",
        /*   CN-SX */ "Shanxi",
        /*   CN-JX */ "Jiangxi",
        /*   CN-HA */ "Henan",
        /*   CN-GZ */ "Guizhou",
        /*   CN-GD */ "Guangdong",
        /*   CN-HB */ "Hubei",
        /*   CN-JL */ "Jilin",
        /*   CN-HE */ "Hebei",
        /*   CN-SN */ "Shaanxi",
        /*   CN-NM */ "Nei Mongol|Inner Mongolia",
        /*   CN-HL */ "Heilongjiang",
        /*   CN-HN */ "Hunan",
        /*   CN-GX */ "Guangxi Zhuang",
        /*   CN-SC */ "Sichuan",
        /*   CN-YN */ "Yunnan",
        /*   CN-XZ */ "Xizang|Tibet",
        /*   CN-GS */ "Gansu",
        /*   CN-QH */ "Qinghai",
        /*   CN-XJ */ "Xinjiang Uiguren",
        /*     CHN */ "China",
        /*     UMI */ "United States Minor Outlying Islands",
        /*     CPT */ "Clipperton-Insel",
        /*     ATA */ "Antarktis",
        /*     AAA */ "International|Weltweit|Erde"
#else // MAPCODE_SUPPORT_LANGUAGE_DE
        NULL
#endif // MAPCODE_SUPPORT_LANGUAGE_DE
};

#ifdef __cplusplus
}
#endif

#endif // __INTERNAL_TERRITORY_NAMES_DE_H__
