/*
 * Copyright (C) 2014-2017 Stichting Mapcode Foundation (http://www.mapcode.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef __INTERNAL_TERRITORY_NAMES_CS_H__
#define __INTERNAL_TERRITORY_NAMES_CS_H__

#ifdef __cplusplus
extern "C" {
#endif

// *** GENERATED FILE (coords.cpp), DO NOT CHANGE OR PRETTIFY ***

static const char *TERRITORY_FULL_NAME_CS[] = {
#ifdef MAPCODE_SUPPORT_LANGUAGE_CS // Czech
        /*     VAT */ "Vatikán|Svatý stolec",
        /*     MCO */ "Monaco",
        /*     GIB */ "Gibraltar",
        /*     TKL */ "Tokelau",
        /*     CCK */ "Kokosové ostrovy|Keeling Islands",
        /*     BLM */ "Saint-Barthelemy",
        /*     NRU */ "Nauru",
        /*     TUV */ "Tuvalu",
        /*     MAC */ "Macau",
        /*     SXM */ "Sint Maarten",
        /*     MAF */ "Saint-Martin",
        /*     NFK */ "Norfolk a Philip Island|Philip Island",
        /*     PCN */ "Pitcairn",
        /*     BVT */ "Bouvetův ostrov",
        /*     BMU */ "Bermudy",
        /*     IOT */ "Britské indickooceánské území",
        /*     SMR */ "San Marino",
        /*     GGY */ "Guernsey",
        /*     AIA */ "Anguilla",
        /*     MSR */ "Montserrat",
        /*     JEY */ "Jersey",
        /*     CXR */ "Vánoční ostrov",
        /*     WLF */ "Wallis a Futuna|Futuně",
        /*     VGB */ "Britské Panenské ostrovy|Britské Panenské ostrovy",
        /*     LIE */ "Lichtenštejnsko",
        /*     ABW */ "Aruba",
        /*     MHL */ "Marshallovy ostrovy",
        /*     ASM */ "Americká Samoa|Samoa, Američan",
        /*     COK */ "Cookovy ostrovy",
        /*     SPM */ "Saint-Pierre a Miquelon|Miquelon",
        /*     NIU */ "Niue",
        /*     KNA */ "Svatý Kryštof a Nevis|Nevis",
        /*     CYM */ "Kajmanské ostrovy",
        /*     BES */ "Bonaire, St Eustatuis a Saba|Saba|St Eustatius",
        /*     MDV */ "Maledivy",
        /*     SHN */ "Svatá Helena, Ascension a Tristan da Cunha|Ascension|Tristan da Cunha",
        /*     MLT */ "Malta",
        /*     GRD */ "Grenada",
        /*     VIR */ "Americké Panenské ostrovy|Panenské ostrovy, USA",
        /*     MYT */ "Mayotte",
        /*     SJM */ "Svalbard a Jan Mayen|Jan Mayen",
        /*     VCT */ "Svatý Vincenc a Grenadiny|Grenadiny",
        /*     HMD */ "Heardův ostrov a McDonaldovy ostrovy|McDonald ostrovy",
        /*     BRB */ "Barbados",
        /*     ATG */ "Antigua a Barbuda|Barbuda",
        /*     CUW */ "Curacao",
        /*     SYC */ "Seychely",
        /*     PLW */ "Palau",
        /*     MNP */ "Severní Mariany",
        /*     AND */ "Andorra",
        /*     GUM */ "Guam",
        /*     IMN */ "Isle of Man",
        /*     LCA */ "svatá Lucie",
        /*     FSM */ "Mikronésie|Federativní státy Mikronésie",
        /*     SGP */ "Singapore",
        /*     TON */ "Tonga",
        /*     DMA */ "Dominika",
        /*     BHR */ "Bahrajn",
        /*     KIR */ "Kiribati",
        /*     TCA */ "Turks a Caicos|Caicos",
        /*     STP */ "Sao Tome a Principe|Principe",
        /*     HKG */ "Hongkong",
        /*     MTQ */ "Martinik",
        /*     FRO */ "Faerské ostrovy",
        /*     GLP */ "Guadeloupe",
        /*     COM */ "Komory",
        /*     MUS */ "Mauritius",
        /*     REU */ "Shledání",
        /*     LUX */ "Lucembursko",
        /*     WSM */ "Samoa",
        /*     SGS */ "Jižní Georgie a Jižní Sandwichovy ostrovy|Jižní Sandwichovy ostrovy",
        /*     PYF */ "Francouzská Polynésie",
        /*     CPV */ "Kapverdy",
        /*     TTO */ "Trinidad a Tobago|Tobago",
        /*     BRN */ "Brunej",
        /*     ATF */ "Francouzská jižní a antarktická území",
        /*     PRI */ "Portoriko",
        /*     CYP */ "Kypr",
        /*     LBN */ "Libanon",
        /*     JAM */ "Jamaica",
        /*     GMB */ "Gambie",
        /*     QAT */ "Katar",
        /*     FLK */ "Falklandy",
        /*     VUT */ "Vanuatu",
        /*     MNE */ "Černá Hora",
        /*     BHS */ "Bahamské ostrovy",
        /*     TLS */ "Východní Timor",
        /*     SWZ */ "Svazijsko",
        /*     KWT */ "Kuvajt",
        /*     FJI */ "Fidži ostrovy",
        /*     NCL */ "Nová Kaledonie",
        /*     SVN */ "Slovinsko",
        /*     ISR */ "Izrael",
        /*     PSE */ "Palestinská území",
        /*     SLV */ "El Salvador",
        /*     BLZ */ "Belize",
        /*     DJI */ "Džibutsko",
        /*     MKD */ "Makedonie",
        /*     RWA */ "Rwanda",
        /*     HTI */ "Haiti",
        /*     BDI */ "Burundi",
        /*     GNQ */ "Rovníková Guinea",
        /*     ALB */ "Albánie",
        /*     SLB */ "Šalamounovy ostrovy",
        /*     ARM */ "Arménie",
        /*     LSO */ "Lesotho",
        /*     BEL */ "Belgie",
        /*     MDA */ "Moldavsko",
        /*     GNB */ "Guinea-Bissau",
        /*     TWN */ "Tchaj-wan",
        /*     BTN */ "Bhůtán",
        /*     CHE */ "Švýcarsko",
        /*     NLD */ "Nizozemí",
        /*     DNK */ "Dánsko",
        /*     EST */ "Estonsko",
        /*     DOM */ "Dominikánská republika",
        /*     SVK */ "Slovensko",
        /*     CRI */ "Kostarika",
        /*     BIH */ "Bosna a Hercegovina",
        /*     HRV */ "Chorvatsko",
        /*     TGO */ "Togo",
        /*     LVA */ "Lotyšsko",
        /*     LTU */ "Litva",
        /*     LKA */ "Srí Lanka",
        /*     GEO */ "Georgia",
        /*     IRL */ "Irsko",
        /*     SLE */ "Sierra Leone",
        /*     PAN */ "Panama",
        /*     CZE */ "Česká republika",
        /*     GUF */ "Francouzsky Guyana",
        /*     ARE */ "Spojené arabské emiráty",
        /*     AUT */ "Rakousko",
        /*     AZE */ "Ázerbajdžán",
        /*     SRB */ "Srbsko",
        /*     JOR */ "Jordán",
        /*     PRT */ "Portugalsko",
        /*     HUN */ "Maďarsko",
        /*     KOR */ "Jižní Korea",
        /*     ISL */ "Island",
        /*     GTM */ "Guatemala",
        /*     CUB */ "Kuba",
        /*     BGR */ "Bulharsko",
        /*     LBR */ "Libérie",
        /*     HND */ "Honduras",
        /*     BEN */ "Benin",
        /*     ERI */ "Eritrea",
        /*     MWI */ "Malawi",
        /*     PRK */ "Severní Korea",
        /*     NIC */ "Nikaragua",
        /*     GRC */ "Řecko",
        /*     TJK */ "Tádžikistán",
        /*     BGD */ "Bangladéš",
        /*     NPL */ "Nepál",
        /*     TUN */ "Tunisko",
        /*     SUR */ "Surinam",
        /*     URY */ "Uruguay",
        /*     KHM */ "Kambodža",
        /*     SYR */ "Sýrie",
        /*     SEN */ "Senegal",
        /*     KGZ */ "Kyrgyzstán",
        /*     BLR */ "Bělorusko",
        /*     GUY */ "Guyana",
        /*     LAO */ "Laos",
        /*     ROU */ "Rumunsko",
        /*     GHA */ "Ghana",
        /*     UGA */ "Uganda",
        /*     GBR */ "Spojené království|Skotsko|Velká Británie|Severní Irsko|Ireland, Northern",
        /*     GIN */ "Guinea",
        /*     ECU */ "Ekvádor",
        /*     ESH */ "Západní Sahara|Sahrawi",
        /*     GAB */ "Gabon",
        /*     NZL */ "Nový Zéland",
        /*     BFA */ "Burkina Faso",
        /*     PHL */ "Filipíny",
        /*     ITA */ "Itálie",
        /*     OMN */ "Omán",
        /*     POL */ "Polsko",
        /*     CIV */ "Pobřeží slonoviny",
        /*     NOR */ "Norsko",
        /*     MYS */ "Malajsie",
        /*     VNM */ "Vietnam",
        /*     FIN */ "Finsko",
        /*     COG */ "Kongo-Brazzaville",
        /*     DEU */ "Německo",
        /*     JPN */ "Japonsko",
        /*     ZWE */ "Zimbabwe",
        /*     PRY */ "Paraguay",
        /*     IRQ */ "Irák",
        /*     MAR */ "Maroko",
        /*     UZB */ "Uzbekistán",
        /*     SWE */ "Švédsko",
        /*     PNG */ "Papua-Nová Guinea",
        /*     CMR */ "Kamerun",
        /*     TKM */ "Turkmenistán",
        /*     ESP */ "Španělsko",
        /*     THA */ "Thailand",
        /*     YEM */ "Jemen",
        /*     FRA */ "Francie",
        /*     ALA */ "Alandské ostrovy",
        /*     KEN */ "Keňa",
        /*     BWA */ "Botswana",
        /*     MDG */ "Madagaskar",
        /*     UKR */ "Ukrajina",
        /*     SSD */ "Jižní Súdán",
        /*     CAF */ "Středoafrická republika",
        /*     SOM */ "Somálsko",
        /*     AFG */ "Afghánistán",
        /*     MMR */ "Myanmar|Barma",
        /*     ZMB */ "Zambie",
        /*     CHL */ "Chile",
        /*     TUR */ "Turecko",
        /*     PAK */ "Pákistán",
        /*     MOZ */ "Mosambik",
        /*     NAM */ "Namibie",
        /*     VEN */ "Venezuela",
        /*     NGA */ "Nigérie",
        /*     TZA */ "Tanzanie",
        /*     EGY */ "Egypt",
        /*     MRT */ "Mauritánie",
        /*     BOL */ "Bolívie",
        /*     ETH */ "Etiopie",
        /*     COL */ "Kolumbie",
        /*     ZAF */ "Jižní Afrika",
        /*     MLI */ "Mali",
        /*     AGO */ "Angola",
        /*     NER */ "Niger",
        /*     TCD */ "Chad",
        /*     PER */ "Peru",
        /*     MNG */ "Mongolsko",
        /*     IRN */ "Írán",
        /*     LBY */ "Libye",
        /*     SDN */ "Súdán",
        /*     IDN */ "Indonésie",
        /*     DIF */ "Federální Okruh",
        /*     TLA */ "Tlaxcala",
        /*     MOR */ "Morelos",
        /*     AGU */ "Aguascalientes",
        /*   MX-CL */ "Colima",
        /*     QUE */ "Queretaro",
        /*     HID */ "Hidalgo",
        /*   MX-MX */ "Mexico State",
        /*     TAB */ "Tabasco",
        /*     NAY */ "Nayarit",
        /*     GUA */ "Guanajuato",
        /*     PUE */ "Puebla",
        /*     YUC */ "Yucatan",
        /*     ROO */ "Quintana Roo",
        /*     SIN */ "Sinaloa",
        /*     CAM */ "Campeche",
        /*     MIC */ "Michoacan",
        /*     SLP */ "San Luis Potosi",
        /*     GRO */ "Guerrero",
        /*     NLE */ "Nuevo Leon",
        /*     BCN */ "Baja California",
        /*     VER */ "Veracruz",
        /*     CHP */ "Chiapas",
        /*     BCS */ "Baja California Sur",
        /*     ZAC */ "Zacatecas",
        /*     JAL */ "Jalisco",
        /*     TAM */ "Tamaulipas",
        /*     OAX */ "Oaxaca",
        /*     DUR */ "Durango",
        /*     COA */ "Coahuila",
        /*     SON */ "Sonora",
        /*     CHH */ "Chihuahua",
        /*     GRL */ "Grónsko",
        /*     SAU */ "Saudská arábie",
        /*     COD */ "Kongo-Kinshasa",
        /*     DZA */ "Alžírsko",
        /*     KAZ */ "Kazachstán",
        /*     ARG */ "Argentina",
        /*   IN-DD */ "Daman a Diu",
        /*   IN-DN */ "Dadra a Nagar Haveli",
        /*   IN-CH */ "Chandigarh",
        /*   IN-AN */ "Andaman a Nicobar",
        /*   IN-LD */ "Lakshadweep",
        /*   IN-DL */ "Delhi",
        /*   IN-ML */ "Meghalaya",
        /*   IN-NL */ "Nagaland",
        /*   IN-MN */ "Manipur",
        /*   IN-TR */ "Tripura",
        /*   IN-MZ */ "Mizoram",
        /*   IN-SK */ "Sikkim",
        /*   IN-PB */ "Paňdžáb",
        /*   IN-HR */ "Haryana",
        /*   IN-AR */ "Arunáčalpradéš",
        /*   IN-AS */ "Assam",
        /*   IN-BR */ "Bihar",
        /*   IN-UT */ "Uttarakhand",
        /*   IN-GA */ "Goa",
        /*   IN-KL */ "Kerala",
        /*   IN-TN */ "Tamil Nadu",
        /*   IN-HP */ "Himáčalpradéš",
        /*   IN-JK */ "Džammú a Kašmír",
        /*   IN-CT */ "Chhattisgarh",
        /*   IN-JH */ "Jharkhand",
        /*   IN-KA */ "Karnataka",
        /*   IN-RJ */ "Rajasthan",
        /*   IN-OR */ "Urísa|Orissa",
        /*   IN-GJ */ "Gujarat",
        /*   IN-WB */ "West Bengal",
        /*   IN-MP */ "Madhjapradéš",
        /*   IN-TG */ "Telangana",
        /*   IN-AP */ "Andhra Pradesh",
        /*   IN-MH */ "Maharashtra",
        /*   IN-UP */ "Uttar Pradesh",
        /*   IN-PY */ "Puducherry",
        /*     NSW */ "Nový Jížní Wales",
        /*     ACT */ "Australian Capital Territory",
        /*     JBT */ "Jervis Bay Territory",
        /*   AU-NT */ "Northern Territory",
        /*   AU-SA */ "Jižní Austrálie",
        /*     TAS */ "Tasmánie",
        /*     VIC */ "Victoria",
        /*   AU-WA */ "Západní Austrálie",
        /*     QLD */ "Queensland",
        /*   BR-DF */ "Distrito Federal",
        /*   BR-SE */ "Sergipe",
        /*   BR-AL */ "Alagoas",
        /*   BR-RJ */ "Rio de Janeiro",
        /*   BR-ES */ "Espirito Santo",
        /*   BR-RN */ "Rio Grande do Norte",
        /*   BR-PB */ "Paraiba",
        /*   BR-SC */ "Santa Catarina",
        /*   BR-PE */ "Pernambuco",
        /*   BR-AP */ "Amapa",
        /*   BR-CE */ "Ceara",
        /*   BR-AC */ "Acre",
        /*   BR-PR */ "Parana",
        /*   BR-RR */ "Roraima",
        /*   BR-RO */ "Rondonia",
        /*   BR-SP */ "Sao Paulo",
        /*   BR-PI */ "Piaui",
        /*   BR-TO */ "Tocantins",
        /*   BR-RS */ "Rio Grande do Sul",
        /*   BR-MA */ "Maranhao",
        /*   BR-GO */ "Goias",
        /*   BR-MS */ "Mato Grosso do Sul",
        /*   BR-BA */ "Bahia",
        /*   BR-MG */ "Minas Gerais",
        /*   BR-MT */ "Mato Grosso",
        /*   BR-PA */ "para",
        /*   BR-AM */ "Amazonas",
        /*   US-DC */ "Washington, D.C.",
        /*   US-RI */ "Rhode Island",
        /*   US-DE */ "Delaware",
        /*   US-CT */ "Connecticut",
        /*   US-NJ */ "New Jersey",
        /*   US-NH */ "New Hampshire",
        /*   US-VT */ "Vermont",
        /*   US-MA */ "Massachusetts",
        /*   US-HI */ "Havaj",
        /*   US-MD */ "Maryland",
        /*   US-WV */ "West Virginia",
        /*   US-SC */ "Jižní Karolína",
        /*   US-ME */ "Maine",
        /*   US-IN */ "Indiana",
        /*   US-KY */ "Kentucky",
        /*   US-TN */ "Tennessee",
        /*   US-VA */ "Virginia",
        /*   US-OH */ "Ohio",
        /*   US-PA */ "Pennsylvania",
        /*   US-MS */ "Mississippi",
        /*   US-LA */ "Louisiana",
        /*   US-AL */ "Alabama",
        /*   US-AR */ "Arkansas",
        /*   US-NC */ "Severní Karolína",
        /*   US-NY */ "New York",
        /*   US-IA */ "Iowa",
        /*   US-IL */ "Illinois",
        /*   US-GA */ "Georgia",
        /*   US-WI */ "Wisconsin",
        /*   US-FL */ "Florida",
        /*   US-MO */ "Missouri",
        /*   US-OK */ "Oklahoma",
        /*   US-ND */ "Severní Dakota",
        /*   US-WA */ "Washington",
        /*   US-SD */ "Jižní Dakota",
        /*   US-NE */ "Nebraska",
        /*   US-KS */ "Kansas",
        /*   US-ID */ "Idaho",
        /*   US-UT */ "Utah",
        /*   US-MN */ "Minnesota",
        /*   US-MI */ "Michigan",
        /*   US-WY */ "Wyoming",
        /*   US-OR */ "Oregon",
        /*   US-CO */ "Colorado",
        /*   US-NV */ "Nevada",
        /*   US-AZ */ "Arizona",
        /*   US-NM */ "Nové Mexiko",
        /*   US-MT */ "Montana",
        /*   US-CA */ "Kalifornie",
        /*   US-TX */ "Texas",
        /*   US-AK */ "Aljaška",
        /*   CA-BC */ "Britská Kolumbie",
        /*   CA-AB */ "Alberta",
        /*   CA-ON */ "Ontario",
        /*   CA-QC */ "Quebec",
        /*   CA-SK */ "Saskatchewan",
        /*   CA-MB */ "Manitoba",
        /*   CA-NL */ "Novofundlanďan",
        /*   CA-NB */ "Nový Brunswick",
        /*   CA-NS */ "Nové Skotsko",
        /*   CA-PE */ "Prince Edward Island",
        /*   CA-YT */ "Yukon",
        /*   CA-NT */ "Severozápadní teritoria",
        /*   CA-NU */ "Nunavut",
        /*     IND */ "Indie",
        /*     AUS */ "Austrálie",
        /*     BRA */ "Brazílie",
        /*     USA */ "USA|United States of America|America",
        /*     MEX */ "Mexiko",
        /*     MOW */ "Moskva",
        /*     SPE */ "Petrohrad",
        /*     KGD */ "Kaliningrad Oblast",
        /*   RU-IN */ "Ingušsko Republic",
        /*   RU-AD */ "Adygea Republic",
        /*   RU-SE */ "Severní Osetie-Alanie Republic",
        /*   RU-KB */ "Kabardino-Balkar Republic",
        /*   RU-KC */ "Karachay-Cherkess Republic",
        /*   RU-CE */ "čečenská republika",
        /*   RU-CU */ "Chuvash Republic",
        /*     IVA */ "Ivanovo Oblast",
        /*     LIP */ "Lipecká oblast",
        /*     ORL */ "Orelská oblast",
        /*     TUL */ "Tula Oblast",
        /*   RU-BE */ "Belgorod Oblast",
        /*     VLA */ "Vladimir Oblast",
        /*     KRS */ "Kursk Oblast",
        /*     KLU */ "Kaluga Oblast",
        /*   RU-TT */ "Tambov Oblast",
        /*     BRY */ "Brjanská oblast",
        /*     YAR */ "Jaroslavl Oblast",
        /*     RYA */ "Ryazan Oblast",
        /*     AST */ "Astrachaň Oblast",
        /*     MOS */ "Moskva Oblast",
        /*     SMO */ "Smolenská oblast",
        /*   RU-DA */ "Dagestan Republic",
        /*     VOR */ "Voronezh Oblast",
        /*     NGR */ "Novgorod Oblast",
        /*     PSK */ "Pskov Oblast",
        /*     KOS */ "Kostroma Oblast",
        /*     STA */ "Stavropol Krai",
        /*     KDA */ "Krasnodar Krai",
        /*   RU-KL */ "Kalmykia Republic",
        /*     TVE */ "Tverská oblast",
        /*     LEN */ "Leningrad Oblast",
        /*     ROS */ "Rostov Oblast",
        /*     VGG */ "Volgogradská oblast",
        /*     VLG */ "Vologda Oblast",
        /*     MUR */ "Murmansk Oblast",
        /*   RU-KR */ "Karélie Republic",
        /*     NEN */ "Něnecký autonomní okruh",
        /*   RU-KO */ "Komi Republic",
        /*     ARK */ "Arkhangelsk Oblast",
        /*   RU-MO */ "Mordovie Republic",
        /*     NIZ */ "Nižněnovgorodská oblast",
        /*     PNZ */ "Penza Oblast",
        /*   RU-KI */ "Kirov Oblast",
        /*   RU-ME */ "Mari El republika",
        /*     ORE */ "Orenburg Oblast",
        /*     ULY */ "Ulyanovsk Oblast",
        /*   RU-PM */ "Perm Krai",
        /*   RU-BA */ "Baškortostán Republic",
        /*   RU-UD */ "Udmurt Republic",
        /*   RU-TA */ "Tatarstán republiky",
        /*     SAM */ "Samarská oblast",
        /*     SAR */ "Saratov Oblast",
        /*     YAN */ "Jamalskon Nenets",
        /*   RU-KM */ "Chanty-Mansi",
        /*     SVE */ "Sverdlovsk Oblast",
        /*     TYU */ "Tyumen Oblast",
        /*     KGN */ "Kurgan Oblast",
        /*   RU-CH */ "Čeljabinsk Oblast",
        /*   RU-BU */ "Buryatia Republic",
        /*     ZAB */ "Zabajkalský kraj",
        /*     IRK */ "Irkutsk Oblast",
        /*     NVS */ "Novosibirsk Oblast",
        /*     TOM */ "Tomsk Oblast",
        /*     OMS */ "Omsk Oblast",
        /*   RU-KK */ "Chakaské republice",
        /*     KEM */ "Kemerovo Oblast",
        /*   RU-AL */ "Altai Republic",
        /*     ALT */ "Altai Krai",
        /*   RU-TY */ "Tuva Republic",
        /*     KYA */ "Krasnojarský kraj",
        /*     MAG */ "Magadan Oblast",
        /*     CHU */ "Čukotka Okrug",
        /*     KAM */ "Kamčatský kraj",
        /*     SAK */ "Sakhalin Oblast",
        /*   RU-PO */ "Primorsky Krai",
        /*     YEV */ "Židovská autonomní oblast",
        /*     KHA */ "Chabarovský kraj",
        /*     AMU */ "Amur Oblast",
        /*   RU-SA */ "Sacha|Jakutsko republika",
        /*     CAN */ "Kanada",
        /*     RUS */ "Rusko",
        /*   CN-SH */ "Shanghai",
        /*   CN-TJ */ "Tianjin",
        /*   CN-BJ */ "Peking",
        /*   CN-HI */ "Hainan",
        /*   CN-NX */ "Ningxia Hui",
        /*   CN-CQ */ "Chongqing",
        /*   CN-ZJ */ "Zhejiang",
        /*   CN-JS */ "Jiangsu",
        /*   CN-FJ */ "Fujian",
        /*   CN-AH */ "Anhui",
        /*   CN-LN */ "Liaoning",
        /*   CN-SD */ "Shandong",
        /*   CN-SX */ "Shanxi",
        /*   CN-JX */ "Jiangxi",
        /*   CN-HA */ "Henan",
        /*   CN-GZ */ "Guizhou",
        /*   CN-GD */ "Guangdong",
        /*   CN-HB */ "Hubei",
        /*   CN-JL */ "Jilin",
        /*   CN-HE */ "Hebei",
        /*   CN-SN */ "Shaanxi",
        /*   CN-NM */ "Nei Mongol|Vnitřní Mongolsko",
        /*   CN-HL */ "Heilongjiang",
        /*   CN-HN */ "Hunan",
        /*   CN-GX */ "Guangxi Zhuang",
        /*   CN-SC */ "Sichuan",
        /*   CN-YN */ "Yunnan",
        /*   CN-XZ */ "Xizang|Tibet",
        /*   CN-GS */ "Gansu",
        /*   CN-QH */ "Qinghai",
        /*   CN-XJ */ "Xinjiang Uyghur",
        /*     CHN */ "Čína",
        /*     UMI */ "Menší americké odlehlé ostrovy",
        /*     CPT */ "Clipperton Island",
        /*     ATA */ "Antarctica",
        /*     AAA */ "Svět|Mezinárodní|Země"
#else // MAPCODE_SUPPORT_LANGUAGE_CS
        NULL
#endif // MAPCODE_SUPPORT_LANGUAGE_CS
};

#ifdef __cplusplus
}
#endif

#endif // __INTERNAL_TERRITORY_NAMES_CS_H__
