/*
 * Copyright (C) 2014-2017 Stichting Mapcode Foundation (http://www.mapcode.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef __INTERNAL_TERRITORY_NAMES_DA_H__
#define __INTERNAL_TERRITORY_NAMES_DA_H__

#ifdef __cplusplus
extern "C" {
#endif

// *** GENERATED FILE (coords.cpp), DO NOT CHANGE OR PRETTIFY ***

static const char *TERRITORY_FULL_NAME_DA[] = {
#ifdef MAPCODE_SUPPORT_LANGUAGE_DA // Danish
        /*     VAT */ "Vatikanstaten|Pavestolen",
        /*     MCO */ "Monaco",
        /*     GIB */ "Gibraltar",
        /*     TKL */ "Tokelau",
        /*     CCK */ "Cocosøerne|Keeling Islands",
        /*     BLM */ "Saint-Barthelemy",
        /*     NRU */ "Nauru",
        /*     TUV */ "Tuvalu",
        /*     MAC */ "Macau",
        /*     SXM */ "Sint Maarten",
        /*     MAF */ "Saint-Martin",
        /*     NFK */ "Norfolk og Philip Island|Philip Island",
        /*     PCN */ "Pitcairn",
        /*     BVT */ "Bouvetø",
        /*     BMU */ "Bermuda",
        /*     IOT */ "British Indian Ocean Territory",
        /*     SMR */ "San Marino",
        /*     GGY */ "Guernsey",
        /*     AIA */ "Anguilla",
        /*     MSR */ "Montserrat",
        /*     JEY */ "Jersey",
        /*     CXR */ "Juleøen",
        /*     WLF */ "Wallis-og Futuna|Futuna",
        /*     VGB */ "British Virgin Islands|Virgin Islands, British",
        /*     LIE */ "Liechtenstein",
        /*     ABW */ "Aruba",
        /*     MHL */ "Marshalløerne",
        /*     ASM */ "Amerikansk Samoa|Samoa, Amerikansk",
        /*     COK */ "Cookøerne",
        /*     SPM */ "Saint Pierre og Miquelon|Miquelon",
        /*     NIU */ "Niue",
        /*     KNA */ "Saint Kitts og Nevis|Nevis",
        /*     CYM */ "Cayman Islands",
        /*     BES */ "Bonaire, Saint Eustasuis og Saba|Saba|St Eustasius",
        /*     MDV */ "Maldiverne",
        /*     SHN */ "Saint Helena, Ascension og Tristan da Cunha|Kristi Himmelfart|Tristan da Cunha",
        /*     MLT */ "Malta",
        /*     GRD */ "Grenada",
        /*     VIR */ "US Virgin Islands|Virgin Islands, USA",
        /*     MYT */ "Mayotte",
        /*     SJM */ "Svalbard and Jan Mayen|Jan Mayen",
        /*     VCT */ "Saint Vincent og Grenadinerne|Grenadinerne",
        /*     HMD */ "Heard og McDonald-øerne|McDonald Islands",
        /*     BRB */ "Barbados",
        /*     ATG */ "Antigua og Barbuda|Barbuda",
        /*     CUW */ "Curacao",
        /*     SYC */ "Seychellerne",
        /*     PLW */ "Palau",
        /*     MNP */ "Nordmarianerne",
        /*     AND */ "Andorra",
        /*     GUM */ "Guam",
        /*     IMN */ "Isle of Man",
        /*     LCA */ "Saint Lucia",
        /*     FSM */ "Micronesia|Federated States of Micronesia",
        /*     SGP */ "Singapore",
        /*     TON */ "Tonga",
        /*     DMA */ "Dominica",
        /*     BHR */ "Bahrain",
        /*     KIR */ "Kiribati",
        /*     TCA */ "Turks-og Caicosøerne|Caicosøerne",
        /*     STP */ "Sao Tome og Principe|Principe",
        /*     HKG */ "Hong Kong",
        /*     MTQ */ "Martinique",
        /*     FRO */ "Færøerne",
        /*     GLP */ "Guadeloupe",
        /*     COM */ "Comorerne",
        /*     MUS */ "Mauritius",
        /*     REU */ "Reunion",
        /*     LUX */ "Luxembourg",
        /*     WSM */ "Samoa",
        /*     SGS */ "South Georgia og De Sydlige Sandwichøer|Sydsandwichøerne",
        /*     PYF */ "Fransk Polynesien",
        /*     CPV */ "Kap Verde",
        /*     TTO */ "Trinidad og Tobago|Tobago",
        /*     BRN */ "Brunei",
        /*     ATF */ "Franske sydlige og antarktiske Lands",
        /*     PRI */ "Puerto Rico",
        /*     CYP */ "Cypern",
        /*     LBN */ "Libanon",
        /*     JAM */ "Jamaica",
        /*     GMB */ "Gambia",
        /*     QAT */ "Qatar",
        /*     FLK */ "Falklandsøerne",
        /*     VUT */ "Vanuatu",
        /*     MNE */ "Montenegro",
        /*     BHS */ "Bahamas",
        /*     TLS */ "Østtimor",
        /*     SWZ */ "Swaziland",
        /*     KWT */ "Kuwait",
        /*     FJI */ "Fijiøerne",
        /*     NCL */ "Ny Kaledonien",
        /*     SVN */ "Slovenien",
        /*     ISR */ "Israel",
        /*     PSE */ "Palestinian territory",
        /*     SLV */ "Salvador",
        /*     BLZ */ "Belize",
        /*     DJI */ "Djibouti",
        /*     MKD */ "Makedonien",
        /*     RWA */ "Rwanda",
        /*     HTI */ "Haiti",
        /*     BDI */ "Burundi",
        /*     GNQ */ "Ækvatorial Guinea",
        /*     ALB */ "Albanien",
        /*     SLB */ "Salomonøerne",
        /*     ARM */ "Armenien",
        /*     LSO */ "Lesotho",
        /*     BEL */ "Belgien",
        /*     MDA */ "Moldova",
        /*     GNB */ "Guinea-Bissau",
        /*     TWN */ "Taiwan",
        /*     BTN */ "Bhutan",
        /*     CHE */ "Schweiz",
        /*     NLD */ "Holland",
        /*     DNK */ "Danmark",
        /*     EST */ "Estland",
        /*     DOM */ "Den Dominikanske Republik",
        /*     SVK */ "Slovakiet",
        /*     CRI */ "Costa Rica",
        /*     BIH */ "Bosnien og Hercegovina",
        /*     HRV */ "Kroatien",
        /*     TGO */ "Togo",
        /*     LVA */ "Letland",
        /*     LTU */ "Litauen",
        /*     LKA */ "Sri Lanka",
        /*     GEO */ "Georgia",
        /*     IRL */ "Irland",
        /*     SLE */ "Sierra Leone",
        /*     PAN */ "Panama",
        /*     CZE */ "Tjekkiet",
        /*     GUF */ "Fransk Guyana",
        /*     ARE */ "Forenede Arabiske Emirater",
        /*     AUT */ "Østrig",
        /*     AZE */ "Aserbajdsjan",
        /*     SRB */ "Serbia",
        /*     JOR */ "Jordan",
        /*     PRT */ "Portugal",
        /*     HUN */ "Ungarn",
        /*     KOR */ "Sydkorea",
        /*     ISL */ "Island",
        /*     GTM */ "Guatemala",
        /*     CUB */ "Cuba",
        /*     BGR */ "Bulgarien",
        /*     LBR */ "Liberia",
        /*     HND */ "Honduras",
        /*     BEN */ "Benin",
        /*     ERI */ "Eritrea",
        /*     MWI */ "Malawi",
        /*     PRK */ "Nordkorea",
        /*     NIC */ "Nicaragua",
        /*     GRC */ "Grækenland",
        /*     TJK */ "Tadsjikistan",
        /*     BGD */ "Bangladesh",
        /*     NPL */ "Nepal",
        /*     TUN */ "Tunesien",
        /*     SUR */ "Surinam",
        /*     URY */ "Uruguay",
        /*     KHM */ "Cambodia",
        /*     SYR */ "Syrien",
        /*     SEN */ "Senegal",
        /*     KGZ */ "Kirgisistan",
        /*     BLR */ "Belarus",
        /*     GUY */ "Guyana",
        /*     LAO */ "Laos",
        /*     ROU */ "Rumænien",
        /*     GHA */ "Ghana",
        /*     UGA */ "Uganda",
        /*     GBR */ "Storbritannien",
        /*     GIN */ "Guinea",
        /*     ECU */ "Ecuador",
        /*     ESH */ "Western Sahara|Sahrawi",
        /*     GAB */ "Gabon",
        /*     NZL */ "New Zealand",
        /*     BFA */ "Burkina Faso",
        /*     PHL */ "Filippinerne",
        /*     ITA */ "Italien",
        /*     OMN */ "Oman",
        /*     POL */ "Polen",
        /*     CIV */ "Elfenbenskysten",
        /*     NOR */ "Norge",
        /*     MYS */ "Malaysia",
        /*     VNM */ "Vietnam",
        /*     FIN */ "Finland",
        /*     COG */ "Congo-Brazzaville",
        /*     DEU */ "Tyskland",
        /*     JPN */ "Japan",
        /*     ZWE */ "Zimbabwe",
        /*     PRY */ "Paraguay",
        /*     IRQ */ "Iraq",
        /*     MAR */ "Marokko",
        /*     UZB */ "Usbekistan",
        /*     SWE */ "Sverige",
        /*     PNG */ "Papua Ny Guinea",
        /*     CMR */ "Cameroon",
        /*     TKM */ "Turkmenistan",
        /*     ESP */ "Spanien",
        /*     THA */ "Thailand",
        /*     YEM */ "Yemen",
        /*     FRA */ "France",
        /*     ALA */ "Ålandsøerne",
        /*     KEN */ "Kenya",
        /*     BWA */ "Botswana",
        /*     MDG */ "Madagascar",
        /*     UKR */ "Ukraine",
        /*     SSD */ "Sydsudan",
        /*     CAF */ "Centralafrikanske Republik",
        /*     SOM */ "Somalia",
        /*     AFG */ "Afghanistan",
        /*     MMR */ "Myanmar|Burma",
        /*     ZMB */ "Zambia",
        /*     CHL */ "Chile",
        /*     TUR */ "Tyrkiet",
        /*     PAK */ "Pakistan",
        /*     MOZ */ "Mozambique",
        /*     NAM */ "Namibia",
        /*     VEN */ "Venezuela",
        /*     NGA */ "Nigeria",
        /*     TZA */ "Tanzania",
        /*     EGY */ "Egypten",
        /*     MRT */ "Mauretanien",
        /*     BOL */ "Bolivia",
        /*     ETH */ "Etiopien",
        /*     COL */ "Colombia",
        /*     ZAF */ "Sydafrika",
        /*     MLI */ "Mali",
        /*     AGO */ "Angola",
        /*     NER */ "Niger",
        /*     TCD */ "Chad",
        /*     PER */ "Peru",
        /*     MNG */ "Mongoliet",
        /*     IRN */ "Iran",
        /*     LBY */ "Libyen",
        /*     SDN */ "Sudan",
        /*     IDN */ "Indonesien",
        /*     DIF */ "Federal District",
        /*     TLA */ "Tlaxcala",
        /*     MOR */ "Morelos",
        /*     AGU */ "Aguascalientes",
        /*   MX-CL */ "Colima",
        /*     QUE */ "Queretaro",
        /*     HID */ "Hidalgo",
        /*   MX-MX */ "Mexico State",
        /*     TAB */ "Tabasco",
        /*     NAY */ "Nayarit",
        /*     GUA */ "Guanajuato",
        /*     PUE */ "Puebla",
        /*     YUC */ "Yucatan",
        /*     ROO */ "Quintana Roo",
        /*     SIN */ "Sinaloa",
        /*     CAM */ "Campeche",
        /*     MIC */ "Michoacan",
        /*     SLP */ "San Luis Potosi",
        /*     GRO */ "Guerrero",
        /*     NLE */ "Nuevo Leon",
        /*     BCN */ "Baja California",
        /*     VER */ "Veracruz",
        /*     CHP */ "Chiapas",
        /*     BCS */ "Baja California Sur",
        /*     ZAC */ "Zacatecas",
        /*     JAL */ "Jalisco",
        /*     TAM */ "Tamaulipas",
        /*     OAX */ "Oaxaca",
        /*     DUR */ "Durango",
        /*     COA */ "Coahuila",
        /*     SON */ "Sonora",
        /*     CHH */ "Chihuahua",
        /*     GRL */ "Grønland",
        /*     SAU */ "Saudi Arabien",
        /*     COD */ "Congo-Kinshasa",
        /*     DZA */ "Algeriet",
        /*     KAZ */ "Kasakhstan",
        /*     ARG */ "Argentina",
        /*   IN-DD */ "Daman og Diu",
        /*   IN-DN */ "Dadra og Nagar Haveli",
        /*   IN-CH */ "Chandigarh",
        /*   IN-AN */ "Andaman og Nicobar",
        /*   IN-LD */ "Lakshadweep",
        /*   IN-DL */ "Delhi",
        /*   IN-ML */ "Meghalaya",
        /*   IN-NL */ "Nagaland",
        /*   IN-MN */ "Manipur",
        /*   IN-TR */ "Tripura",
        /*   IN-MZ */ "Mizoram",
        /*   IN-SK */ "Sikkim",
        /*   IN-PB */ "Punjab",
        /*   IN-HR */ "Haryana",
        /*   IN-AR */ "Arunachal Pradesh",
        /*   IN-AS */ "Assam",
        /*   IN-BR */ "Bihar",
        /*   IN-UT */ "Uttarakhand",
        /*   IN-GA */ "Goa",
        /*   IN-KL */ "Kerala",
        /*   IN-TN */ "Tamil Nadu",
        /*   IN-HP */ "Himachal Pradesh",
        /*   IN-JK */ "Jammu og Kashmir",
        /*   IN-CT */ "Chhattisgarh",
        /*   IN-JH */ "Jharkhand",
        /*   IN-KA */ "Karnataka",
        /*   IN-RJ */ "Rajasthan",
        /*   IN-OR */ "Odisha|Orissa",
        /*   IN-GJ */ "Gujarat",
        /*   IN-WB */ "Vestbengalen",
        /*   IN-MP */ "Madhya Pradesh",
        /*   IN-TG */ "Telangana",
        /*   IN-AP */ "Andhra Pradesh",
        /*   IN-MH */ "Maharashtra",
        /*   IN-UP */ "Uttar Pradesh",
        /*   IN-PY */ "Puducherry",
        /*     NSW */ "New South Wales",
        /*     ACT */ "Australian Capital Territory",
        /*     JBT */ "Jervis Bay Territory",
        /*   AU-NT */ "Northern Territory",
        /*   AU-SA */ "South Australia",
        /*     TAS */ "Tasmanien",
        /*     VIC */ "Victoria",
        /*   AU-WA */ "Western Australia",
        /*     QLD */ "Queensland",
        /*   BR-DF */ "Distrito Federal",
        /*   BR-SE */ "Sergipe",
        /*   BR-AL */ "Alagoas",
        /*   BR-RJ */ "Rio de Janeiro",
        /*   BR-ES */ "Espirito Santo",
        /*   BR-RN */ "Rio Grande do Norte",
        /*   BR-PB */ "Paraiba",
        /*   BR-SC */ "Santa Catarina",
        /*   BR-PE */ "Pernambuco",
        /*   BR-AP */ "Amapa",
        /*   BR-CE */ "Ceara",
        /*   BR-AC */ "Acre",
        /*   BR-PR */ "Parana",
        /*   BR-RR */ "Roraima",
        /*   BR-RO */ "Rondonia",
        /*   BR-SP */ "Sao Paulo",
        /*   BR-PI */ "Piaui",
        /*   BR-TO */ "Tocantins",
        /*   BR-RS */ "Rio Grande do Sul",
        /*   BR-MA */ "Maranhao",
        /*   BR-GO */ "Goias",
        /*   BR-MS */ "Mato Grosso do Sul",
        /*   BR-BA */ "Bahia",
        /*   BR-MG */ "Minas Gerais",
        /*   BR-MT */ "Mato Grosso",
        /*   BR-PA */ "Para",
        /*   BR-AM */ "Amazonas",
        /*   US-DC */ "District of Columbia",
        /*   US-RI */ "Rhode Island",
        /*   US-DE */ "Delaware",
        /*   US-CT */ "Connecticut",
        /*   US-NJ */ "New Jersey",
        /*   US-NH */ "New Hampshire",
        /*   US-VT */ "Vermont",
        /*   US-MA */ "Massachusetts",
        /*   US-HI */ "Hawaii",
        /*   US-MD */ "Maryland",
        /*   US-WV */ "West Virginia",
        /*   US-SC */ "South Carolina",
        /*   US-ME */ "Maine",
        /*   US-IN */ "Indiana",
        /*   US-KY */ "Kentucky",
        /*   US-TN */ "Tennessee",
        /*   US-VA */ "Virginia",
        /*   US-OH */ "Ohio",
        /*   US-PA */ "Pennsylvania",
        /*   US-MS */ "Mississippi",
        /*   US-LA */ "Louisiana",
        /*   US-AL */ "Alabama",
        /*   US-AR */ "Arkansas",
        /*   US-NC */ "North Carolina",
        /*   US-NY */ "New York",
        /*   US-IA */ "Iowa",
        /*   US-IL */ "Illinois",
        /*   US-GA */ "Georgia",
        /*   US-WI */ "Wisconsin",
        /*   US-FL */ "Florida",
        /*   US-MO */ "Missouri",
        /*   US-OK */ "Oklahoma",
        /*   US-ND */ "North Dakota",
        /*   US-WA */ "Washington",
        /*   US-SD */ "South Dakota",
        /*   US-NE */ "Nebraska",
        /*   US-KS */ "Kansas",
        /*   US-ID */ "Idaho",
        /*   US-UT */ "Utah",
        /*   US-MN */ "Minnesota",
        /*   US-MI */ "Michigan",
        /*   US-WY */ "Wyoming",
        /*   US-OR */ "Oregon",
        /*   US-CO */ "Colorado",
        /*   US-NV */ "Nevada",
        /*   US-AZ */ "Arizona",
        /*   US-NM */ "New Mexico",
        /*   US-MT */ "Montana",
        /*   US-CA */ "California",
        /*   US-TX */ "Texas",
        /*   US-AK */ "Alaska",
        /*   CA-BC */ "British Columbia",
        /*   CA-AB */ "Alberta",
        /*   CA-ON */ "Ontario",
        /*   CA-QC */ "Quebec",
        /*   CA-SK */ "Saskatchewan",
        /*   CA-MB */ "Manitoba",
        /*   CA-NL */ "Newfoundland",
        /*   CA-NB */ "New Brunswick",
        /*   CA-NS */ "Nova Scotia",
        /*   CA-PE */ "Prince Edward Island",
        /*   CA-YT */ "Yukon",
        /*   CA-NT */ "Northwest Territories",
        /*   CA-NU */ "Nunavut",
        /*     IND */ "Indien",
        /*     AUS */ "Australien",
        /*     BRA */ "Brasilien",
        /*     USA */ "USA|USA|Amerika",
        /*     MEX */ "Mexico",
        /*     MOW */ "Moskva",
        /*     SPE */ "Sankt Petersborg",
        /*     KGD */ "Kaliningrad Oblast",
        /*   RU-IN */ "Ingusjetien Republik",
        /*   RU-AD */ "Adygea Republik",
        /*   RU-SE */ "Nordossetien-Alania Republik",
        /*   RU-KB */ "Kabardino-Balkar Republic",
        /*   RU-KC */ "Karachay-Cherkess Republic",
        /*   RU-CE */ "Tjetjenske republik",
        /*   RU-CU */ "Chuvash Republic",
        /*     IVA */ "Ivanovo Oblast",
        /*     LIP */ "Lipetsk Oblast",
        /*     ORL */ "Oryol Oblast",
        /*     TUL */ "Tula Oblast",
        /*   RU-BE */ "Belgorod Oblast",
        /*     VLA */ "Vladimir Oblast",
        /*     KRS */ "Kursk Oblast",
        /*     KLU */ "Kaluga Oblast",
        /*   RU-TT */ "Tambov Oblast",
        /*     BRY */ "Bryansk Oblast",
        /*     YAR */ "Yaroslavl Oblast",
        /*     RYA */ "Ryazan Oblast",
        /*     AST */ "Astrakhan Oblast",
        /*     MOS */ "Moskva Oblast",
        /*     SMO */ "Smolensk Oblast",
        /*   RU-DA */ "Dagestan Republik",
        /*     VOR */ "Voronezh Oblast",
        /*     NGR */ "Novgorod Oblast",
        /*     PSK */ "Pskov Oblast",
        /*     KOS */ "Kostroma Oblast",
        /*     STA */ "Stavropol Krai",
        /*     KDA */ "Krasnodar Krai",
        /*   RU-KL */ "Kalmykia Republik",
        /*     TVE */ "Tver Oblast",
        /*     LEN */ "Leningrad Oblast",
        /*     ROS */ "Rostov Oblast",
        /*     VGG */ "Volgograd Oblast",
        /*     VLG */ "Vologda Oblast",
        /*     MUR */ "Murmansk Oblast",
        /*   RU-KR */ "Karelia Republik",
        /*     NEN */ "Nenets Autonome Okrug",
        /*   RU-KO */ "Komi Republic",
        /*     ARK */ "Arkhangelsk Oblast",
        /*   RU-MO */ "Mordovien Republik",
        /*     NIZ */ "Nizhny Novgorod Oblast",
        /*     PNZ */ "Penza Oblast",
        /*   RU-KI */ "Kirov Oblast",
        /*   RU-ME */ "Mari El Republik",
        /*     ORE */ "Orenburg Oblast",
        /*     ULY */ "Ulyanovsk Oblast",
        /*   RU-PM */ "Perm Krai",
        /*   RU-BA */ "Bashkortostan Republik",
        /*   RU-UD */ "Udmurt Republic",
        /*   RU-TA */ "Tatarstan Republik",
        /*     SAM */ "Samara Oblast",
        /*     SAR */ "Saratov Oblast",
        /*     YAN */ "Yamalo-Nenets",
        /*   RU-KM */ "Khanty-Mansi",
        /*     SVE */ "Sverdlovsk Oblast",
        /*     TYU */ "Tyumen Oblast",
        /*     KGN */ "Kurgan Oblast",
        /*   RU-CH */ "Chelyabinsk Oblast",
        /*   RU-BU */ "Buryatia Republik",
        /*     ZAB */ "Zabaykalsky Krai",
        /*     IRK */ "Irkutsk Oblast",
        /*     NVS */ "Novosibirsk Oblast",
        /*     TOM */ "Tomsk Oblast",
        /*     OMS */ "Omsk Oblast",
        /*   RU-KK */ "Khakassia Republik",
        /*     KEM */ "Kemerovo Oblast",
        /*   RU-AL */ "Altai Republik",
        /*     ALT */ "Altai Krai",
        /*   RU-TY */ "Tuva Republik",
        /*     KYA */ "Krasnoyarsk Krai",
        /*     MAG */ "Magadan Oblast",
        /*     CHU */ "Tjukotka Okrug",
        /*     KAM */ "Kamchatka Krai",
        /*     SAK */ "Sakhalin Oblast",
        /*   RU-PO */ "Primorsky Krai",
        /*     YEV */ "Jødisk selvstyrende Oblast",
        /*     KHA */ "Khabarovsk Krai",
        /*     AMU */ "Amur Oblast",
        /*   RU-SA */ "Sakha Republik|Yakutia Republic",
        /*     CAN */ "Canada",
        /*     RUS */ "Rusland",
        /*   CN-SH */ "Shanghai",
        /*   CN-TJ */ "Tianjin",
        /*   CN-BJ */ "Beijing",
        /*   CN-HI */ "Hainan",
        /*   CN-NX */ "Ningxia Hui",
        /*   CN-CQ */ "Chongqing",
        /*   CN-ZJ */ "Zhejiang",
        /*   CN-JS */ "Jiangsu",
        /*   CN-FJ */ "Fujian",
        /*   CN-AH */ "Anhui",
        /*   CN-LN */ "Liaoning",
        /*   CN-SD */ "Shandong",
        /*   CN-SX */ "Shanxi",
        /*   CN-JX */ "Jiangxi",
        /*   CN-HA */ "Henan",
        /*   CN-GZ */ "Guizhou",
        /*   CN-GD */ "Guangdong",
        /*   CN-HB */ "Hubei",
        /*   CN-JL */ "Jilin",
        /*   CN-HE */ "Hebei",
        /*   CN-SN */ "Shaanxi",
        /*   CN-NM */ "Nei Mongol|Inner Mongolia",
        /*   CN-HL */ "Heilongjiang",
        /*   CN-HN */ "Hunan",
        /*   CN-GX */ "Guangxi",
        /*   CN-SC */ "Sichuan",
        /*   CN-YN */ "Yunnan",
        /*   CN-XZ */ "Xizang|Tibet",
        /*   CN-GS */ "Gansu",
        /*   CN-QH */ "Qinghai",
        /*   CN-XJ */ "Xinjiang Uyghur",
        /*     CHN */ "Kina",
        /*     UMI */ "United States Minor Outlying Islands",
        /*     CPT */ "Clipperton Island",
        /*     ATA */ "Antarctica",
        /*     AAA */ "International|Verdenen|Jord"
#else // MAPCODE_SUPPORT_LANGUAGE_DA
        NULL
#endif // MAPCODE_SUPPORT_LANGUAGE_DA
};

#ifdef __cplusplus
}
#endif

#endif // __INTERNAL_TERRITORY_NAMES_DA_H__
