/*
 * Copyright (C) 2014-2017 Stichting Mapcode Foundation (http://www.mapcode.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef __INTERNAL_TERRITORY_NAMES_FI_H__
#define __INTERNAL_TERRITORY_NAMES_FI_H__

#ifdef __cplusplus
extern "C" {
#endif

// *** GENERATED FILE (coords.cpp), DO NOT CHANGE OR PRETTIFY ***

static const char *TERRITORY_FULL_NAME_FI[] = {
#ifdef MAPCODE_SUPPORT_LANGUAGE_FI // Finnish
        /*     VAT */ "Vatikaani|Pyhä istuin",
        /*     MCO */ "Monaco",
        /*     GIB */ "Gibraltar",
        /*     TKL */ "Tokelau",
        /*     CCK */ "Kookossaaret|Keeling Islands",
        /*     BLM */ "Saint-Barthelemy",
        /*     NRU */ "Nauru",
        /*     TUV */ "Tuvalu",
        /*     MAC */ "Macao",
        /*     SXM */ "Sint Maarten",
        /*     MAF */ "Saint-Martin",
        /*     NFK */ "Norfolk ja Philip Island|Philip Island",
        /*     PCN */ "Pitcairnsaaret",
        /*     BVT */ "Bouvet`nsaari",
        /*     BMU */ "Bermuda",
        /*     IOT */ "Brittiläinen Intian valtameren alue",
        /*     SMR */ "San Marino",
        /*     GGY */ "Guernsey",
        /*     AIA */ "Anguilla",
        /*     MSR */ "Montserrat",
        /*     JEY */ "Jersey",
        /*     CXR */ "Joulusaari",
        /*     WLF */ "Wallis ja Futuna|Futuna",
        /*     VGB */ "Brittiläiset Neitsytsaaret|Brittiläiset Neitsytsaaret",
        /*     LIE */ "Liechtenstein",
        /*     ABW */ "Aruba",
        /*     MHL */ "Marshallinsaaret",
        /*     ASM */ "Amerikan Samoa|Samoa, amerikkalainen",
        /*     COK */ "Cook saaret",
        /*     SPM */ "Saint-Pierre ja Miquelon|Miquelon",
        /*     NIU */ "Niue",
        /*     KNA */ "Saint Kitts ja Nevis|Nevis",
        /*     CYM */ "Caymansaaret",
        /*     BES */ "Bonaire, St Eustatuis ja Saba|Saba|St Eustatius",
        /*     MDV */ "Malediivit",
        /*     SHN */ "Saint Helena, Ascension ja Tristan da Cunha|Ascension|Tristan da Cunha",
        /*     MLT */ "Malta",
        /*     GRD */ "Grenada",
        /*     VIR */ "Yhdysvaltain Neitsytsaaret",
        /*     MYT */ "Mayotte",
        /*     SJM */ "Huippuvuoret ja Jan Mayen|Jan Mayen",
        /*     VCT */ "Saint Vincent ja Grenadiinit|Grenadiinit",
        /*     HMD */ "Heard ja McDonald Islands|McDonald-saaret",
        /*     BRB */ "Barbados",
        /*     ATG */ "Antigua ja Barbuda|Barbuda",
        /*     CUW */ "Curacao",
        /*     SYC */ "Seychellit",
        /*     PLW */ "Palau",
        /*     MNP */ "Pohjois-Mariaanit",
        /*     AND */ "Andorra",
        /*     GUM */ "Guam",
        /*     IMN */ "Mansaari",
        /*     LCA */ "Saint Lucia",
        /*     FSM */ "Mikronesia",
        /*     SGP */ "Singapore",
        /*     TON */ "Tonga",
        /*     DMA */ "Dominica",
        /*     BHR */ "Bahrain",
        /*     KIR */ "Kiribati",
        /*     TCA */ "Turks- ja Caicossaaret|Caicossaaret",
        /*     STP */ "Sao Tome ja Principe|Principe",
        /*     HKG */ "Hongkong",
        /*     MTQ */ "Martinique",
        /*     FRO */ "Färsaaret",
        /*     GLP */ "Guadeloupe",
        /*     COM */ "Komorit",
        /*     MUS */ "Mauritius",
        /*     REU */ "Jälleennäkeminen",
        /*     LUX */ "Luxemburg",
        /*     WSM */ "Samoa",
        /*     SGS */ "Etelä-Georgia ja Eteläiset Sandwichsaaret|Sandwichsaaret",
        /*     PYF */ "Ranskan Polynesia",
        /*     CPV */ "Kap Verde",
        /*     TTO */ "Trinidad ja Tobago|Tobago",
        /*     BRN */ "Brunei",
        /*     ATF */ "Ranskan eteläiset alueet",
        /*     PRI */ "Puerto Rico",
        /*     CYP */ "Kypros",
        /*     LBN */ "Libanon",
        /*     JAM */ "Jamaika",
        /*     GMB */ "Gambia",
        /*     QAT */ "Qatar",
        /*     FLK */ "Falklandinsaaret",
        /*     VUT */ "Vanuatu",
        /*     MNE */ "Montenegro",
        /*     BHS */ "Bahama",
        /*     TLS */ "Itä-Timor",
        /*     SWZ */ "Swazimaa",
        /*     KWT */ "Kuwait",
        /*     FJI */ "Fiji",
        /*     NCL */ "Uusi-Caledonia",
        /*     SVN */ "Slovenia",
        /*     ISR */ "Israel",
        /*     PSE */ "Palestiinalaisalueet",
        /*     SLV */ "El Salvador",
        /*     BLZ */ "Belize",
        /*     DJI */ "Djibouti",
        /*     MKD */ "Makedonia",
        /*     RWA */ "Ruanda",
        /*     HTI */ "Haiti",
        /*     BDI */ "Burundi",
        /*     GNQ */ "Päiväntasaajan Guinea",
        /*     ALB */ "Albania",
        /*     SLB */ "Salomonsaaret",
        /*     ARM */ "Armenia",
        /*     LSO */ "Lesotho",
        /*     BEL */ "Belgia",
        /*     MDA */ "Moldova",
        /*     GNB */ "Guinea-Bissau",
        /*     TWN */ "Taiwan",
        /*     BTN */ "Bhutan",
        /*     CHE */ "Sveitsi",
        /*     NLD */ "Hollanti|Alankomaat",
        /*     DNK */ "Tanska",
        /*     EST */ "Viro",
        /*     DOM */ "Dominikaaninen tasavalta",
        /*     SVK */ "Slovakia",
        /*     CRI */ "Costa Rica",
        /*     BIH */ "Bosnia ja Hertsegovina",
        /*     HRV */ "Kroatia",
        /*     TGO */ "Togo",
        /*     LVA */ "Latvia",
        /*     LTU */ "Liettua",
        /*     LKA */ "Sri Lanka",
        /*     GEO */ "Georgia",
        /*     IRL */ "Irlanti",
        /*     SLE */ "Sierra Leone",
        /*     PAN */ "Panama",
        /*     CZE */ "Tšekin tasavalta",
        /*     GUF */ "Ranskan Guayana",
        /*     ARE */ "Yhdistyneet Arabiemiirikunnat",
        /*     AUT */ "Itävalta",
        /*     AZE */ "Azerbaidžan",
        /*     SRB */ "Serbia",
        /*     JOR */ "Jordania",
        /*     PRT */ "Portugali",
        /*     HUN */ "Unkari",
        /*     KOR */ "Etelä-Korea",
        /*     ISL */ "Islanti",
        /*     GTM */ "Guatemala",
        /*     CUB */ "Kuuba",
        /*     BGR */ "Bulgaria",
        /*     LBR */ "Liberia",
        /*     HND */ "Honduras",
        /*     BEN */ "Benin",
        /*     ERI */ "Eritrea",
        /*     MWI */ "Malawi",
        /*     PRK */ "Pohjois-Korea",
        /*     NIC */ "Nicaragua",
        /*     GRC */ "Kreikka",
        /*     TJK */ "Tadžikistan",
        /*     BGD */ "Bangladesh",
        /*     NPL */ "Nepal",
        /*     TUN */ "Tunisia",
        /*     SUR */ "Suriname",
        /*     URY */ "Uruguay",
        /*     KHM */ "Kambodza",
        /*     SYR */ "Syyria",
        /*     SEN */ "Senegal",
        /*     KGZ */ "Kirgisia",
        /*     BLR */ "Valko-Venäjä",
        /*     GUY */ "Guyana",
        /*     LAO */ "Laos",
        /*     ROU */ "Romania",
        /*     GHA */ "Ghana",
        /*     UGA */ "Uganda",
        /*     GBR */ "Iso-Britannia|Skotlanti|Pohjois-Irlanti|Irlanti, Pohjois",
        /*     GIN */ "Guinea",
        /*     ECU */ "Ecuador",
        /*     ESH */ "Länsi-Sahara|Länsi-Saharan",
        /*     GAB */ "Gabon",
        /*     NZL */ "Uusi Seelanti",
        /*     BFA */ "Burkina Faso",
        /*     PHL */ "Filippiinit",
        /*     ITA */ "Italia",
        /*     OMN */ "Oman",
        /*     POL */ "Puola",
        /*     CIV */ "Norsunluurannikko",
        /*     NOR */ "Norja",
        /*     MYS */ "Malesia",
        /*     VNM */ "Vietnam",
        /*     FIN */ "Suomi",
        /*     COG */ "Kongon",
        /*     DEU */ "Saksa",
        /*     JPN */ "Japani",
        /*     ZWE */ "Zimbabwe",
        /*     PRY */ "Paraguay",
        /*     IRQ */ "Irak",
        /*     MAR */ "Marokko",
        /*     UZB */ "Uzbekistan",
        /*     SWE */ "Ruotsi",
        /*     PNG */ "Papua-Uusi-Guinea",
        /*     CMR */ "Kamerun",
        /*     TKM */ "Turkmenistan",
        /*     ESP */ "Espanja",
        /*     THA */ "Thaimaa",
        /*     YEM */ "Jemen",
        /*     FRA */ "Ranska",
        /*     ALA */ "Ahvenanmaa",
        /*     KEN */ "Kenia",
        /*     BWA */ "Botswana",
        /*     MDG */ "Madagaskar",
        /*     UKR */ "Ukraina",
        /*     SSD */ "Etelä-Sudan",
        /*     CAF */ "Keski-Afrikan tasavalta",
        /*     SOM */ "Somalia",
        /*     AFG */ "Afganistan",
        /*     MMR */ "Myanmar|Burma",
        /*     ZMB */ "Sambia",
        /*     CHL */ "Chile",
        /*     TUR */ "Turkki",
        /*     PAK */ "Pakistan",
        /*     MOZ */ "Mosambik",
        /*     NAM */ "Namibia",
        /*     VEN */ "Venezuela",
        /*     NGA */ "Nigeria",
        /*     TZA */ "Tansania",
        /*     EGY */ "Egypti",
        /*     MRT */ "Mauritania",
        /*     BOL */ "Bolivia",
        /*     ETH */ "Etiopia",
        /*     COL */ "Kolumbia",
        /*     ZAF */ "Etelä-Afrikka",
        /*     MLI */ "Mali",
        /*     AGO */ "Angola",
        /*     NER */ "Niger",
        /*     TCD */ "Chad",
        /*     PER */ "Peru",
        /*     MNG */ "Mongolia",
        /*     IRN */ "Iran",
        /*     LBY */ "Libya",
        /*     SDN */ "Sudan",
        /*     IDN */ "Indonesia",
        /*     DIF */ "Federal District",
        /*     TLA */ "Tlaxcala",
        /*     MOR */ "Morelos",
        /*     AGU */ "Aguascalientes",
        /*   MX-CL */ "Colima",
        /*     QUE */ "Queretaro",
        /*     HID */ "Hidalgo",
        /*   MX-MX */ "Mexico State",
        /*     TAB */ "Tabasco",
        /*     NAY */ "Nayarit",
        /*     GUA */ "Guanajuato",
        /*     PUE */ "Puebla",
        /*     YUC */ "Yucatan",
        /*     ROO */ "Quintana Roo",
        /*     SIN */ "Sinaloa",
        /*     CAM */ "Campeche",
        /*     MIC */ "Michoacan",
        /*     SLP */ "San Luis Potosi",
        /*     GRO */ "Guerrero",
        /*     NLE */ "Nuevo Leon",
        /*     BCN */ "Baja California",
        /*     VER */ "Veracruz",
        /*     CHP */ "Chiapas",
        /*     BCS */ "Baja California Sur",
        /*     ZAC */ "Zacatecas",
        /*     JAL */ "Jalisco",
        /*     TAM */ "Tamaulipas",
        /*     OAX */ "Oaxaca",
        /*     DUR */ "Durango",
        /*     COA */ "Coahuila",
        /*     SON */ "Sonora",
        /*     CHH */ "Chihuahua",
        /*     GRL */ "Grönlanti",
        /*     SAU */ "Saudi-Arabia",
        /*     COD */ "Kongo-Kinshasa",
        /*     DZA */ "Algeria",
        /*     KAZ */ "Kazakstan",
        /*     ARG */ "Argentiina",
        /*   IN-DD */ "Daman ja Diu",
        /*   IN-DN */ "Dadra ja Nagar Haveli",
        /*   IN-CH */ "Chandigarh",
        /*   IN-AN */ "Andaman ja Nicobar",
        /*   IN-LD */ "Lakshadweep",
        /*   IN-DL */ "Delhi",
        /*   IN-ML */ "Meghalaya",
        /*   IN-NL */ "Nagaland",
        /*   IN-MN */ "Manipur",
        /*   IN-TR */ "Tripura",
        /*   IN-MZ */ "Mizoram",
        /*   IN-SK */ "Sikkim",
        /*   IN-PB */ "Punjab",
        /*   IN-HR */ "Haryana",
        /*   IN-AR */ "Arunachal Pradesh",
        /*   IN-AS */ "Assam",
        /*   IN-BR */ "Bihar",
        /*   IN-UT */ "Uttarakhand",
        /*   IN-GA */ "Goa",
        /*   IN-KL */ "Kerala",
        /*   IN-TN */ "Tamil Nadun",
        /*   IN-HP */ "Himachal Pradesh",
        /*   IN-JK */ "Jammun ja Kashmirin",
        /*   IN-CT */ "Chhattisgarh",
        /*   IN-JH */ "Jharkhand",
        /*   IN-KA */ "Karnataka",
        /*   IN-RJ */ "Rajasthan",
        /*   IN-OR */ "Odisha|Orissa",
        /*   IN-GJ */ "Gujaratin",
        /*   IN-WB */ "Länsi-Bengal",
        /*   IN-MP */ "Madhya Pradesh",
        /*   IN-TG */ "Telangana",
        /*   IN-AP */ "Andhra Pradesh",
        /*   IN-MH */ "Maharashtra",
        /*   IN-UP */ "Uttar Pradesh",
        /*   IN-PY */ "Puducherry",
        /*     NSW */ "New South Wales",
        /*     ACT */ "Australian pääkaupunkiterritorio|Australian Capital Territory",
        /*     JBT */ "Jervis Bay Territory",
        /*   AU-NT */ "Northern Territory",
        /*   AU-SA */ "South Australia",
        /*     TAS */ "Tasmania",
        /*     VIC */ "Victoria",
        /*   AU-WA */ "Western Australia",
        /*     QLD */ "Queensland",
        /*   BR-DF */ "Distrito Federal",
        /*   BR-SE */ "Sergipe",
        /*   BR-AL */ "Alagoas",
        /*   BR-RJ */ "Rio de Janeiro",
        /*   BR-ES */ "Espirito Santo",
        /*   BR-RN */ "Rio Grande do Norte",
        /*   BR-PB */ "Paraiba",
        /*   BR-SC */ "Santa Catarina",
        /*   BR-PE */ "Pernambuco",
        /*   BR-AP */ "Amapa",
        /*   BR-CE */ "Ceara",
        /*   BR-AC */ "Acre",
        /*   BR-PR */ "Parana",
        /*   BR-RR */ "Roraima",
        /*   BR-RO */ "Rondonia",
        /*   BR-SP */ "Sao Paulo",
        /*   BR-PI */ "Piaui",
        /*   BR-TO */ "Tocantins",
        /*   BR-RS */ "Rio Grande do Sul",
        /*   BR-MA */ "Maranhao",
        /*   BR-GO */ "Goias",
        /*   BR-MS */ "Mato Grosso do Sul",
        /*   BR-BA */ "Bahia",
        /*   BR-MG */ "Minas Gerais",
        /*   BR-MT */ "Mato Grosso",
        /*   BR-PA */ "Para",
        /*   BR-AM */ "Amazonas",
        /*   US-DC */ "District of Columbia",
        /*   US-RI */ "Rhode Island",
        /*   US-DE */ "Delaware",
        /*   US-CT */ "Connecticut",
        /*   US-NJ */ "New Jersey",
        /*   US-NH */ "New Hampshire",
        /*   US-VT */ "Vermont",
        /*   US-MA */ "Massachusetts",
        /*   US-HI */ "Havaiji",
        /*   US-MD */ "Maryland",
        /*   US-WV */ "Länsi-Virginia",
        /*   US-SC */ "Etelä-Carolina",
        /*   US-ME */ "Maine",
        /*   US-IN */ "Indiana",
        /*   US-KY */ "Kentucky",
        /*   US-TN */ "Tennessee",
        /*   US-VA */ "Virginia",
        /*   US-OH */ "Ohio",
        /*   US-PA */ "Pennsylvania",
        /*   US-MS */ "Mississippi",
        /*   US-LA */ "Louisiana",
        /*   US-AL */ "Alabama",
        /*   US-AR */ "Arkansas",
        /*   US-NC */ "Pohjois-Carolina",
        /*   US-NY */ "New York",
        /*   US-IA */ "Iowa",
        /*   US-IL */ "Illinois",
        /*   US-GA */ "Georgia",
        /*   US-WI */ "Wisconsin",
        /*   US-FL */ "Florida",
        /*   US-MO */ "Missouri",
        /*   US-OK */ "Oklahoma",
        /*   US-ND */ "North Dakota",
        /*   US-WA */ "Washington",
        /*   US-SD */ "South Dakota|Etelä-Dakota",
        /*   US-NE */ "Nebraska",
        /*   US-KS */ "Kansas",
        /*   US-ID */ "Idaho",
        /*   US-UT */ "Utah",
        /*   US-MN */ "Minnesota",
        /*   US-MI */ "Michigan",
        /*   US-WY */ "Wyoming",
        /*   US-OR */ "Oregon",
        /*   US-CO */ "Colorado",
        /*   US-NV */ "Nevada",
        /*   US-AZ */ "Arizona",
        /*   US-NM */ "Uusi Meksiko|New Mexico",
        /*   US-MT */ "Montana",
        /*   US-CA */ "Kalifornia",
        /*   US-TX */ "Texas",
        /*   US-AK */ "Alaska",
        /*   CA-BC */ "Brittiläinen Kolumbia",
        /*   CA-AB */ "Alberta",
        /*   CA-ON */ "Ontario",
        /*   CA-QC */ "Quebec",
        /*   CA-SK */ "Saskatchewan",
        /*   CA-MB */ "Manitoba",
        /*   CA-NL */ "Newfoundland",
        /*   CA-NB */ "New Brunswick",
        /*   CA-NS */ "Nova Scotia",
        /*   CA-PE */ "Prince Edward Island",
        /*   CA-YT */ "Yukon",
        /*   CA-NT */ "Luoteisterritoriot",
        /*   CA-NU */ "Nunavut",
        /*     IND */ "Intia",
        /*     AUS */ "Australia",
        /*     BRA */ "Brasilia",
        /*     USA */ "USA|Yhdysvallat|Amerikka",
        /*     MEX */ "Meksiko",
        /*     MOW */ "Moskova",
        /*     SPE */ "Pietari",
        /*     KGD */ "Kaliningradin alue",
        /*   RU-IN */ "Ingušian tasavalta",
        /*   RU-AD */ "Adygeia tasavalta",
        /*   RU-SE */ "Pohjois-Ossetia-Alania tasavalta",
        /*   RU-KB */ "Kabardi-Balkarian tasavalta",
        /*   RU-KC */ "Karatšai-Tšerkessit tasavalta",
        /*   RU-CE */ "Tšetšenian tasavallassa",
        /*   RU-CU */ "Tšuvassi tasavalta",
        /*     IVA */ "Ivanovon alue",
        /*     LIP */ "Lipetskin alue",
        /*     ORL */ "Orjolin alue",
        /*     TUL */ "Tulan alue",
        /*   RU-BE */ "Belgorodin alue",
        /*     VLA */ "Vladimirin alue",
        /*     KRS */ "Kurskin alue",
        /*     KLU */ "Kalugan alue",
        /*   RU-TT */ "Tambovin alue",
        /*     BRY */ "Brjanskin alue",
        /*     YAR */ "Jaroslavlin alue",
        /*     RYA */ "Rjazanin alue",
        /*     AST */ "Astrahanin alue",
        /*     MOS */ "Moskovan",
        /*     SMO */ "Smolenskin alue",
        /*   RU-DA */ "Dagestanin tasavalta",
        /*     VOR */ "Voronežin alue",
        /*     NGR */ "Novgorodin alue",
        /*     PSK */ "Pihkovan alue",
        /*     KOS */ "Kostromossa",
        /*     STA */ "Stavropolin aluepiiri",
        /*     KDA */ "Krasnodarin",
        /*   RU-KL */ "Kalmykia tasavalta",
        /*     TVE */ "Tverin alue",
        /*     LEN */ "Leningradin",
        /*     ROS */ "Rostovin alue",
        /*     VGG */ "Volgogradin alue",
        /*     VLG */ "Vologdan alue",
        /*     MUR */ "Murmanskin alue",
        /*   RU-KR */ "Karjalan tasavalta",
        /*     NEN */ "Nenetsiassa",
        /*   RU-KO */ "Komin",
        /*     ARK */ "Arkangelin",
        /*   RU-MO */ "Mordvan tasavalta",
        /*     NIZ */ "Nižni Novgorodin alue",
        /*     PNZ */ "Penzan alue",
        /*   RU-KI */ "Kirovin alue",
        /*   RU-ME */ "Marin tasavallan",
        /*     ORE */ "Orenburgin alue",
        /*     ULY */ "Uljanovskin alue",
        /*   RU-PM */ "Perm Krai",
        /*   RU-BA */ "Bashkortostanin tasavalta",
        /*   RU-UD */ "Udmurtian",
        /*   RU-TA */ "Tatarstanin tasavalta",
        /*     SAM */ "Samaran alue",
        /*     SAR */ "Saratovin alue",
        /*     YAN */ "Jamalin Nenetsian",
        /*   RU-KM */ "Hanti-Mansi",
        /*     SVE */ "Sverdlovskin alue",
        /*     TYU */ "Tjumenin alue",
        /*     KGN */ "Kurganin alue",
        /*   RU-CH */ "Tšeljabinskin alue",
        /*   RU-BU */ "Burjatian tasavalta",
        /*     ZAB */ "Taka-Baikalian aluepiiri",
        /*     IRK */ "Irkutskin alue",
        /*     NVS */ "Novosibirskin alue",
        /*     TOM */ "Tomskin alue",
        /*     OMS */ "Omskin alue",
        /*   RU-KK */ "Hakassian tasavalta",
        /*     KEM */ "Kemerovon alue",
        /*   RU-AL */ "Altai Republic",
        /*     ALT */ "Altain aluepiiri",
        /*   RU-TY */ "Tuvan tasavalta",
        /*     KYA */ "Krasnojarskin aluepiiri",
        /*     MAG */ "Magadanin alue",
        /*     CHU */ "Chukotkan Okrugin",
        /*     KAM */ "Kamtšatkan aluepiiri",
        /*     SAK */ "Sahalinin alue",
        /*   RU-PO */ "Primorsky aluepiiri",
        /*     YEV */ "Juutalaisten autonominen alue",
        /*     KHA */ "Habarovskin aluepiiri",
        /*     AMU */ "Amurin alue",
        /*   RU-SA */ "Sahan Tasavallassa|Yakutia Tasavalta",
        /*     CAN */ "Kanada",
        /*     RUS */ "Venäjä",
        /*   CN-SH */ "Shanghai",
        /*   CN-TJ */ "Tianjin",
        /*   CN-BJ */ "Peking",
        /*   CN-HI */ "Hainan",
        /*   CN-NX */ "Ningxia Hui",
        /*   CN-CQ */ "Chongqing",
        /*   CN-ZJ */ "Zhejiang",
        /*   CN-JS */ "Jiangsu",
        /*   CN-FJ */ "Fujian",
        /*   CN-AH */ "Anhui",
        /*   CN-LN */ "Liaoningin",
        /*   CN-SD */ "Shandong",
        /*   CN-SX */ "Shanxi",
        /*   CN-JX */ "Jiangxi",
        /*   CN-HA */ "Henan",
        /*   CN-GZ */ "Guizhoun",
        /*   CN-GD */ "Guangdong",
        /*   CN-HB */ "Hubein",
        /*   CN-JL */ "Jilin",
        /*   CN-HE */ "Hebei",
        /*   CN-SN */ "Shaanxin",
        /*   CN-NM */ "Nei Mongol|Inner Mongolia",
        /*   CN-HL */ "Heilongjiangin",
        /*   CN-HN */ "Hunan",
        /*   CN-GX */ "Guangxi Zhuang",
        /*   CN-SC */ "Sichuan",
        /*   CN-YN */ "Yunnan",
        /*   CN-XZ */ "Xizang|Tiibet",
        /*   CN-GS */ "Gansun",
        /*   CN-QH */ "Qinghai",
        /*   CN-XJ */ "Xinjiangin uiguurien",
        /*     CHN */ "Kiina",
        /*     UMI */ "Yhdysvaltain Tyynenmeren erillissaaret",
        /*     CPT */ "Clippertoninsaari",
        /*     ATA */ "Antarktis",
        /*     AAA */ "Kansainvälinen|Maailma|Maapallo"
#else // MAPCODE_SUPPORT_LANGUAGE_FI
        NULL
#endif // MAPCODE_SUPPORT_LANGUAGE_FI
};

#ifdef __cplusplus
}
#endif

#endif // __INTERNAL_TERRITORY_NAMES_FI_H__
