/*
 * Copyright (C) 2014-2017 Stichting Mapcode Foundation (http://www.mapcode.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef __INTERNAL_TERRITORY_NAMES_ID_H__
#define __INTERNAL_TERRITORY_NAMES_ID_H__

#ifdef __cplusplus
extern "C" {
#endif

// *** GENERATED FILE (coords.cpp), DO NOT CHANGE OR PRETTIFY ***

static const char *TERRITORY_FULL_NAME_ID[] = {
#ifdef MAPCODE_SUPPORT_LANGUAGE_ID // Indonesian
        /*     VAT */ "Vatican City|Holy See",
        /*     MCO */ "Monako",
        /*     GIB */ "Gibraltar",
        /*     TKL */ "Tokelau",
        /*     CCK */ "Kepulauan Cocos|Keeling Islands",
        /*     BLM */ "Saint-Barthelemy",
        /*     NRU */ "Nauru",
        /*     TUV */ "Tuvalu",
        /*     MAC */ "Macau",
        /*     SXM */ "Sint Maarten",
        /*     MAF */ "Saint-Martin",
        /*     NFK */ "Norfolk dan Philip Island|Philip Island",
        /*     PCN */ "Kepulauan Pitcairn",
        /*     BVT */ "Bouvet Pulau",
        /*     BMU */ "Bermuda",
        /*     IOT */ "Britania di Samudra Hindia",
        /*     SMR */ "San Marino",
        /*     GGY */ "Guernsey",
        /*     AIA */ "Anguilla",
        /*     MSR */ "Montserrat",
        /*     JEY */ "Jersey",
        /*     CXR */ "Christmas Island",
        /*     WLF */ "Wallis dan Futuna|Futuna",
        /*     VGB */ "British Virgin Islands|Kepulauan Virgin, Inggris",
        /*     LIE */ "Liechtenstein",
        /*     ABW */ "Aruba",
        /*     MHL */ "Pulau Marshall",
        /*     ASM */ "Samoa Amerika|Samoa, Amerika",
        /*     COK */ "Kepulauan cook",
        /*     SPM */ "Saint Pierre dan Miquelon|Miquelon",
        /*     NIU */ "Niue",
        /*     KNA */ "Saint Kitts dan Nevis|Nevis",
        /*     CYM */ "Pulau Cayman",
        /*     BES */ "Bonaire, St Eustatuis dan Saba|Saba|St Eustatius",
        /*     MDV */ "Maladewa",
        /*     SHN */ "Saint Helena, Ascension dan Tristan da Cunha|Ascension|Tristan da Cunha",
        /*     MLT */ "Malta",
        /*     GRD */ "Grenada",
        /*     VIR */ "US Virgin Islands|Kepulauan Virgin, AS",
        /*     MYT */ "Mayotte",
        /*     SJM */ "Svalbard dan Jan Mayen|Jan Mayen",
        /*     VCT */ "Saint Vincent dan Grenadines|Grenadines",
        /*     HMD */ "Pulau Heard dan Kepulauan McDonald|McDonald Islands",
        /*     BRB */ "Barbados",
        /*     ATG */ "Antigua dan Barbuda|Barbuda",
        /*     CUW */ "Curacao",
        /*     SYC */ "Seychelles",
        /*     PLW */ "Palau",
        /*     MNP */ "Kepulauan Mariana Utara",
        /*     AND */ "Andorra",
        /*     GUM */ "Guam",
        /*     IMN */ "Pulau manusia",
        /*     LCA */ "Saint Lucia",
        /*     FSM */ "Mikronesia|Negara Federasi Mikronesia",
        /*     SGP */ "Singapura",
        /*     TON */ "Tonga",
        /*     DMA */ "Dominica",
        /*     BHR */ "Bahrain",
        /*     KIR */ "Kiribati",
        /*     TCA */ "Kepulauan Turks dan Caicos|Caicos Islands",
        /*     STP */ "Sao Tome dan Principe|Principe",
        /*     HKG */ "Hongkong",
        /*     MTQ */ "Martinique",
        /*     FRO */ "Faroe|Kepulauan Faroe",
        /*     GLP */ "Guadeloupe",
        /*     COM */ "Komoro",
        /*     MUS */ "Mauritius",
        /*     REU */ "Reuni",
        /*     LUX */ "Luksemburg",
        /*     WSM */ "Samoa",
        /*     SGS */ "Georgia Selatan dan Kepulauan Sandwich Selatan|South Sandwich Islands",
        /*     PYF */ "Polinesia Perancis",
        /*     CPV */ "Cape Verde",
        /*     TTO */ "Trinidad dan Tobago|Tobago",
        /*     BRN */ "Brunei",
        /*     ATF */ "Daratan Selatan dan Antarktika Perancis",
        /*     PRI */ "Puerto Rico",
        /*     CYP */ "Siprus",
        /*     LBN */ "Libanon",
        /*     JAM */ "Jamaika",
        /*     GMB */ "Gambia",
        /*     QAT */ "Qatar",
        /*     FLK */ "Falklands|Kepulauan Falkland",
        /*     VUT */ "Vanuatu",
        /*     MNE */ "Montenegro",
        /*     BHS */ "Bahama",
        /*     TLS */ "Timor Timur",
        /*     SWZ */ "Swaziland",
        /*     KWT */ "Kuwait",
        /*     FJI */ "Fiji|Kepulauan Fiji",
        /*     NCL */ "Kaledonia Baru",
        /*     SVN */ "Slovenia",
        /*     ISR */ "Israel",
        /*     PSE */ "Wilayah Palestina",
        /*     SLV */ "El Salvador",
        /*     BLZ */ "Belize",
        /*     DJI */ "Djibouti",
        /*     MKD */ "Makedonia",
        /*     RWA */ "Rwanda",
        /*     HTI */ "Haiti",
        /*     BDI */ "Burundi",
        /*     GNQ */ "Guinea ekuator",
        /*     ALB */ "Albania",
        /*     SLB */ "Pulau Solomon",
        /*     ARM */ "Armenia",
        /*     LSO */ "Lesotho",
        /*     BEL */ "Belgium",
        /*     MDA */ "Moldova",
        /*     GNB */ "Guinea-Bissau",
        /*     TWN */ "Taiwan",
        /*     BTN */ "Bhutan",
        /*     CHE */ "Swiss",
        /*     NLD */ "Belanda",
        /*     DNK */ "Denmark",
        /*     EST */ "Estonia",
        /*     DOM */ "Republik Dominika",
        /*     SVK */ "Slovakia",
        /*     CRI */ "Kosta Rika",
        /*     BIH */ "Bosnia dan Herzegovina",
        /*     HRV */ "Kroasia",
        /*     TGO */ "Togo",
        /*     LVA */ "Latvia",
        /*     LTU */ "Lithuania",
        /*     LKA */ "Srilanka",
        /*     GEO */ "Georgia",
        /*     IRL */ "Irlandia",
        /*     SLE */ "Sierra Leone",
        /*     PAN */ "Panama",
        /*     CZE */ "Republik Ceko",
        /*     GUF */ "Guyana Perancis",
        /*     ARE */ "Uni Emirat Arab",
        /*     AUT */ "Austria",
        /*     AZE */ "Azerbaijan",
        /*     SRB */ "Serbia",
        /*     JOR */ "Jordan",
        /*     PRT */ "Portugal",
        /*     HUN */ "Hongaria",
        /*     KOR */ "Korea Selatan",
        /*     ISL */ "Islandia",
        /*     GTM */ "Guatemala",
        /*     CUB */ "Kuba",
        /*     BGR */ "Bulgaria",
        /*     LBR */ "Liberia",
        /*     HND */ "Honduras",
        /*     BEN */ "Benin",
        /*     ERI */ "Eritrea",
        /*     MWI */ "Malawi",
        /*     PRK */ "Korea Utara",
        /*     NIC */ "Nikaragua",
        /*     GRC */ "Yunani",
        /*     TJK */ "Tajikistan",
        /*     BGD */ "Bangladesh",
        /*     NPL */ "Nepal",
        /*     TUN */ "Tunisia",
        /*     SUR */ "Suriname",
        /*     URY */ "Uruguay",
        /*     KHM */ "Kamboja",
        /*     SYR */ "Suriah",
        /*     SEN */ "Senegal",
        /*     KGZ */ "Kyrgyzstan",
        /*     BLR */ "Belarus",
        /*     GUY */ "Guyana",
        /*     LAO */ "Laos",
        /*     ROU */ "Rumania",
        /*     GHA */ "Ghana",
        /*     UGA */ "Uganda",
        /*     GBR */ "Inggris Raya|Skotlandia|Inggris|Irlandia Utara|Irlandia, Northern",
        /*     GIN */ "Guinea",
        /*     ECU */ "Ekuador",
        /*     ESH */ "Sahara Barat|Sahrawi",
        /*     GAB */ "Gabon",
        /*     NZL */ "Selandia Baru",
        /*     BFA */ "Burkina Faso",
        /*     PHL */ "Pilipina",
        /*     ITA */ "Italia",
        /*     OMN */ "Oman",
        /*     POL */ "Polandia",
        /*     CIV */ "Pantai Gading",
        /*     NOR */ "Norway",
        /*     MYS */ "Malaysia",
        /*     VNM */ "Vietnam",
        /*     FIN */ "Finlandia",
        /*     COG */ "Kongo-Brazzaville",
        /*     DEU */ "Jerman",
        /*     JPN */ "Jepang",
        /*     ZWE */ "Zimbabwe",
        /*     PRY */ "Paraguai",
        /*     IRQ */ "Irak",
        /*     MAR */ "Maroko",
        /*     UZB */ "Uzbekistan",
        /*     SWE */ "Swedia",
        /*     PNG */ "Papua Nugini",
        /*     CMR */ "Kamerun",
        /*     TKM */ "Turkmenistan",
        /*     ESP */ "Spanyol",
        /*     THA */ "Thailand",
        /*     YEM */ "Yaman",
        /*     FRA */ "Perancis",
        /*     ALA */ "Kepulauan Aaland",
        /*     KEN */ "Kenya",
        /*     BWA */ "Botswana",
        /*     MDG */ "Madagaskar",
        /*     UKR */ "Ukraina",
        /*     SSD */ "Sudan Selatan",
        /*     CAF */ "Republik Afrika Tengah",
        /*     SOM */ "Somalia",
        /*     AFG */ "Afganistan",
        /*     MMR */ "Myanmar|Burma",
        /*     ZMB */ "Zambia",
        /*     CHL */ "Chili",
        /*     TUR */ "Turki",
        /*     PAK */ "Pakistan",
        /*     MOZ */ "Mozambik",
        /*     NAM */ "Namibia",
        /*     VEN */ "Venezuela",
        /*     NGA */ "Nigeria",
        /*     TZA */ "Tanzania",
        /*     EGY */ "Mesir",
        /*     MRT */ "Mauritania",
        /*     BOL */ "Bolivia",
        /*     ETH */ "Etiopia",
        /*     COL */ "Kolumbia",
        /*     ZAF */ "Afrika Selatan",
        /*     MLI */ "Mali",
        /*     AGO */ "Angola",
        /*     NER */ "Niger",
        /*     TCD */ "Chad",
        /*     PER */ "Peru",
        /*     MNG */ "Mongolia",
        /*     IRN */ "Iran",
        /*     LBY */ "Libya",
        /*     SDN */ "Sudan",
        /*     IDN */ "Indonesia",
        /*     DIF */ "Distrik Federal",
        /*     TLA */ "Tlaxcala",
        /*     MOR */ "Morelos",
        /*     AGU */ "Aguascalientes",
        /*   MX-CL */ "Colima",
        /*     QUE */ "Queretaro",
        /*     HID */ "Hidalgo",
        /*   MX-MX */ "Mexico State",
        /*     TAB */ "Tabasco",
        /*     NAY */ "Nayarit",
        /*     GUA */ "Guanajuato",
        /*     PUE */ "Puebla",
        /*     YUC */ "Yucatan",
        /*     ROO */ "Quintana Roo",
        /*     SIN */ "Sinaloa",
        /*     CAM */ "Campeche",
        /*     MIC */ "Michoacan",
        /*     SLP */ "San Luis Potosi",
        /*     GRO */ "Guerrero",
        /*     NLE */ "Nuevo Leon",
        /*     BCN */ "Baja California",
        /*     VER */ "Veracruz",
        /*     CHP */ "Chiapas",
        /*     BCS */ "Baja California Sur",
        /*     ZAC */ "Zacatecas",
        /*     JAL */ "Jalisco",
        /*     TAM */ "Tamaulipas",
        /*     OAX */ "Oaxaca",
        /*     DUR */ "Durango",
        /*     COA */ "Coahuila",
        /*     SON */ "Sonora",
        /*     CHH */ "Chihuahua",
        /*     GRL */ "Tanah penggembalaan",
        /*     SAU */ "Arab Saudi",
        /*     COD */ "Kongo-Kinshasa",
        /*     DZA */ "Aljazair",
        /*     KAZ */ "Kazakhstan",
        /*     ARG */ "Argentina",
        /*   IN-DD */ "Daman dan Diu",
        /*   IN-DN */ "Dadra dan Nagar Haveli",
        /*   IN-CH */ "Chandigarh",
        /*   IN-AN */ "Andaman dan Nicobar",
        /*   IN-LD */ "Lakshadweep",
        /*   IN-DL */ "Delhi",
        /*   IN-ML */ "Meghalaya",
        /*   IN-NL */ "Nagaland",
        /*   IN-MN */ "Manipur",
        /*   IN-TR */ "Tripura",
        /*   IN-MZ */ "Mizoram",
        /*   IN-SK */ "Sikkim",
        /*   IN-PB */ "Punjab",
        /*   IN-HR */ "Haryana",
        /*   IN-AR */ "Arunachal Pradesh",
        /*   IN-AS */ "Assam",
        /*   IN-BR */ "Bihar",
        /*   IN-UT */ "Uttarakhand",
        /*   IN-GA */ "Goa",
        /*   IN-KL */ "Kerala",
        /*   IN-TN */ "Tamil Nadu",
        /*   IN-HP */ "Himachal Pradesh",
        /*   IN-JK */ "Jammu dan Kashmir",
        /*   IN-CT */ "Chhattisgarh",
        /*   IN-JH */ "Jharkhand",
        /*   IN-KA */ "Karnataka",
        /*   IN-RJ */ "Rajasthan",
        /*   IN-OR */ "Odisha|Orissa",
        /*   IN-GJ */ "Gujarat",
        /*   IN-WB */ "Benggala barat",
        /*   IN-MP */ "Madhya Pradesh",
        /*   IN-TG */ "Telangana",
        /*   IN-AP */ "Andhra Pradesh",
        /*   IN-MH */ "Maharashtra",
        /*   IN-UP */ "Uttar Pradesh",
        /*   IN-PY */ "Puducherry",
        /*     NSW */ "New South Wales",
        /*     ACT */ "Wilayah Ibu Kota Australia",
        /*     JBT */ "Jervis Bay Wilayah",
        /*   AU-NT */ "Wilayah utara",
        /*   AU-SA */ "Australia Selatan",
        /*     TAS */ "Tasmania",
        /*     VIC */ "Victoria",
        /*   AU-WA */ "Australia Barat",
        /*     QLD */ "Queensland",
        /*   BR-DF */ "Distrito federal",
        /*   BR-SE */ "Sergipe",
        /*   BR-AL */ "Alagoas",
        /*   BR-RJ */ "Rio de Janeiro",
        /*   BR-ES */ "Espirito Santo",
        /*   BR-RN */ "Rio Grande do Norte",
        /*   BR-PB */ "Paraiba",
        /*   BR-SC */ "Santa Catarina",
        /*   BR-PE */ "Pernambuco",
        /*   BR-AP */ "Amapá",
        /*   BR-CE */ "Ceara",
        /*   BR-AC */ "Acre",
        /*   BR-PR */ "Parana",
        /*   BR-RR */ "Roraima",
        /*   BR-RO */ "Rondônia",
        /*   BR-SP */ "Sao Paulo",
        /*   BR-PI */ "Piauí",
        /*   BR-TO */ "Tocantins",
        /*   BR-RS */ "Rio Grande do Sul",
        /*   BR-MA */ "Maranhao",
        /*   BR-GO */ "Goias",
        /*   BR-MS */ "Mato Grosso do Sul",
        /*   BR-BA */ "Bahia",
        /*   BR-MG */ "Minas Gerais",
        /*   BR-MT */ "Mato Grosso",
        /*   BR-PA */ "Para",
        /*   BR-AM */ "Amazonas",
        /*   US-DC */ "District of Columbia",
        /*   US-RI */ "Rhode Island",
        /*   US-DE */ "Delaware",
        /*   US-CT */ "Connecticut",
        /*   US-NJ */ "New Jersey",
        /*   US-NH */ "New Hampshire",
        /*   US-VT */ "Vermont",
        /*   US-MA */ "Massachusetts",
        /*   US-HI */ "Hawaii",
        /*   US-MD */ "Maryland",
        /*   US-WV */ "West Virginia",
        /*   US-SC */ "South Carolina",
        /*   US-ME */ "Maine",
        /*   US-IN */ "Indiana",
        /*   US-KY */ "Kentucky",
        /*   US-TN */ "Tennessee",
        /*   US-VA */ "Virginia",
        /*   US-OH */ "Ohio",
        /*   US-PA */ "Pennsylvania",
        /*   US-MS */ "Mississippi",
        /*   US-LA */ "Louisiana",
        /*   US-AL */ "Alabama",
        /*   US-AR */ "Arkansas",
        /*   US-NC */ "North Carolina",
        /*   US-NY */ "New York",
        /*   US-IA */ "Iowa",
        /*   US-IL */ "Illinois",
        /*   US-GA */ "Georgia",
        /*   US-WI */ "Wisconsin",
        /*   US-FL */ "Florida",
        /*   US-MO */ "Missouri",
        /*   US-OK */ "Oklahoma",
        /*   US-ND */ "North Dakota",
        /*   US-WA */ "Washington",
        /*   US-SD */ "South Dakota",
        /*   US-NE */ "Nebraska",
        /*   US-KS */ "Kansas",
        /*   US-ID */ "Idaho",
        /*   US-UT */ "Utah",
        /*   US-MN */ "Minnesota",
        /*   US-MI */ "Michigan",
        /*   US-WY */ "Wyoming",
        /*   US-OR */ "Oregon",
        /*   US-CO */ "Colorado",
        /*   US-NV */ "Nevada",
        /*   US-AZ */ "Arizona",
        /*   US-NM */ "New Mexico",
        /*   US-MT */ "Montana",
        /*   US-CA */ "California",
        /*   US-TX */ "Texas",
        /*   US-AK */ "Alaska",
        /*   CA-BC */ "British Columbia",
        /*   CA-AB */ "Alberta",
        /*   CA-ON */ "Ontario",
        /*   CA-QC */ "Quebec",
        /*   CA-SK */ "Saskatchewan",
        /*   CA-MB */ "Manitoba",
        /*   CA-NL */ "Newfoundland",
        /*   CA-NB */ "New Brunswick",
        /*   CA-NS */ "Nova Scotia",
        /*   CA-PE */ "Pulau Pangeran Edward",
        /*   CA-YT */ "Yukon",
        /*   CA-NT */ "Northwest Territories",
        /*   CA-NU */ "Nunavut",
        /*     IND */ "India",
        /*     AUS */ "Australia",
        /*     BRA */ "Brazil",
        /*     USA */ "USA|Amerika Serikat|Amerika",
        /*     MEX */ "Mexico",
        /*     MOW */ "Moskow",
        /*     SPE */ "Saint Petersburg",
        /*     KGD */ "Kaliningrad Oblast",
        /*   RU-IN */ "Ingushetia Republik",
        /*   RU-AD */ "Adygea Republik",
        /*   RU-SE */ "Ossetia-Alania Republik utara",
        /*   RU-KB */ "Kabardino-Balkar Republic",
        /*   RU-KC */ "Karachay-Cherkess Republic",
        /*   RU-CE */ "Republik Chechnya",
        /*   RU-CU */ "Chuvash Republic",
        /*     IVA */ "Ivanovo Oblast",
        /*     LIP */ "Lipetsk Oblast",
        /*     ORL */ "Oryol Oblast",
        /*     TUL */ "Tula Oblast",
        /*   RU-BE */ "Belgorod Oblast",
        /*     VLA */ "Vladimir Oblast",
        /*     KRS */ "Kursk Oblast",
        /*     KLU */ "Kaluga Oblast",
        /*   RU-TT */ "Tambov Oblast",
        /*     BRY */ "Bryansk Oblast",
        /*     YAR */ "Yaroslavl Oblast",
        /*     RYA */ "Ryazan Oblast",
        /*     AST */ "Astrakhan Oblast",
        /*     MOS */ "Moscow Oblast",
        /*     SMO */ "Smolensk Oblast",
        /*   RU-DA */ "Dagestan Republik",
        /*     VOR */ "Voronezh Oblast",
        /*     NGR */ "Novgorod Oblast",
        /*     PSK */ "Pskov Oblast",
        /*     KOS */ "Kostroma Oblast",
        /*     STA */ "Stavropol Krai",
        /*     KDA */ "Krasnodar Krai",
        /*   RU-KL */ "Kalmykia Republik",
        /*     TVE */ "Tver Oblast",
        /*     LEN */ "Leningrad Oblast",
        /*     ROS */ "Rostov Oblast",
        /*     VGG */ "Volgograd Oblast",
        /*     VLG */ "Vologda Oblast",
        /*     MUR */ "Murmansk Oblast",
        /*   RU-KR */ "Karelia Republik",
        /*     NEN */ "Nenetsia",
        /*   RU-KO */ "Komi Republic",
        /*     ARK */ "Arkhangelsk Oblast",
        /*   RU-MO */ "Mordovia Republik",
        /*     NIZ */ "Nizhny Novgorod Oblast",
        /*     PNZ */ "Penza Oblast",
        /*   RU-KI */ "Kirov Oblast",
        /*   RU-ME */ "Mari El Republic",
        /*     ORE */ "Orenburg Oblast",
        /*     ULY */ "Ulyanovsk Oblast",
        /*   RU-PM */ "Perm Krai",
        /*   RU-BA */ "Bashkortostan Republic",
        /*   RU-UD */ "Udmurt Republic",
        /*   RU-TA */ "Republik Tatarstan",
        /*     SAM */ "Samara Oblast",
        /*     SAR */ "Saratov Oblast",
        /*     YAN */ "Yamalo-Nenets",
        /*   RU-KM */ "Khanty-Mansi",
        /*     SVE */ "Sverdlovsk Oblast",
        /*     TYU */ "Tyumen Oblast",
        /*     KGN */ "Kurgan Oblast",
        /*   RU-CH */ "Chelyabinsk Oblast",
        /*   RU-BU */ "Buryatia Republic",
        /*     ZAB */ "Krai Zabaykalsky",
        /*     IRK */ "Irkutsk Oblast",
        /*     NVS */ "Novosibirsk Oblast",
        /*     TOM */ "Tomsk Oblast",
        /*     OMS */ "Omsk Oblast",
        /*   RU-KK */ "Khakassia Republik",
        /*     KEM */ "Kemerovo Oblast",
        /*   RU-AL */ "Republik Altai",
        /*     ALT */ "Altai Krai",
        /*   RU-TY */ "Tuva Republic",
        /*     KYA */ "Krasnoyarsk Krai",
        /*     MAG */ "Magadan Oblast",
        /*     CHU */ "Chukotka Okrug",
        /*     KAM */ "Kamchatka Krai",
        /*     SAK */ "Sakhalin Oblast",
        /*   RU-PO */ "Primorsky Krai",
        /*     YEV */ "Oblast Otonom Yahudi",
        /*     KHA */ "Khabarovsk Krai",
        /*     AMU */ "Amur Oblast",
        /*   RU-SA */ "Republik Sakha|Yakutia Republic",
        /*     CAN */ "Kanada",
        /*     RUS */ "Rusia",
        /*   CN-SH */ "Menculik",
        /*   CN-TJ */ "Tianjin",
        /*   CN-BJ */ "Beijing",
        /*   CN-HI */ "Hainan",
        /*   CN-NX */ "Ningxia Hui",
        /*   CN-CQ */ "Chongqing",
        /*   CN-ZJ */ "Zhejiang",
        /*   CN-JS */ "Jiangsu",
        /*   CN-FJ */ "Fujian",
        /*   CN-AH */ "Anhui",
        /*   CN-LN */ "Liaoning",
        /*   CN-SD */ "Shandong",
        /*   CN-SX */ "Shanxi",
        /*   CN-JX */ "Jiangxi",
        /*   CN-HA */ "Henan",
        /*   CN-GZ */ "Guizhou",
        /*   CN-GD */ "Guangdong",
        /*   CN-HB */ "Hubei",
        /*   CN-JL */ "Jilin",
        /*   CN-HE */ "Hebei",
        /*   CN-SN */ "Shaanxi",
        /*   CN-NM */ "Nei Mongol|Mongolia Dalam",
        /*   CN-HL */ "Heilongjiang",
        /*   CN-HN */ "Hunan",
        /*   CN-GX */ "Guangxi Zhuang",
        /*   CN-SC */ "Sichuan",
        /*   CN-YN */ "Yunnan",
        /*   CN-XZ */ "Xizang|Tibet",
        /*   CN-GS */ "Gansu",
        /*   CN-QH */ "Qinghai",
        /*   CN-XJ */ "Xinjiang Uyghur",
        /*     CHN */ "Cina",
        /*     UMI */ "Kepulauan Terluar Kecil Amerika Serikat",
        /*     CPT */ "Pulau Clipperton",
        /*     ATA */ "Antartika",
        /*     AAA */ "Internasional|Dunia|Bumi"
#else // MAPCODE_SUPPORT_LANGUAGE_ID
        NULL
#endif // MAPCODE_SUPPORT_LANGUAGE_ID
};

#ifdef __cplusplus
}
#endif

#endif // __INTERNAL_TERRITORY_NAMES_ID_H__
