/*
 * Copyright (C) 2014-2017 Stichting Mapcode Foundation (http://www.mapcode.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef __INTERNAL_TERRITORY_NAMES_SV_H__
#define __INTERNAL_TERRITORY_NAMES_SV_H__

#ifdef __cplusplus
extern "C" {
#endif

// *** GENERATED FILE (coords.cpp), DO NOT CHANGE OR PRETTIFY ***

static const char *TERRITORY_FULL_NAME_SV[] = {
#ifdef MAPCODE_SUPPORT_LANGUAGE_SV // Swedish
        /*     VAT */ "Vatikanstaten|Heliga stolen",
        /*     MCO */ "Monaco",
        /*     GIB */ "Gibraltar",
        /*     TKL */ "Tokelau",
        /*     CCK */ "Kokosöarna|Keeling Islands",
        /*     BLM */ "Saint-Barthélemy",
        /*     NRU */ "Nauru",
        /*     TUV */ "Tuvalu",
        /*     MAC */ "Macau",
        /*     SXM */ "Sint Maarten",
        /*     MAF */ "Saint-Martin",
        /*     NFK */ "Norfolk och Philip Island|Philip Island",
        /*     PCN */ "Pitcairn Islands",
        /*     BVT */ "Bouvetön",
        /*     BMU */ "Bermuda",
        /*     IOT */ "Brittiska territoriet i Indiska oceanen",
        /*     SMR */ "San Marino",
        /*     GGY */ "Guernsey",
        /*     AIA */ "Anguilla",
        /*     MSR */ "Montserrat",
        /*     JEY */ "Jersey",
        /*     CXR */ "Julön",
        /*     WLF */ "Wallis och Futuna|Futuna",
        /*     VGB */ "Brittiska Jungfruöarna|Brittiska Jungfruöarna",
        /*     LIE */ "Liechtenstein",
        /*     ABW */ "Aruba",
        /*     MHL */ "Marshallöarna",
        /*     ASM */ "Amerikanska Samoa|Samoa, amerikansk",
        /*     COK */ "Cook öarna",
        /*     SPM */ "Saint Pierre och Miquelon|Miquelon",
        /*     NIU */ "Niue",
        /*     KNA */ "Saint Kitts och Nevis|Nevis",
        /*     CYM */ "Caymanöarna",
        /*     BES */ "Bonaire, St Eustatuis och Saba|Saba|St Eustatius",
        /*     MDV */ "Maldiverna",
        /*     SHN */ "Saint Helena, Ascension och Tristan da Cunha|Ascension|Tristan da Cunha",
        /*     MLT */ "Malta",
        /*     GRD */ "Grenada",
        /*     VIR */ "Amerikanska Jungfruöarna",
        /*     MYT */ "Mayotte",
        /*     SJM */ "Svalbard och Jan Mayen|Jan Mayen",
        /*     VCT */ "Saint Vincent och Grenadinerna|Grenadinerna",
        /*     HMD */ "Heard- och Mcdonaldöarna|McDonald öar",
        /*     BRB */ "Barbados",
        /*     ATG */ "Antigua och Barbuda|Barbuda",
        /*     CUW */ "Curacao",
        /*     SYC */ "Seychellerna",
        /*     PLW */ "Palau",
        /*     MNP */ "Nordmarianerna",
        /*     AND */ "Andorra",
        /*     GUM */ "Guam",
        /*     IMN */ "Ö av man",
        /*     LCA */ "Saint Lucia",
        /*     FSM */ "Mikronesiska federationen",
        /*     SGP */ "Singapore",
        /*     TON */ "Tonga",
        /*     DMA */ "Dominica",
        /*     BHR */ "Bahrain",
        /*     KIR */ "Kiribati",
        /*     TCA */ "Turks- och Caicosöarna|Caicosöarna",
        /*     STP */ "Sao Tomé och Principe|Principe",
        /*     HKG */ "Hong Kong",
        /*     MTQ */ "Martinique",
        /*     FRO */ "Färöarna",
        /*     GLP */ "Guadeloupe",
        /*     COM */ "Comoros",
        /*     MUS */ "Mauritius",
        /*     REU */ "Återförening",
        /*     LUX */ "Luxemburg",
        /*     WSM */ "Samoa",
        /*     SGS */ "Sydgeorgien och Sydsandwichöarna|Sydsandwichöarna",
        /*     PYF */ "Franska Polynesien",
        /*     CPV */ "Cap Verde",
        /*     TTO */ "Trinidad och Tobago|Tobago",
        /*     BRN */ "Brunei",
        /*     ATF */ "Franska sydliga och antarktiska Lands",
        /*     PRI */ "Puerto Rico",
        /*     CYP */ "Cypern",
        /*     LBN */ "Libanon",
        /*     JAM */ "Jamaica",
        /*     GMB */ "Gambia",
        /*     QAT */ "Qatar",
        /*     FLK */ "Falklandsöarna",
        /*     VUT */ "Vanuatu",
        /*     MNE */ "Monte~~POS=TRUNC",
        /*     BHS */ "Bahamas",
        /*     TLS */ "Östtimor",
        /*     SWZ */ "Swaziland",
        /*     KWT */ "Kuwait",
        /*     FJI */ "Fiji",
        /*     NCL */ "Nya Kaledonien",
        /*     SVN */ "Slovenien",
        /*     ISR */ "Israel",
        /*     PSE */ "Palestinska Territorier",
        /*     SLV */ "El Salvador",
        /*     BLZ */ "Belize",
        /*     DJI */ "Djibouti",
        /*     MKD */ "Makedonien",
        /*     RWA */ "Rwanda",
        /*     HTI */ "Haiti",
        /*     BDI */ "Burundi",
        /*     GNQ */ "Ekvatorialguinea",
        /*     ALB */ "Albanien",
        /*     SLB */ "Salomonöarna",
        /*     ARM */ "Armenien",
        /*     LSO */ "Lesotho",
        /*     BEL */ "Belgien",
        /*     MDA */ "Moldavien",
        /*     GNB */ "GUINEA-BISSAU",
        /*     TWN */ "Taiwan",
        /*     BTN */ "Bhutan",
        /*     CHE */ "Schweiz",
        /*     NLD */ "Nederländerna",
        /*     DNK */ "Danmark",
        /*     EST */ "Estland",
        /*     DOM */ "Dominikanska republiken",
        /*     SVK */ "Slovakien",
        /*     CRI */ "Costa rica",
        /*     BIH */ "Bosnien och Hercegovina",
        /*     HRV */ "Kroatien",
        /*     TGO */ "Togo",
        /*     LVA */ "Lettland",
        /*     LTU */ "Litauen",
        /*     LKA */ "Sri Lanka",
        /*     GEO */ "Georgien",
        /*     IRL */ "Irland",
        /*     SLE */ "Sierra Leone",
        /*     PAN */ "Panama",
        /*     CZE */ "Tjeckien",
        /*     GUF */ "Franska Guyana",
        /*     ARE */ "Förenade Arabemiraten",
        /*     AUT */ "Österrike",
        /*     AZE */ "Azerbaijan",
        /*     SRB */ "Serbien",
        /*     JOR */ "Jordanien",
        /*     PRT */ "Portugal",
        /*     HUN */ "Ungern",
        /*     KOR */ "Sydkorea",
        /*     ISL */ "Island",
        /*     GTM */ "Guatemala",
        /*     CUB */ "Kuba",
        /*     BGR */ "Bulgarien",
        /*     LBR */ "Liberia",
        /*     HND */ "Honduras",
        /*     BEN */ "Benin",
        /*     ERI */ "Eritrea",
        /*     MWI */ "Malawi",
        /*     PRK */ "Nordkorea",
        /*     NIC */ "Nicaragua",
        /*     GRC */ "Grekland",
        /*     TJK */ "Tadzjikistan",
        /*     BGD */ "Bangladesh",
        /*     NPL */ "Nepal",
        /*     TUN */ "Tunisien",
        /*     SUR */ "Suriname",
        /*     URY */ "Uruguay",
        /*     KHM */ "Kambodja",
        /*     SYR */ "Syrien",
        /*     SEN */ "Senegal",
        /*     KGZ */ "Kyrgyzstan",
        /*     BLR */ "Vitryssland",
        /*     GUY */ "Guyana",
        /*     LAO */ "Laos",
        /*     ROU */ "Rumänien",
        /*     GHA */ "Ghana",
        /*     UGA */ "Uganda",
        /*     GBR */ "Storbritannien|Skottland|Nordirland|Irland, Northern",
        /*     GIN */ "Guinea",
        /*     ECU */ "Ecuador",
        /*     ESH */ "Västsahara|Sahrawi",
        /*     GAB */ "Gabon",
        /*     NZL */ "Nya Zeeland",
        /*     BFA */ "Burkina Faso",
        /*     PHL */ "Filippinerna",
        /*     ITA */ "Italien",
        /*     OMN */ "Oman",
        /*     POL */ "Polen",
        /*     CIV */ "Elfenbenskusten",
        /*     NOR */ "Norge",
        /*     MYS */ "Malaysia",
        /*     VNM */ "Vietnam",
        /*     FIN */ "Finland",
        /*     COG */ "Kongo-Brazzaville",
        /*     DEU */ "Tyskland",
        /*     JPN */ "Japan",
        /*     ZWE */ "Zimbabwe",
        /*     PRY */ "Paraguay",
        /*     IRQ */ "Irak",
        /*     MAR */ "Marocko",
        /*     UZB */ "Uzbekistan",
        /*     SWE */ "Sverige",
        /*     PNG */ "Papua Nya Guinea",
        /*     CMR */ "Kamerun",
        /*     TKM */ "Turkmenistan",
        /*     ESP */ "Spanien",
        /*     THA */ "Thailand",
        /*     YEM */ "Jemen",
        /*     FRA */ "Frankrike",
        /*     ALA */ "Åland",
        /*     KEN */ "Kenya",
        /*     BWA */ "Botswana",
        /*     MDG */ "Madagaskar",
        /*     UKR */ "Ukraina",
        /*     SSD */ "Södra Sudan",
        /*     CAF */ "Centralafrikanska republiken",
        /*     SOM */ "Somalia",
        /*     AFG */ "Afghanistan",
        /*     MMR */ "Myanmar|Burma",
        /*     ZMB */ "Zambia",
        /*     CHL */ "Chile",
        /*     TUR */ "Turkiet",
        /*     PAK */ "Pakistan",
        /*     MOZ */ "Moçambique",
        /*     NAM */ "Namibia",
        /*     VEN */ "Venezuela",
        /*     NGA */ "Nigeria",
        /*     TZA */ "Tanzania",
        /*     EGY */ "Egypten",
        /*     MRT */ "Mauretanien",
        /*     BOL */ "Bolivia",
        /*     ETH */ "Etiopien",
        /*     COL */ "Colombia",
        /*     ZAF */ "Sydafrika",
        /*     MLI */ "Mali",
        /*     AGO */ "Angola",
        /*     NER */ "Niger",
        /*     TCD */ "Tchad",
        /*     PER */ "Peru",
        /*     MNG */ "Mongoliet",
        /*     IRN */ "Iran",
        /*     LBY */ "Libyen",
        /*     SDN */ "Sudan",
        /*     IDN */ "Indonesien",
        /*     DIF */ "Federal District",
        /*     TLA */ "Tlaxcala",
        /*     MOR */ "Morelos",
        /*     AGU */ "Aguascalientes",
        /*   MX-CL */ "Colima",
        /*     QUE */ "Queretaro",
        /*     HID */ "Hidalgo",
        /*   MX-MX */ "Mexico State",
        /*     TAB */ "Tabasco",
        /*     NAY */ "Nayarit",
        /*     GUA */ "Guanajuato",
        /*     PUE */ "Puebla",
        /*     YUC */ "Yucatan",
        /*     ROO */ "Quintana Roo",
        /*     SIN */ "Sinaloa",
        /*     CAM */ "Campeche",
        /*     MIC */ "Michoacan",
        /*     SLP */ "San Luis Potosi",
        /*     GRO */ "Guerrero",
        /*     NLE */ "Nuevo Leon",
        /*     BCN */ "Baja California",
        /*     VER */ "Vera",
        /*     CHP */ "Chiapas",
        /*     BCS */ "Baja California Sur",
        /*     ZAC */ "Zacatecas",
        /*     JAL */ "Jalisco",
        /*     TAM */ "Tamaulipas",
        /*     OAX */ "Oaxaca",
        /*     DUR */ "Durango",
        /*     COA */ "Coahuila",
        /*     SON */ "Sonora",
        /*     CHH */ "Chihuahua",
        /*     GRL */ "Grönland",
        /*     SAU */ "Saudiarabien",
        /*     COD */ "Kongo-Kinshasa",
        /*     DZA */ "Algeriet",
        /*     KAZ */ "Kazakstan",
        /*     ARG */ "Argentina",
        /*   IN-DD */ "Daman och Diu",
        /*   IN-DN */ "Dadra and Nagar Haveli",
        /*   IN-CH */ "Chandigarh",
        /*   IN-AN */ "Andaman and Nicobar",
        /*   IN-LD */ "Lakshadweep",
        /*   IN-DL */ "Delhi",
        /*   IN-ML */ "Meghalaya",
        /*   IN-NL */ "Nagaland",
        /*   IN-MN */ "Manipur",
        /*   IN-TR */ "Tripura",
        /*   IN-MZ */ "Mizoram",
        /*   IN-SK */ "Sikkim",
        /*   IN-PB */ "Punjab",
        /*   IN-HR */ "Haryana",
        /*   IN-AR */ "Arunachal Pradesh",
        /*   IN-AS */ "Assam",
        /*   IN-BR */ "Bihar",
        /*   IN-UT */ "Uttarakhand",
        /*   IN-GA */ "Goa",
        /*   IN-KL */ "Kerala",
        /*   IN-TN */ "Tamil Nadu",
        /*   IN-HP */ "Himachal Pradesh",
        /*   IN-JK */ "Jammu och Kashmir",
        /*   IN-CT */ "Chhattisgarh",
        /*   IN-JH */ "Jharkhand",
        /*   IN-KA */ "Karnatakaen",
        /*   IN-RJ */ "Rajasthan",
        /*   IN-OR */ "Odisha|Orissa",
        /*   IN-GJ */ "Gujarat",
        /*   IN-WB */ "Västbengalen",
        /*   IN-MP */ "Madhya Pradesh",
        /*   IN-TG */ "Telangana",
        /*   IN-AP */ "Andhra Pradesh",
        /*   IN-MH */ "Maharashtra",
        /*   IN-UP */ "Uttar Pradesh",
        /*   IN-PY */ "Puducherry",
        /*     NSW */ "New South Wales",
        /*     ACT */ "Australian Capital Territory",
        /*     JBT */ "Jervis Bay Territory",
        /*   AU-NT */ "Northern Territory",
        /*   AU-SA */ "South Australia",
        /*     TAS */ "Tasmanien",
        /*     VIC */ "Victoria",
        /*   AU-WA */ "Västra Australien",
        /*     QLD */ "Queensland",
        /*   BR-DF */ "Distrito Federal",
        /*   BR-SE */ "Sergipe",
        /*   BR-AL */ "Alagoas",
        /*   BR-RJ */ "Rio de Janeiro",
        /*   BR-ES */ "Espirito Santo",
        /*   BR-RN */ "Rio Grande do Norte",
        /*   BR-PB */ "Paraiba",
        /*   BR-SC */ "Santa Catarina",
        /*   BR-PE */ "Pernambuco",
        /*   BR-AP */ "Amapa",
        /*   BR-CE */ "Ceara",
        /*   BR-AC */ "Acre",
        /*   BR-PR */ "Parana",
        /*   BR-RR */ "Roraima",
        /*   BR-RO */ "Rondonia",
        /*   BR-SP */ "Sao Paulo",
        /*   BR-PI */ "Piaui",
        /*   BR-TO */ "Tocantins",
        /*   BR-RS */ "Rio Grande do Sul",
        /*   BR-MA */ "Maranhao",
        /*   BR-GO */ "Goias",
        /*   BR-MS */ "Mato Grosso do Sul",
        /*   BR-BA */ "Bahia",
        /*   BR-MG */ "Minas Gerais",
        /*   BR-MT */ "Mato Grosso",
        /*   BR-PA */ "Para",
        /*   BR-AM */ "Amazonas",
        /*   US-DC */ "District of Columbia",
        /*   US-RI */ "Rhode Island",
        /*   US-DE */ "Delaware",
        /*   US-CT */ "Connecticut",
        /*   US-NJ */ "New Jersey",
        /*   US-NH */ "New Hampshire",
        /*   US-VT */ "Vermont",
        /*   US-MA */ "Massachusetts",
        /*   US-HI */ "Hawaii",
        /*   US-MD */ "Maryland",
        /*   US-WV */ "Västra Virginia|West Virginia",
        /*   US-SC */ "South Carolina",
        /*   US-ME */ "Maine",
        /*   US-IN */ "Indiana",
        /*   US-KY */ "Kentucky",
        /*   US-TN */ "Tennessee",
        /*   US-VA */ "Virginia",
        /*   US-OH */ "Ohio",
        /*   US-PA */ "Pennsylvania sylvania~~POS=HEADCOMP",
        /*   US-MS */ "Mississippi",
        /*   US-LA */ "Louisiana",
        /*   US-AL */ "Alabama",
        /*   US-AR */ "Arkansas",
        /*   US-NC */ "Norra Carolina",
        /*   US-NY */ "New York",
        /*   US-IA */ "Iowa",
        /*   US-IL */ "Illinois",
        /*   US-GA */ "Georgien",
        /*   US-WI */ "Wisconsin",
        /*   US-FL */ "Florida",
        /*   US-MO */ "Missouri",
        /*   US-OK */ "Oklahoma",
        /*   US-ND */ "Norra Dakota",
        /*   US-WA */ "Washington",
        /*   US-SD */ "South Dakota",
        /*   US-NE */ "Nebraska",
        /*   US-KS */ "Kansas",
        /*   US-ID */ "Idaho",
        /*   US-UT */ "Utah",
        /*   US-MN */ "Minnesota",
        /*   US-MI */ "Michigan",
        /*   US-WY */ "Wyoming",
        /*   US-OR */ "Oregon",
        /*   US-CO */ "Colorado",
        /*   US-NV */ "Nevada",
        /*   US-AZ */ "Arizona",
        /*   US-NM */ "New Mexico",
        /*   US-MT */ "Montana",
        /*   US-CA */ "Kalifornien",
        /*   US-TX */ "Texas",
        /*   US-AK */ "Alaska",
        /*   CA-BC */ "British Columbia",
        /*   CA-AB */ "Alberta",
        /*   CA-ON */ "Ontario",
        /*   CA-QC */ "Quebec",
        /*   CA-SK */ "Saskatchewan",
        /*   CA-MB */ "Manitoba",
        /*   CA-NL */ "Newfoundland",
        /*   CA-NB */ "New Brunswick",
        /*   CA-NS */ "Nova Scotia",
        /*   CA-PE */ "Prins Edward ö",
        /*   CA-YT */ "Yukon",
        /*   CA-NT */ "Northwest Territories",
        /*   CA-NU */ "Nunavut",
        /*     IND */ "Indien",
        /*     AUS */ "Australien",
        /*     BRA */ "Brasilien",
        /*     USA */ "USA|Amerikas förenta stater|Amerika",
        /*     MEX */ "Mexico",
        /*     MOW */ "Moskva",
        /*     SPE */ "Sankt Petersburg",
        /*     KGD */ "Kaliningrad",
        /*   RU-IN */ "Ingushetia republiken",
        /*   RU-AD */ "Adygea Republic",
        /*   RU-SE */ "Nordossetien republiken",
        /*   RU-KB */ "Kabardino-Balkar Republic",
        /*   RU-KC */ "Karachay-Cherkess Republic",
        /*   RU-CE */ "Tjetjenien",
        /*   RU-CU */ "Chuvash Republic",
        /*     IVA */ "Ivanovo Oblast",
        /*     LIP */ "Lipetsk Oblast",
        /*     ORL */ "Oryol Oblast",
        /*     TUL */ "Tula",
        /*   RU-BE */ "Belgorod oblast",
        /*     VLA */ "Vladimir Oblast",
        /*     KRS */ "Kursk Oblast",
        /*     KLU */ "Kaluga oblast",
        /*   RU-TT */ "Tambov oblast",
        /*     BRY */ "Brjansk oblast",
        /*     YAR */ "Yaroslavl Oblast",
        /*     RYA */ "Ryazan Oblast",
        /*     AST */ "Astrachan oblast",
        /*     MOS */ "Moscow Oblast",
        /*     SMO */ "Smolensk oblast",
        /*   RU-DA */ "Dagestan republiken",
        /*     VOR */ "Voronezj oblast",
        /*     NGR */ "Novgorod Oblast",
        /*     PSK */ "Pskov Oblast",
        /*     KOS */ "Kostroma Oblast",
        /*     STA */ "Stavropol Krai",
        /*     KDA */ "Krasnodar Krai",
        /*   RU-KL */ "Kalmykiarepubliken",
        /*     TVE */ "Tver Oblast",
        /*     LEN */ "Leningrad Oblast",
        /*     ROS */ "Rostov Oblast",
        /*     VGG */ "Volgograd Oblast",
        /*     VLG */ "Vologda oblast",
        /*     MUR */ "Murmansk",
        /*   RU-KR */ "Karelia republiken",
        /*     NEN */ "Nentsien",
        /*   RU-KO */ "Komi Republic",
        /*     ARK */ "Arkhangelsk",
        /*   RU-MO */ "Mordovia Republic",
        /*     NIZ */ "Nizhny Novgorod Oblast",
        /*     PNZ */ "Penza Oblast",
        /*   RU-KI */ "Kirov Oblast",
        /*   RU-ME */ "Mari El Republic",
        /*     ORE */ "Oren Oblast",
        /*     ULY */ "Uljanovsk oblast",
        /*   RU-PM */ "Perm Krai",
        /*   RU-BA */ "Bashkortostan Republic",
        /*   RU-UD */ "Udmurt Republic",
        /*   RU-TA */ "Tatarstan",
        /*     SAM */ "Samara Oblast",
        /*     SAR */ "Saratov Oblast",
        /*     YAN */ "Yamalo-Nenets",
        /*   RU-KM */ "Khanty-Mansi",
        /*     SVE */ "Sverdlovsk Oblast",
        /*     TYU */ "Tyumen Oblast",
        /*     KGN */ "Kurgan Oblast",
        /*   RU-CH */ "Tjeljabinsk",
        /*   RU-BU */ "Republiken Burjatien",
        /*     ZAB */ "Zabaykalsky Krai",
        /*     IRK */ "Irkutsk Oblast",
        /*     NVS */ "Novosibirsk Oblast",
        /*     TOM */ "Tomsk Oblast",
        /*     OMS */ "Omsk Oblast",
        /*   RU-KK */ "Chakassien Republiken",
        /*     KEM */ "Kemerovo oblast",
        /*   RU-AL */ "Altajrepubliken",
        /*     ALT */ "Altaj kraj",
        /*   RU-TY */ "Tuva republiken",
        /*     KYA */ "Krasnoyarsk Krai",
        /*     MAG */ "Magadan Oblast",
        /*     CHU */ "Chukotka Okrug",
        /*     KAM */ "Kamchatka Krai",
        /*     SAK */ "Sakhalin Oblast",
        /*   RU-PO */ "Primorsky Krai",
        /*     YEV */ "Judiska autonoma länet",
        /*     KHA */ "Chabarovsk",
        /*     AMU */ "Amur Oblast",
        /*   RU-SA */ "Sacha Republiken|Yakutia republiken",
        /*     CAN */ "Kanada",
        /*     RUS */ "Ryssland",
        /*   CN-SH */ "Shanghai",
        /*   CN-TJ */ "Tianjin",
        /*   CN-BJ */ "Peking",
        /*   CN-HI */ "Hainan",
        /*   CN-NX */ "Ningxia Hui",
        /*   CN-CQ */ "Chongqing",
        /*   CN-ZJ */ "Zhejiang",
        /*   CN-JS */ "Jiangsu",
        /*   CN-FJ */ "Fujian",
        /*   CN-AH */ "Anhui",
        /*   CN-LN */ "Liaoning",
        /*   CN-SD */ "Shandong",
        /*   CN-SX */ "Shanxi",
        /*   CN-JX */ "Jiangxi",
        /*   CN-HA */ "Henan",
        /*   CN-GZ */ "Guizhou",
        /*   CN-GD */ "Guangdong",
        /*   CN-HB */ "Hubei",
        /*   CN-JL */ "Jilin",
        /*   CN-HE */ "Hebei",
        /*   CN-SN */ "Shaanxi",
        /*   CN-NM */ "Nei Mongol|Inre Mongoliet",
        /*   CN-HL */ "Heilongjiang",
        /*   CN-HN */ "Hunan",
        /*   CN-GX */ "Guangxi Zhuang",
        /*   CN-SC */ "Sichuan",
        /*   CN-YN */ "Yunnan",
        /*   CN-XZ */ "Xizang|Tibet",
        /*   CN-GS */ "Gansu",
        /*   CN-QH */ "Qinghai",
        /*   CN-XJ */ "Xinjiang Uyghur",
        /*     CHN */ "Kina",
        /*     UMI */ "Förenta staternas avlägset belägna öar",
        /*     CPT */ "Clipperton",
        /*     ATA */ "Antarktis",
        /*     AAA */ "Internationell|Världen|Jorden"
#else // MAPCODE_SUPPORT_LANGUAGE_SV
        NULL
#endif // MAPCODE_SUPPORT_LANGUAGE_SV
};

#ifdef __cplusplus
}
#endif

#endif // __INTERNAL_TERRITORY_NAMES_SV_H__
