/*
 * Copyright (C) 2014-2017 Stichting Mapcode Foundation (http://www.mapcode.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef __INTERNAL_TERRITORY_NAMES_SW_H__
#define __INTERNAL_TERRITORY_NAMES_SW_H__

#ifdef __cplusplus
extern "C" {
#endif

// *** GENERATED FILE (coords.cpp), DO NOT CHANGE OR PRETTIFY ***

static const char *TERRITORY_FULL_NAME_SW[] = {
#ifdef MAPCODE_SUPPORT_LANGUAGE_SW // Swahili
        /*     VAT */ "Vatican City|Kitakatifu",
        /*     MCO */ "Monaco",
        /*     GIB */ "Gibraltar",
        /*     TKL */ "Tokelau",
        /*     CCK */ "Cocos Visiwa vya|Keeling Islands",
        /*     BLM */ "Saint-Barthelemy",
        /*     NRU */ "Nauru",
        /*     TUV */ "Tuvalu",
        /*     MAC */ "Macau",
        /*     SXM */ "Sint Maarten",
        /*     MAF */ "Saint-Martin",
        /*     NFK */ "Norfolk na Philip Island|Philip Island",
        /*     PCN */ "Visiwa vya Pitcairn",
        /*     BVT */ "Bouvet Island",
        /*     BMU */ "Bermuda",
        /*     IOT */ "Uingereza katika Bahari Hindi",
        /*     SMR */ "San Marino",
        /*     GGY */ "Guernsey",
        /*     AIA */ "Anguilla",
        /*     MSR */ "Montserrat",
        /*     JEY */ "Jersey",
        /*     CXR */ "Kisiwa cha Krismasi",
        /*     WLF */ "Wallis na Futuna|Futuna",
        /*     VGB */ "British Virgin Islands|Virgin Islands, British",
        /*     LIE */ "Liechtenstein",
        /*     ABW */ "Aruba",
        /*     MHL */ "Visiwa vya Marshall",
        /*     ASM */ "American Samoa|Samoa, American",
        /*     COK */ "Visiwa Cook",
        /*     SPM */ "Saint Pierre na Miquelon|Miquelon",
        /*     NIU */ "Niue",
        /*     KNA */ "Saint Kitts na Nevis|Nevis",
        /*     CYM */ "Visiwa Cayman",
        /*     BES */ "Bonaire, St Eustatuis na Saba|Saba|St Eustatius",
        /*     MDV */ "Maldives",
        /*     SHN */ "Saint Helena, Ascension na Tristan da Cunha|Ascension|Tristan da Cunha",
        /*     MLT */ "Malta",
        /*     GRD */ "Grenada",
        /*     VIR */ "Visiwa vya Virgin vya Marekani|Visiwa vya Virgin, Marekani",
        /*     MYT */ "Mayotte",
        /*     SJM */ "Svalbard na Jan Mayen|Jan Mayen",
        /*     VCT */ "Saint Vincent na Grenadines|Grenadines",
        /*     HMD */ "Kusikia Kisiwa na McDonald Visiwa|McDonald Visiwa",
        /*     BRB */ "Barbados",
        /*     ATG */ "Antigua na Barbuda|Barbuda",
        /*     CUW */ "Curacao",
        /*     SYC */ "Shelisheli",
        /*     PLW */ "Palau",
        /*     MNP */ "Visiwa vya Mariana ya Kaskazini",
        /*     AND */ "Andorra",
        /*     GUM */ "Guam",
        /*     IMN */ "Kisiwa cha Man",
        /*     LCA */ "Mtakatifu Lucia",
        /*     FSM */ "Micronesia|Shirikisho la Mikronesia",
        /*     SGP */ "Singapore",
        /*     TON */ "Tonga",
        /*     DMA */ "Dominica",
        /*     BHR */ "Bahrain",
        /*     KIR */ "Kiribati",
        /*     TCA */ "Turks na Caicos|Caicos",
        /*     STP */ "Sao Tome na Principe|Principe",
        /*     HKG */ "Hong Kong",
        /*     MTQ */ "Martinique",
        /*     FRO */ "Visiwa vya Faroe",
        /*     GLP */ "Guadeloupe",
        /*     COM */ "Comoro",
        /*     MUS */ "Mauritius",
        /*     REU */ "Reunion",
        /*     LUX */ "Luxembourg",
        /*     WSM */ "Samoa",
        /*     SGS */ "South Georgia na South Sandwich Islands|Visiwa vya South Sandwich",
        /*     PYF */ "Polynesia ya Kifaransa",
        /*     CPV */ "Cape Verde",
        /*     TTO */ "Trinidad na Tobago|Tobago",
        /*     BRN */ "Brunei",
        /*     ATF */ "Kusini mwa Ufaransa na Antarctic Ardhi",
        /*     PRI */ "Pwetoriko",
        /*     CYP */ "Cyprus",
        /*     LBN */ "Lebanon",
        /*     JAM */ "Jamaica",
        /*     GMB */ "Gambia",
        /*     QAT */ "Qatar",
        /*     FLK */ "Visiwa vya Falkland",
        /*     VUT */ "Vanuatu",
        /*     MNE */ "Montenegro",
        /*     BHS */ "Bahamas",
        /*     TLS */ "Timor ya Mashariki",
        /*     SWZ */ "Swaziland",
        /*     KWT */ "Kuwait",
        /*     FJI */ "Fiji Visiwa vya",
        /*     NCL */ "Caledonia New",
        /*     SVN */ "Slovenia",
        /*     ISR */ "Israel",
        /*     PSE */ "Maeneo ya Palestina",
        /*     SLV */ "El Salvador",
        /*     BLZ */ "Belize",
        /*     DJI */ "Djibouti",
        /*     MKD */ "Makedonia",
        /*     RWA */ "Rwanda",
        /*     HTI */ "Haiti",
        /*     BDI */ "Burundi",
        /*     GNQ */ "Equatorial Guinea",
        /*     ALB */ "Albania",
        /*     SLB */ "Visiwa vya Solomon",
        /*     ARM */ "Armenia",
        /*     LSO */ "Lesotho",
        /*     BEL */ "Ubelgiji",
        /*     MDA */ "Moldova",
        /*     GNB */ "Guinea-Bissau",
        /*     TWN */ "Taiwan",
        /*     BTN */ "Bhutan",
        /*     CHE */ "Switzerland",
        /*     NLD */ "Uholanzi",
        /*     DNK */ "Denmark",
        /*     EST */ "Estonia",
        /*     DOM */ "Jamhuri ya Dominika",
        /*     SVK */ "Slovakia",
        /*     CRI */ "Costa Rica",
        /*     BIH */ "Bosnia na Herzegovina",
        /*     HRV */ "Croatia",
        /*     TGO */ "Togo",
        /*     LVA */ "Latvia",
        /*     LTU */ "Lithuania",
        /*     LKA */ "Sri Lanka",
        /*     GEO */ "Georgia",
        /*     IRL */ "Ireland",
        /*     SLE */ "Sierra Leone",
        /*     PAN */ "Panama",
        /*     CZE */ "Jamhuri ya Czech",
        /*     GUF */ "Kifaransa Guiana",
        /*     ARE */ "Umoja wa Falme za Kiarabu",
        /*     AUT */ "Austria",
        /*     AZE */ "Azerbaijan",
        /*     SRB */ "Serbia",
        /*     JOR */ "Jordan",
        /*     PRT */ "Ureno",
        /*     HUN */ "Hungary",
        /*     KOR */ "Korea ya Kusini",
        /*     ISL */ "Iceland",
        /*     GTM */ "Guatemala",
        /*     CUB */ "Cuba",
        /*     BGR */ "Bulgaria",
        /*     LBR */ "Liberia",
        /*     HND */ "Honduras",
        /*     BEN */ "Benin",
        /*     ERI */ "Eritrea",
        /*     MWI */ "Malawi",
        /*     PRK */ "Korea Kaskazini",
        /*     NIC */ "Nicaragua",
        /*     GRC */ "Ugiriki",
        /*     TJK */ "Tajikistan",
        /*     BGD */ "Bangladesh",
        /*     NPL */ "Nepal",
        /*     TUN */ "Tunisia",
        /*     SUR */ "Surinam",
        /*     URY */ "Uruguay",
        /*     KHM */ "Cambodia",
        /*     SYR */ "Syria",
        /*     SEN */ "Senegal",
        /*     KGZ */ "Kyrgyzstan",
        /*     BLR */ "Belarus",
        /*     GUY */ "Guyana",
        /*     LAO */ "Laos",
        /*     ROU */ "Romania",
        /*     GHA */ "Ghana",
        /*     UGA */ "Uganda",
        /*     GBR */ "Uingereza|Scotland|Mkuu wa Uingereza|Northern Ireland|Ireland, Northern",
        /*     GIN */ "Guinea",
        /*     ECU */ "Ecuador",
        /*     ESH */ "Western Sahara|Saharawi",
        /*     GAB */ "Gabon",
        /*     NZL */ "New Zealand",
        /*     BFA */ "Burkina Faso",
        /*     PHL */ "Philippines",
        /*     ITA */ "Italia",
        /*     OMN */ "Oman",
        /*     POL */ "Poland",
        /*     CIV */ "Ivory Coast",
        /*     NOR */ "Norway",
        /*     MYS */ "Malaysia",
        /*     VNM */ "Vietnam",
        /*     FIN */ "Finland",
        /*     COG */ "Congo-Brazzaville",
        /*     DEU */ "Ujerumani",
        /*     JPN */ "Japan",
        /*     ZWE */ "Zimbabwe",
        /*     PRY */ "Paraguay",
        /*     IRQ */ "Iraq",
        /*     MAR */ "Morocco",
        /*     UZB */ "Uzbekistan",
        /*     SWE */ "Sweden",
        /*     PNG */ "Papua New Guinea",
        /*     CMR */ "Cameroon",
        /*     TKM */ "Turkmenistan",
        /*     ESP */ "Hispania",
        /*     THA */ "Thailand",
        /*     YEM */ "Yemen",
        /*     FRA */ "Ufaransa",
        /*     ALA */ "Aaland Visiwa",
        /*     KEN */ "Kenya",
        /*     BWA */ "Botswana",
        /*     MDG */ "Madagascar",
        /*     UKR */ "Ukraine",
        /*     SSD */ "Sudan Kusini",
        /*     CAF */ "Jamhuri ya Afrika ya Kati",
        /*     SOM */ "Somalia",
        /*     AFG */ "Afghanistan",
        /*     MMR */ "Myanmar|Burma",
        /*     ZMB */ "Zambia",
        /*     CHL */ "Chile",
        /*     TUR */ "Uturuki",
        /*     PAK */ "Pakistan",
        /*     MOZ */ "Msumbiji",
        /*     NAM */ "Namibia",
        /*     VEN */ "Venezuela",
        /*     NGA */ "Nigeria",
        /*     TZA */ "Tanzania",
        /*     EGY */ "Misri",
        /*     MRT */ "Mauritania",
        /*     BOL */ "Bolivia",
        /*     ETH */ "Ethiopia",
        /*     COL */ "Colombia",
        /*     ZAF */ "Africa Kusini",
        /*     MLI */ "Mali",
        /*     AGO */ "Angola",
        /*     NER */ "Niger",
        /*     TCD */ "Chad",
        /*     PER */ "Peru",
        /*     MNG */ "Mongolia",
        /*     IRN */ "Iran",
        /*     LBY */ "Libya",
        /*     SDN */ "Sudan",
        /*     IDN */ "Indonesia",
        /*     DIF */ "Wilaya ya shirikisho",
        /*     TLA */ "Tlaxcala",
        /*     MOR */ "Morelos",
        /*     AGU */ "Aguascalientes",
        /*   MX-CL */ "Colima",
        /*     QUE */ "Queretaro",
        /*     HID */ "Hidalgo",
        /*   MX-MX */ "Mexico State",
        /*     TAB */ "Tabasco",
        /*     NAY */ "Nayarit",
        /*     GUA */ "Guanajuato",
        /*     PUE */ "Puebla",
        /*     YUC */ "Yucatan",
        /*     ROO */ "Quintana Roo",
        /*     SIN */ "Sinaloa",
        /*     CAM */ "Campeche",
        /*     MIC */ "Michoacan",
        /*     SLP */ "San Luis Potosi",
        /*     GRO */ "Guerrero",
        /*     NLE */ "Nuevo Leon",
        /*     BCN */ "Baja California",
        /*     VER */ "Veracruz",
        /*     CHP */ "Chiapas",
        /*     BCS */ "Baja California Sur",
        /*     ZAC */ "Zacatecas",
        /*     JAL */ "Jalisco",
        /*     TAM */ "Tamaulipas",
        /*     OAX */ "Oaxaca",
        /*     DUR */ "Durango",
        /*     COA */ "Coahuila",
        /*     SON */ "Sonora",
        /*     CHH */ "Chihuahua",
        /*     GRL */ "Greenland",
        /*     SAU */ "Saudi Arabia",
        /*     COD */ "Congo-Kinshasa",
        /*     DZA */ "Algeria",
        /*     KAZ */ "Kazakhstan",
        /*     ARG */ "Argentina",
        /*   IN-DD */ "Daman na Diu",
        /*   IN-DN */ "Dadra na Nagar Haveli",
        /*   IN-CH */ "Chandigarh",
        /*   IN-AN */ "Andaman and Nicobar",
        /*   IN-LD */ "Lakshadweep",
        /*   IN-DL */ "Delhi",
        /*   IN-ML */ "Meghalaya",
        /*   IN-NL */ "Nagaland",
        /*   IN-MN */ "Manipur",
        /*   IN-TR */ "Tripura",
        /*   IN-MZ */ "Mizoram",
        /*   IN-SK */ "Sikkim",
        /*   IN-PB */ "Punjab",
        /*   IN-HR */ "Haryana",
        /*   IN-AR */ "Arunachal Pradesh",
        /*   IN-AS */ "Assam",
        /*   IN-BR */ "Bihar",
        /*   IN-UT */ "Uttarakhand",
        /*   IN-GA */ "Goa",
        /*   IN-KL */ "Kerala",
        /*   IN-TN */ "Tamil Nadu",
        /*   IN-HP */ "Himachal Pradesh",
        /*   IN-JK */ "Jammu na Kashmir",
        /*   IN-CT */ "Chhattisgarh",
        /*   IN-JH */ "Jharkhand",
        /*   IN-KA */ "Karnataka",
        /*   IN-RJ */ "Rajasthan",
        /*   IN-OR */ "Odisha|Orissa",
        /*   IN-GJ */ "Gujarat",
        /*   IN-WB */ "West Bengal",
        /*   IN-MP */ "Madhya Pradesh",
        /*   IN-TG */ "Telangana",
        /*   IN-AP */ "Andhra Pradesh",
        /*   IN-MH */ "Maharashtra",
        /*   IN-UP */ "Uttar Pradesh",
        /*   IN-PY */ "Puducherry",
        /*     NSW */ "New South Wales",
        /*     ACT */ "Australian Capital Territory",
        /*     JBT */ "Jervis Bay Wapelestina",
        /*   AU-NT */ "Wilaya ya Kaskazini",
        /*   AU-SA */ "Australia Kusini",
        /*     TAS */ "Tasmania",
        /*     VIC */ "Victoria",
        /*   AU-WA */ "Australia ya Magharibi",
        /*     QLD */ "Queensland",
        /*   BR-DF */ "Distrito Federal",
        /*   BR-SE */ "Sergipe",
        /*   BR-AL */ "Alagoas",
        /*   BR-RJ */ "Rio de Janeiro",
        /*   BR-ES */ "Espirito Santo",
        /*   BR-RN */ "Rio Grande do Norte",
        /*   BR-PB */ "Paraiba",
        /*   BR-SC */ "Santa Catarina",
        /*   BR-PE */ "Pernambuco",
        /*   BR-AP */ "Amapa",
        /*   BR-CE */ "Ceara",
        /*   BR-AC */ "Acre",
        /*   BR-PR */ "Parana",
        /*   BR-RR */ "Roraima",
        /*   BR-RO */ "Rondonia",
        /*   BR-SP */ "Sao Paulo",
        /*   BR-PI */ "Piaui",
        /*   BR-TO */ "Tocantins",
        /*   BR-RS */ "Rio Grande do Sul",
        /*   BR-MA */ "Maranhao",
        /*   BR-GO */ "Goias",
        /*   BR-MS */ "Mato Grosso do Sul",
        /*   BR-BA */ "Bahia",
        /*   BR-MG */ "Minas Gerais",
        /*   BR-MT */ "Mato Grosso",
        /*   BR-PA */ "Para",
        /*   BR-AM */ "Amazonas",
        /*   US-DC */ "Wilaya ya Columbia",
        /*   US-RI */ "Rhode Island",
        /*   US-DE */ "Delaware",
        /*   US-CT */ "Connecticut",
        /*   US-NJ */ "New Jersey",
        /*   US-NH */ "New Hampshire",
        /*   US-VT */ "Vermont",
        /*   US-MA */ "Massachusetts",
        /*   US-HI */ "Hawaii",
        /*   US-MD */ "Maryland",
        /*   US-WV */ "West Virginia",
        /*   US-SC */ "South Carolina",
        /*   US-ME */ "Maine",
        /*   US-IN */ "Indiana",
        /*   US-KY */ "Kentucky",
        /*   US-TN */ "Tennessee",
        /*   US-VA */ "Virginia",
        /*   US-OH */ "Ohio",
        /*   US-PA */ "Pennsylvania",
        /*   US-MS */ "Mississippi",
        /*   US-LA */ "Louisiana",
        /*   US-AL */ "Alabama",
        /*   US-AR */ "Arkansas",
        /*   US-NC */ "North Carolina",
        /*   US-NY */ "New York",
        /*   US-IA */ "Iowa",
        /*   US-IL */ "Illinois",
        /*   US-GA */ "Georgia",
        /*   US-WI */ "Wisconsin",
        /*   US-FL */ "Florida",
        /*   US-MO */ "Missouri",
        /*   US-OK */ "Oklahoma",
        /*   US-ND */ "North Dakota",
        /*   US-WA */ "Washington",
        /*   US-SD */ "South Dakota",
        /*   US-NE */ "Nebraska",
        /*   US-KS */ "Kansas",
        /*   US-ID */ "Idaho",
        /*   US-UT */ "Utah",
        /*   US-MN */ "Minnesota",
        /*   US-MI */ "Michigan",
        /*   US-WY */ "Wyoming",
        /*   US-OR */ "Oregon",
        /*   US-CO */ "Colorado",
        /*   US-NV */ "Nevada",
        /*   US-AZ */ "Arizona",
        /*   US-NM */ "New Mexico",
        /*   US-MT */ "Montana",
        /*   US-CA */ "California",
        /*   US-TX */ "Texas",
        /*   US-AK */ "Alaska",
        /*   CA-BC */ "British Columbia",
        /*   CA-AB */ "Alberta",
        /*   CA-ON */ "Ontario",
        /*   CA-QC */ "Quebec",
        /*   CA-SK */ "Saskatchewan",
        /*   CA-MB */ "Manitoba",
        /*   CA-NL */ "Newfoundland",
        /*   CA-NB */ "New Brunswick",
        /*   CA-NS */ "Nova Scotia",
        /*   CA-PE */ "Prince Edward Island",
        /*   CA-YT */ "Yukon",
        /*   CA-NT */ "Northwest Territories",
        /*   CA-NU */ "Nunavut",
        /*     IND */ "India",
        /*     AUS */ "Australia",
        /*     BRA */ "Brazil",
        /*     USA */ "Marekani|United States of America|Amerika",
        /*     MEX */ "Mexico",
        /*     MOW */ "Moscow",
        /*     SPE */ "Saint Petersburg",
        /*     KGD */ "Kaliningrad Oblast",
        /*   RU-IN */ "Ingushetia Republic",
        /*   RU-AD */ "Adygea Jamhuri",
        /*   RU-SE */ "Ossetia ya Kaskazini-Alania Republic",
        /*   RU-KB */ "Kabardino-Balkar Jamhuri",
        /*   RU-KC */ "Karachay-Cherkess Jamhuri",
        /*   RU-CE */ "Chechen Jamhuri",
        /*   RU-CU */ "Chuvash Jamhuri",
        /*     IVA */ "Ivanovo Oblast",
        /*     LIP */ "Lipetsk Oblast",
        /*     ORL */ "Oryol Oblast",
        /*     TUL */ "Tula Oblast",
        /*   RU-BE */ "Belgorod Oblast",
        /*     VLA */ "Vladimir Oblast",
        /*     KRS */ "Kursk Oblast",
        /*     KLU */ "Kaluga Oblast",
        /*   RU-TT */ "Tambov Oblast",
        /*     BRY */ "Bryansk Oblast",
        /*     YAR */ "Yaroslavl Oblast",
        /*     RYA */ "Ryazan Oblast",
        /*     AST */ "Astrakhan Oblast",
        /*     MOS */ "Moscow Oblast",
        /*     SMO */ "Smolensk Oblast",
        /*   RU-DA */ "Dagestan Republic",
        /*     VOR */ "Voronezh Oblast",
        /*     NGR */ "Novgorod Oblast",
        /*     PSK */ "Pskov Oblast",
        /*     KOS */ "Kostroma Oblast",
        /*     STA */ "Stavropol Krai",
        /*     KDA */ "Krasnodar Krai",
        /*   RU-KL */ "Kalmykia Republic",
        /*     TVE */ "Tver Oblast",
        /*     LEN */ "Leningrad Oblast",
        /*     ROS */ "Rostov Oblast",
        /*     VGG */ "Volgograd Oblast",
        /*     VLG */ "Vologda Oblast",
        /*     MUR */ "Murmansk Oblast",
        /*   RU-KR */ "Karelia Republic",
        /*     NEN */ "Nenets Autonomous Okrug",
        /*   RU-KO */ "Komi Republic",
        /*     ARK */ "Arkhangelsk Oblast",
        /*   RU-MO */ "Mordovia Republic",
        /*     NIZ */ "Nizhny Novgorod Oblast",
        /*     PNZ */ "Penza Oblast",
        /*   RU-KI */ "Kirov Oblast",
        /*   RU-ME */ "Mari El Jamhuri",
        /*     ORE */ "Orenburg Oblast",
        /*     ULY */ "Ulyanovsk Oblast",
        /*   RU-PM */ "Perm Krai",
        /*   RU-BA */ "Bashkortostan Republic",
        /*   RU-UD */ "Udmurt Republic",
        /*   RU-TA */ "Tatarstan Republic",
        /*     SAM */ "Samara Oblast",
        /*     SAR */ "Saratov Oblast",
        /*     YAN */ "Yamalo-Nenets",
        /*   RU-KM */ "Khanty-Mansi",
        /*     SVE */ "Sverdlovsk Oblast",
        /*     TYU */ "Tyumen Oblast",
        /*     KGN */ "Kurgan Oblast",
        /*   RU-CH */ "Chelyabinsk Oblast",
        /*   RU-BU */ "Buryatia Republic",
        /*     ZAB */ "Zabaykalsky Krai",
        /*     IRK */ "Irkutsk Oblast",
        /*     NVS */ "Novosibirsk Oblast",
        /*     TOM */ "Tomsk Oblast",
        /*     OMS */ "Omsk Oblast",
        /*   RU-KK */ "Khakassia Jamhuri",
        /*     KEM */ "Kemerovo Oblast",
        /*   RU-AL */ "Altai Republic",
        /*     ALT */ "Altai Krai",
        /*   RU-TY */ "Tuva Jamhuri",
        /*     KYA */ "Krasnoyarsk Krai",
        /*     MAG */ "Magadani Oblast",
        /*     CHU */ "Chukotka Okrug",
        /*     KAM */ "Kamchatka Krai",
        /*     SAK */ "Sakhalin Oblast",
        /*   RU-PO */ "Primorsky Krai",
        /*     YEV */ "Jewish Autonomous Oblast",
        /*     KHA */ "Khabarovsk Krai",
        /*     AMU */ "Amur Oblast",
        /*   RU-SA */ "Sakha Republic|Yakutia Republic",
        /*     CAN */ "Canada",
        /*     RUS */ "Russia",
        /*   CN-SH */ "Shanghai",
        /*   CN-TJ */ "Tianjin",
        /*   CN-BJ */ "Beijing",
        /*   CN-HI */ "Hainan",
        /*   CN-NX */ "Ningxia Hui",
        /*   CN-CQ */ "Chongqing",
        /*   CN-ZJ */ "Zhejiang",
        /*   CN-JS */ "Jiangsu",
        /*   CN-FJ */ "Fujian",
        /*   CN-AH */ "Anhui",
        /*   CN-LN */ "Liaoning",
        /*   CN-SD */ "Shandong",
        /*   CN-SX */ "Shanxi",
        /*   CN-JX */ "Jiangxi",
        /*   CN-HA */ "Henan",
        /*   CN-GZ */ "Guizhou",
        /*   CN-GD */ "Guangdong",
        /*   CN-HB */ "Hubei",
        /*   CN-JL */ "Jilin",
        /*   CN-HE */ "Hebei",
        /*   CN-SN */ "Shaanxi",
        /*   CN-NM */ "Nei Mongol|Inner Mongolia",
        /*   CN-HL */ "Heilongjiang",
        /*   CN-HN */ "Hunan",
        /*   CN-GX */ "Guangxi Zhuang",
        /*   CN-SC */ "Sichuan",
        /*   CN-YN */ "Yunnan",
        /*   CN-XZ */ "Xizang|Tibet",
        /*   CN-GS */ "Gansu",
        /*   CN-QH */ "Qinghai",
        /*   CN-XJ */ "Xinjiang Uyghur",
        /*     CHN */ "China",
        /*     UMI */ "Marekani Ndogo Visiwa Outlying",
        /*     CPT */ "Clipperton Kisiwa",
        /*     ATA */ "Antarctica",
        /*     AAA */ "International|Dunia"
#else // MAPCODE_SUPPORT_LANGUAGE_SW
        NULL
#endif // MAPCODE_SUPPORT_LANGUAGE_SW
};

#ifdef __cplusplus
}
#endif

#endif // __INTERNAL_TERRITORY_NAMES_SW_H__
