/*
 * Copyright (C) 2014-2017 Stichting Mapcode Foundation (http://www.mapcode.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef __INTERNAL_TERRITORY_NAMES_NL_H__
#define __INTERNAL_TERRITORY_NAMES_NL_H__

#ifdef __cplusplus
extern "C" {
#endif

// *** GENERATED FILE (coords.cpp), DO NOT CHANGE OR PRETTIFY ***

static const char *TERRITORY_FULL_NAME_NL[] = {
#ifdef MAPCODE_SUPPORT_LANGUAGE_NL // Dutch
        /*     VAT */ "Vaticaanstad|Heilige Stoel",
        /*     MCO */ "Monaco",
        /*     GIB */ "Gibraltar",
        /*     TKL */ "Tokelau",
        /*     CCK */ "Cocos Eilanden|Keeling Islands",
        /*     BLM */ "Saint-Barthelemy",
        /*     NRU */ "Nauru",
        /*     TUV */ "Tuvalu",
        /*     MAC */ "Macau",
        /*     SXM */ "Sint Maarten",
        /*     MAF */ "Saint-Martin",
        /*     NFK */ "Norfolk en Philip Island|Philip Island",
        /*     PCN */ "Pitcairn Islands",
        /*     BVT */ "Bouvet Island",
        /*     BMU */ "Bermuda",
        /*     IOT */ "British Indian Ocean Territory",
        /*     SMR */ "San Marino",
        /*     GGY */ "Guernsey",
        /*     AIA */ "Anguilla",
        /*     MSR */ "Montserrat",
        /*     JEY */ "Jersey",
        /*     CXR */ "Christmas Island",
        /*     WLF */ "Wallis en Futuna|Futuna",
        /*     VGB */ "Britse Maagdeneilanden|Britse Maagdeneilanden",
        /*     LIE */ "Liechtenstein",
        /*     ABW */ "Aruba",
        /*     MHL */ "Marshall Eilanden",
        /*     ASM */ "Amerikaans Samoa|Samoa, Amerikaans",
        /*     COK */ "Cook eilanden",
        /*     SPM */ "Saint-Pierre en Miquelon|Miquelon",
        /*     NIU */ "Niue",
        /*     KNA */ "Saint Kitts en Nevis|Nevis",
        /*     CYM */ "Cayman eilanden",
        /*     BES */ "Bonaire, Sint Eustasuis en Saba|Saba|St Eustasius",
        /*     MDV */ "Malediven",
        /*     SHN */ "Sint-Helena, Ascension en Tristan da Cunha|Hemelvaart|Tristan da Cunha",
        /*     MLT */ "Malta",
        /*     GRD */ "Grenada",
        /*     VIR */ "Amerikaanse Maagdeneilanden|Maagdeneilanden, USA",
        /*     MYT */ "Mayotte",
        /*     SJM */ "Svalbard and Jan Mayen|Jan Mayen",
        /*     VCT */ "Saint Vincent en de Grenadines|Grenadines",
        /*     HMD */ "Heard Eiland en McDonald Eilanden|McDonald Islands",
        /*     BRB */ "Barbados",
        /*     ATG */ "Antigua en Barbuda|Barbuda",
        /*     CUW */ "Curaçao",
        /*     SYC */ "Seychellen",
        /*     PLW */ "Palau",
        /*     MNP */ "Northern Mariana Islands",
        /*     AND */ "Andorra",
        /*     GUM */ "Guam",
        /*     IMN */ "Isle of Man|Mann",
        /*     LCA */ "Saint Lucia",
        /*     FSM */ "Micronesia|Federated States of Micronesia",
        /*     SGP */ "Singapore",
        /*     TON */ "Tonga",
        /*     DMA */ "Dominica",
        /*     BHR */ "Bahrein",
        /*     KIR */ "Kiribati",
        /*     TCA */ "Turks-en Caicoseilanden|Caicoseilanden",
        /*     STP */ "Sao Tome en Principe|Principe",
        /*     HKG */ "Hong Kong",
        /*     MTQ */ "Martinique",
        /*     FRO */ "Faeröer",
        /*     GLP */ "Guadeloupe",
        /*     COM */ "Comoren",
        /*     MUS */ "Mauritius",
        /*     REU */ "Reunion",
        /*     LUX */ "Luxemburg",
        /*     WSM */ "Samoa",
        /*     SGS */ "Zuid-Georgië en de Zuidelijke Sandwicheilanden|Zuid-Sandwicheilanden",
        /*     PYF */ "Frans-Polynesië",
        /*     CPV */ "Kaapverdië",
        /*     TTO */ "Trinidad en Tobago|Tobago",
        /*     BRN */ "Brunei",
        /*     ATF */ "Franse Zuidelijke en Antarctische Gebieden",
        /*     PRI */ "Puerto Rico",
        /*     CYP */ "Cyprus",
        /*     LBN */ "Libanon",
        /*     JAM */ "Jamaica",
        /*     GMB */ "Gambia",
        /*     QAT */ "Qatar",
        /*     FLK */ "Falkland eilanden",
        /*     VUT */ "Vanuatu",
        /*     MNE */ "Montenegro",
        /*     BHS */ "Bahamas",
        /*     TLS */ "Oost-Timor",
        /*     SWZ */ "Swaziland",
        /*     KWT */ "Koeweit",
        /*     FJI */ "Fiji-eilanden",
        /*     NCL */ "New Caledonia",
        /*     SVN */ "Slovenië",
        /*     ISR */ "Israël",
        /*     PSE */ "Palestinian territory",
        /*     SLV */ "El Salvador",
        /*     BLZ */ "Belize",
        /*     DJI */ "Djibouti",
        /*     MKD */ "Macedonië",
        /*     RWA */ "Rwanda",
        /*     HTI */ "Haïti",
        /*     BDI */ "Burundi",
        /*     GNQ */ "Equatoriaal-Guinea",
        /*     ALB */ "Albanië",
        /*     SLB */ "Solomon eilanden",
        /*     ARM */ "Armenië",
        /*     LSO */ "Lesotho",
        /*     BEL */ "België",
        /*     MDA */ "Moldavië",
        /*     GNB */ "Guinee-Bissau",
        /*     TWN */ "Taiwan",
        /*     BTN */ "Bhutan",
        /*     CHE */ "Zwitserland",
        /*     NLD */ "Nederland",
        /*     DNK */ "Denemarken",
        /*     EST */ "Estland",
        /*     DOM */ "Dominicaanse Republiek",
        /*     SVK */ "Slowakije",
        /*     CRI */ "Costa Rica",
        /*     BIH */ "Bosnië en Herzegovina",
        /*     HRV */ "Kroatië",
        /*     TGO */ "Togo",
        /*     LVA */ "Letland",
        /*     LTU */ "Litouwen",
        /*     LKA */ "Sri Lanka",
        /*     GEO */ "Georgië",
        /*     IRL */ "Ierland",
        /*     SLE */ "Sierra Leone",
        /*     PAN */ "Panama",
        /*     CZE */ "Tsjechische Republiek",
        /*     GUF */ "Frans-Guyana",
        /*     ARE */ "Verenigde Arabische Emiraten",
        /*     AUT */ "Oostenrijk",
        /*     AZE */ "Azerbeidzjan",
        /*     SRB */ "Serbia",
        /*     JOR */ "Jordan",
        /*     PRT */ "Portugal",
        /*     HUN */ "Hongarije",
        /*     KOR */ "Zuid-Korea",
        /*     ISL */ "IJsland",
        /*     GTM */ "Guatemala",
        /*     CUB */ "Cuba",
        /*     BGR */ "Bulgarije",
        /*     LBR */ "Liberia",
        /*     HND */ "Honduras",
        /*     BEN */ "Benin",
        /*     ERI */ "Eritrea",
        /*     MWI */ "Malawi",
        /*     PRK */ "Noord-Korea",
        /*     NIC */ "Nicaragua",
        /*     GRC */ "Griekenland",
        /*     TJK */ "Tadzjikistan",
        /*     BGD */ "Bangladesh",
        /*     NPL */ "Nepal",
        /*     TUN */ "Tunesië",
        /*     SUR */ "Suriname",
        /*     URY */ "Uruguay",
        /*     KHM */ "Cambodja",
        /*     SYR */ "Syrië",
        /*     SEN */ "Senegal",
        /*     KGZ */ "Kirgizië",
        /*     BLR */ "Wit-Rusland",
        /*     GUY */ "Guyana",
        /*     LAO */ "Laos",
        /*     ROU */ "Roemenië",
        /*     GHA */ "Ghana",
        /*     UGA */ "Oeganda",
        /*     GBR */ "Verenigd Koninkrijk|Schotland|Groot Brittannië|Noord Ierland|Ierland, Noord",
        /*     GIN */ "Guinee",
        /*     ECU */ "Ecuador",
        /*     ESH */ "Western Sahara|Sahrawi",
        /*     GAB */ "Gabon",
        /*     NZL */ "Nieuw-Zeeland",
        /*     BFA */ "Burkina Faso",
        /*     PHL */ "Filippijnen",
        /*     ITA */ "Italië",
        /*     OMN */ "Oman",
        /*     POL */ "Polen",
        /*     CIV */ "Ivoorkust",
        /*     NOR */ "Noorwegen",
        /*     MYS */ "Maleisië",
        /*     VNM */ "Vietnam",
        /*     FIN */ "Finland",
        /*     COG */ "Congo-Brazzaville",
        /*     DEU */ "Duitsland",
        /*     JPN */ "Japan",
        /*     ZWE */ "Zimbabwe",
        /*     PRY */ "Paraguay",
        /*     IRQ */ "Irak",
        /*     MAR */ "Marokko",
        /*     UZB */ "Oezbekistan",
        /*     SWE */ "Zweden",
        /*     PNG */ "Papoea-Nieuw-Guinea",
        /*     CMR */ "Kameroen",
        /*     TKM */ "Turkmenistan",
        /*     ESP */ "Spanje",
        /*     THA */ "Thailand",
        /*     YEM */ "Jemen",
        /*     FRA */ "Frankrijk",
        /*     ALA */ "Aaland-eilanden",
        /*     KEN */ "Kenia",
        /*     BWA */ "Botswana",
        /*     MDG */ "Madagascar",
        /*     UKR */ "Oekraïne",
        /*     SSD */ "Zuid-Soedan",
        /*     CAF */ "Centraal-Afrikaanse Republiek",
        /*     SOM */ "Somalië",
        /*     AFG */ "Afghanistan",
        /*     MMR */ "Myanmar|Birma",
        /*     ZMB */ "Zambia",
        /*     CHL */ "Chili",
        /*     TUR */ "Turkije",
        /*     PAK */ "Pakistan",
        /*     MOZ */ "Mozambique",
        /*     NAM */ "Namibië",
        /*     VEN */ "Venezuela",
        /*     NGA */ "Nigeria",
        /*     TZA */ "Tanzania",
        /*     EGY */ "Egypte",
        /*     MRT */ "Mauritanië",
        /*     BOL */ "Bolivia",
        /*     ETH */ "Ethiopië",
        /*     COL */ "Colombia",
        /*     ZAF */ "Zuid-Afrika",
        /*     MLI */ "Mali",
        /*     AGO */ "Angola",
        /*     NER */ "Niger",
        /*     TCD */ "Tsjaad",
        /*     PER */ "Peru",
        /*     MNG */ "Mongolië",
        /*     IRN */ "Iran",
        /*     LBY */ "Libië",
        /*     SDN */ "Soedan",
        /*     IDN */ "Indonesië",
        /*     DIF */ "Federal District",
        /*     TLA */ "Tlaxcala",
        /*     MOR */ "Morelos",
        /*     AGU */ "Aguascalientes",
        /*   MX-CL */ "Colima",
        /*     QUE */ "Queretaro",
        /*     HID */ "Hidalgo",
        /*   MX-MX */ "Mexico State",
        /*     TAB */ "Tabasco",
        /*     NAY */ "Nayarit",
        /*     GUA */ "Guanajuato",
        /*     PUE */ "Puebla",
        /*     YUC */ "Yucatan",
        /*     ROO */ "Quintana Roo",
        /*     SIN */ "Sinaloa",
        /*     CAM */ "Campeche",
        /*     MIC */ "Michoacan",
        /*     SLP */ "San Luis Potosi",
        /*     GRO */ "Guerrero",
        /*     NLE */ "Nuevo Leon",
        /*     BCN */ "Baja California",
        /*     VER */ "Veracruz",
        /*     CHP */ "Chiapas",
        /*     BCS */ "Baja California Sur",
        /*     ZAC */ "Zacatecas",
        /*     JAL */ "Jalisco",
        /*     TAM */ "Tamaulipas",
        /*     OAX */ "Oaxaca",
        /*     DUR */ "Durango",
        /*     COA */ "Coahuila",
        /*     SON */ "Sonora",
        /*     CHH */ "Chihuahua",
        /*     GRL */ "Groenland",
        /*     SAU */ "Saudi-Arabië",
        /*     COD */ "Congo-Kinshasa",
        /*     DZA */ "Algerije",
        /*     KAZ */ "Kazachstan",
        /*     ARG */ "Argentinië",
        /*   IN-DD */ "Daman en Diu",
        /*   IN-DN */ "Dadra en Nagar Haveli",
        /*   IN-CH */ "Chandigarh",
        /*   IN-AN */ "Andaman en Nicobar",
        /*   IN-LD */ "Lakshadweep",
        /*   IN-DL */ "Delhi",
        /*   IN-ML */ "Meghalaya",
        /*   IN-NL */ "Nagaland",
        /*   IN-MN */ "Manipur",
        /*   IN-TR */ "Tripura",
        /*   IN-MZ */ "Mizoram",
        /*   IN-SK */ "Sikkim",
        /*   IN-PB */ "Punjab",
        /*   IN-HR */ "Haryana",
        /*   IN-AR */ "Arunachal Pradesh",
        /*   IN-AS */ "Assam",
        /*   IN-BR */ "Bihar",
        /*   IN-UT */ "Uttarakhand",
        /*   IN-GA */ "Goa",
        /*   IN-KL */ "Kerala",
        /*   IN-TN */ "Tamil Nadu",
        /*   IN-HP */ "Himachal Pradesh",
        /*   IN-JK */ "Jammu en Kasjmir",
        /*   IN-CT */ "Chhattisgarh",
        /*   IN-JH */ "Jharkhand",
        /*   IN-KA */ "Karnataka",
        /*   IN-RJ */ "Rajasthan",
        /*   IN-OR */ "Odisha|Orissa",
        /*   IN-GJ */ "Gujarat",
        /*   IN-WB */ "West-Bengalen",
        /*   IN-MP */ "Madhya Pradesh",
        /*   IN-TG */ "Telangana",
        /*   IN-AP */ "Andhra Pradesh",
        /*   IN-MH */ "Maharashtra",
        /*   IN-UP */ "Uttar Pradesh",
        /*   IN-PY */ "Puducherry",
        /*     NSW */ "New South Wales",
        /*     ACT */ "Australian Capital Territory",
        /*     JBT */ "Jervis Bay Territorium",
        /*   AU-NT */ "Northern Territory",
        /*   AU-SA */ "South Australia",
        /*     TAS */ "Tasmanië",
        /*     VIC */ "Victoria",
        /*   AU-WA */ "West-Australië",
        /*     QLD */ "Queensland",
        /*   BR-DF */ "Distrito Federal",
        /*   BR-SE */ "Sergipe",
        /*   BR-AL */ "Alagoas",
        /*   BR-RJ */ "Rio de Janeiro",
        /*   BR-ES */ "Espirito Santo",
        /*   BR-RN */ "Rio Grande do Norte",
        /*   BR-PB */ "Paraiba",
        /*   BR-SC */ "Santa Catarina",
        /*   BR-PE */ "Pernambuco",
        /*   BR-AP */ "Amapá",
        /*   BR-CE */ "Ceara",
        /*   BR-AC */ "Acre",
        /*   BR-PR */ "Parana",
        /*   BR-RR */ "Roraima",
        /*   BR-RO */ "Rondonia",
        /*   BR-SP */ "Sao Paulo",
        /*   BR-PI */ "Piaui",
        /*   BR-TO */ "Tocantins",
        /*   BR-RS */ "Rio Grande do Sul",
        /*   BR-MA */ "Maranhao",
        /*   BR-GO */ "Goias",
        /*   BR-MS */ "Mato Grosso do Sul",
        /*   BR-BA */ "Bahia",
        /*   BR-MG */ "Minas Gerais",
        /*   BR-MT */ "Mato Grosso",
        /*   BR-PA */ "Para",
        /*   BR-AM */ "Amazonas",
        /*   US-DC */ "District of Columbia",
        /*   US-RI */ "Rhode Island",
        /*   US-DE */ "Delaware",
        /*   US-CT */ "Connecticut",
        /*   US-NJ */ "New Jersey",
        /*   US-NH */ "New Hampshire",
        /*   US-VT */ "Vermont",
        /*   US-MA */ "Massachusetts",
        /*   US-HI */ "Hawaï",
        /*   US-MD */ "Maryland",
        /*   US-WV */ "West Virginia",
        /*   US-SC */ "South Carolina",
        /*   US-ME */ "Maine",
        /*   US-IN */ "Indiana",
        /*   US-KY */ "Kentucky",
        /*   US-TN */ "Tennessee",
        /*   US-VA */ "Virginia",
        /*   US-OH */ "Ohio",
        /*   US-PA */ "Pennsylvania",
        /*   US-MS */ "Mississippi",
        /*   US-LA */ "Louisiana",
        /*   US-AL */ "Alabama",
        /*   US-AR */ "Arkansas",
        /*   US-NC */ "North Carolina",
        /*   US-NY */ "New York",
        /*   US-IA */ "Iowa",
        /*   US-IL */ "Illinois",
        /*   US-GA */ "Georgia",
        /*   US-WI */ "Wisconsin",
        /*   US-FL */ "Florida",
        /*   US-MO */ "Missouri",
        /*   US-OK */ "Oklahoma",
        /*   US-ND */ "North Dakota",
        /*   US-WA */ "Washington",
        /*   US-SD */ "South Dakota",
        /*   US-NE */ "Nebraska",
        /*   US-KS */ "Kansas",
        /*   US-ID */ "Idaho",
        /*   US-UT */ "Utah",
        /*   US-MN */ "Minnesota",
        /*   US-MI */ "Michigan",
        /*   US-WY */ "Wyoming",
        /*   US-OR */ "Oregon",
        /*   US-CO */ "Colorado",
        /*   US-NV */ "Nevada",
        /*   US-AZ */ "Arizona",
        /*   US-NM */ "New Mexico",
        /*   US-MT */ "Montana",
        /*   US-CA */ "Californië",
        /*   US-TX */ "Texas",
        /*   US-AK */ "Alaska",
        /*   CA-BC */ "British Columbia",
        /*   CA-AB */ "Alberta",
        /*   CA-ON */ "Ontario",
        /*   CA-QC */ "Quebec",
        /*   CA-SK */ "Saskatchewan",
        /*   CA-MB */ "Manitoba",
        /*   CA-NL */ "Newfoundland",
        /*   CA-NB */ "New Brunswick",
        /*   CA-NS */ "Nova Scotia",
        /*   CA-PE */ "Prince Edward Island",
        /*   CA-YT */ "Yukon",
        /*   CA-NT */ "Northwest Territories",
        /*   CA-NU */ "Nunavut",
        /*     IND */ "India",
        /*     AUS */ "Australië",
        /*     BRA */ "Brazilië",
        /*     USA */ "VS|Verenigde Staten|Amerika",
        /*     MEX */ "Mexico",
        /*     MOW */ "Moskou",
        /*     SPE */ "Sint-Petersburg",
        /*     KGD */ "Kaliningrad Oblast",
        /*   RU-IN */ "Ingoesjetië Republiek",
        /*   RU-AD */ "Adygea Republiek",
        /*   RU-SE */ "Noord-Ossetië-Alania Republiek",
        /*   RU-KB */ "Kabardino-Balkar Republiek",
        /*   RU-KC */ "Karachay-Cherkess Republiek",
        /*   RU-CE */ "Tsjetsjeense Republiek",
        /*   RU-CU */ "Chuvash Republiek",
        /*     IVA */ "Ivanovo Oblast",
        /*     LIP */ "Lipetsk",
        /*     ORL */ "Oryol Oblast",
        /*     TUL */ "Tula Oblast",
        /*   RU-BE */ "Belgorod Oblast",
        /*     VLA */ "Vladimir Oblast",
        /*     KRS */ "Kursk Oblast",
        /*     KLU */ "Kaluga Oblast",
        /*   RU-TT */ "Tambov Oblast",
        /*     BRY */ "Bryansk Oblast",
        /*     YAR */ "Yaroslavl Oblast",
        /*     RYA */ "Ryazan Oblast",
        /*     AST */ "Astrakhan Oblast",
        /*     MOS */ "Moskou Oblast",
        /*     SMO */ "Smolensk Oblast",
        /*   RU-DA */ "Dagestan Republiek",
        /*     VOR */ "Voronezh Oblast",
        /*     NGR */ "Novgorod Oblast",
        /*     PSK */ "Pskov Oblast",
        /*     KOS */ "Kostroma Oblast",
        /*     STA */ "Stavropol Krai",
        /*     KDA */ "Krasnodar Krai",
        /*   RU-KL */ "Kalmukkië Republiek",
        /*     TVE */ "Tver Oblast",
        /*     LEN */ "Leningrad Oblast",
        /*     ROS */ "Rostov Oblast",
        /*     VGG */ "Volgograd Oblast",
        /*     VLG */ "Vologda Oblast",
        /*     MUR */ "Murmansk Oblast",
        /*   RU-KR */ "Karelia Republiek",
        /*     NEN */ "Nenets Autonome Okrug",
        /*   RU-KO */ "Komi Republic",
        /*     ARK */ "Arkhangelsk Oblast",
        /*   RU-MO */ "Mordovië Republiek",
        /*     NIZ */ "Nizhny Novgorod Oblast",
        /*     PNZ */ "Penza Oblast",
        /*   RU-KI */ "Kirov Oblast",
        /*   RU-ME */ "Republiek Mari El",
        /*     ORE */ "Orenburg Oblast",
        /*     ULY */ "Ulyanovsk Oblast",
        /*   RU-PM */ "Perm Krai",
        /*   RU-BA */ "Bashkortostan Republiek",
        /*   RU-UD */ "Udmurt Republic",
        /*   RU-TA */ "Tatarstan Republiek",
        /*     SAM */ "Samara Oblast",
        /*     SAR */ "Saratov Oblast",
        /*     YAN */ "Yamalo-Nenets",
        /*   RU-KM */ "Khanty-Mansi",
        /*     SVE */ "Sverdlovsk Oblast",
        /*     TYU */ "Tyumen Oblast",
        /*     KGN */ "Kurgan Oblast",
        /*   RU-CH */ "Chelyabinsk Oblast",
        /*   RU-BU */ "Buryatia Republic",
        /*     ZAB */ "Zabaykalsky Krai",
        /*     IRK */ "Irkoetsk Oblast",
        /*     NVS */ "Novosibirsk Oblast",
        /*     TOM */ "Tomsk Oblast",
        /*     OMS */ "Omsk Oblast",
        /*   RU-KK */ "Khakassia Republiek",
        /*     KEM */ "Kemerovo Oblast",
        /*   RU-AL */ "Altai Republiek",
        /*     ALT */ "Altai Krai",
        /*   RU-TY */ "Tuva Republiek",
        /*     KYA */ "Krasnoyarsk Krai",
        /*     MAG */ "Magadan Oblast",
        /*     CHU */ "Chukotka Okrug",
        /*     KAM */ "Kamchatka Krai",
        /*     SAK */ "Sakhalin Oblast",
        /*   RU-PO */ "Primorsky Krai",
        /*     YEV */ "Joodse Autonome Oblast",
        /*     KHA */ "Khabarovsk Krai",
        /*     AMU */ "Amur Oblast",
        /*   RU-SA */ "Sakha Republiek|Yakutia Republic",
        /*     CAN */ "Canada",
        /*     RUS */ "Rusland",
        /*   CN-SH */ "Sjanghai",
        /*   CN-TJ */ "Tianjin",
        /*   CN-BJ */ "Beijing",
        /*   CN-HI */ "Hainan",
        /*   CN-NX */ "Ningxia Hui",
        /*   CN-CQ */ "Chongqing",
        /*   CN-ZJ */ "Zhejiang",
        /*   CN-JS */ "Jiangsu",
        /*   CN-FJ */ "Fujian",
        /*   CN-AH */ "Anhui",
        /*   CN-LN */ "Liaoning",
        /*   CN-SD */ "Shandong",
        /*   CN-SX */ "Shanxi",
        /*   CN-JX */ "Jiangxi",
        /*   CN-HA */ "Henan",
        /*   CN-GZ */ "Guizhou",
        /*   CN-GD */ "Guangdong",
        /*   CN-HB */ "Hubei",
        /*   CN-JL */ "Jilin",
        /*   CN-HE */ "Hebei",
        /*   CN-SN */ "Shaanxi",
        /*   CN-NM */ "Nei Mongol|Inner Mongolia",
        /*   CN-HL */ "Heilongjiang",
        /*   CN-HN */ "Hunan",
        /*   CN-GX */ "Guangxi Zhuang",
        /*   CN-SC */ "Sichuan",
        /*   CN-YN */ "Yunnan",
        /*   CN-XZ */ "Xizang|Tibet",
        /*   CN-GS */ "Gansu",
        /*   CN-QH */ "Qinghai",
        /*   CN-XJ */ "Xinjiang Oeigoerse",
        /*     CHN */ "China",
        /*     UMI */ "United States Minor Outlying Islands",
        /*     CPT */ "Clipperton Island",
        /*     ATA */ "Antarctica",
        /*     AAA */ "Internationaal|Wereldwijd|Aarde"
#else // MAPCODE_SUPPORT_LANGUAGE_NL
        NULL
#endif // MAPCODE_SUPPORT_LANGUAGE_NL
};

#ifdef __cplusplus
}
#endif

#endif // __INTERNAL_TERRITORY_NAMES_NL_H__
