/*
 * Copyright (C) 2014-2017 Stichting Mapcode Foundation (http://www.mapcode.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef __INTERNAL_TERRITORY_NAMES_IT_H__
#define __INTERNAL_TERRITORY_NAMES_IT_H__

#ifdef __cplusplus
extern "C" {
#endif

// *** GENERATED FILE (coords.cpp), DO NOT CHANGE OR PRETTIFY ***

static const char *TERRITORY_FULL_NAME_IT[] = {
#ifdef MAPCODE_SUPPORT_LANGUAGE_IT // Italian
        /*     VAT */ "Vaticano|Città del Vaticano|Santa Sede",
        /*     MCO */ "Monaco",
        /*     GIB */ "Gibilterra",
        /*     TKL */ "Tokelau",
        /*     CCK */ "Isole Cocos|Isole Keeling",
        /*     BLM */ "Saint-Barthelemy",
        /*     NRU */ "Nauru",
        /*     TUV */ "Tuvalu",
        /*     MAC */ "Macau",
        /*     SXM */ "Sint Maarten",
        /*     MAF */ "Saint-Martin",
        /*     NFK */ "Norfolk e Phillip Island|Phillip Island",
        /*     PCN */ "Isole Pitcairn",
        /*     BVT */ "Isola Bouvet",
        /*     BMU */ "Bermuda",
        /*     IOT */ "Territorio Britannico dell`Oceano Indiano",
        /*     SMR */ "San Marino",
        /*     GGY */ "Guernsey",
        /*     AIA */ "Anguilla",
        /*     MSR */ "Montserrat",
        /*     JEY */ "Jersey",
        /*     CXR */ "Isola di Natale",
        /*     WLF */ "Wallis e Futuna|Futuna",
        /*     VGB */ "Isole Vergini Britanniche",
        /*     LIE */ "Liechtenstein",
        /*     ABW */ "Aruba",
        /*     MHL */ "Isole Marshall",
        /*     ASM */ "Samoa Americane",
        /*     COK */ "Isole Cook",
        /*     SPM */ "Saint Pierre e Miquelon|Miquelon",
        /*     NIU */ "Niue",
        /*     KNA */ "Saint Kitts e Nevis|Nevis",
        /*     CYM */ "Isole Cayman",
        /*     BES */ "Bonaire, St Eustatuis e Saba|Saba|St Eustatius",
        /*     MDV */ "Maldive",
        /*     SHN */ "Sant`Elena, Ascensione e Tristan da Cunha|Ascensione|Tristan da Cunha",
        /*     MLT */ "Malta",
        /*     GRD */ "Grenada",
        /*     VIR */ "US Virgin Islands|Isole Vergini, USA",
        /*     MYT */ "Mayotte",
        /*     SJM */ "Svalbard e Jan Mayen|Jan Mayen",
        /*     VCT */ "Saint Vincent e Grenadine|Grenadine",
        /*     HMD */ "Isole Heard e McDonald|Isole McDonald",
        /*     BRB */ "Barbados",
        /*     ATG */ "Antigua e Barbuda|Barbuda",
        /*     CUW */ "Curacao",
        /*     SYC */ "Seychelles",
        /*     PLW */ "Palau",
        /*     MNP */ "Isole Marianne settentrionali",
        /*     AND */ "Andorra",
        /*     GUM */ "Guam",
        /*     IMN */ "Isola di Man",
        /*     LCA */ "Santa Lucia",
        /*     FSM */ "Micronesia|Stati Federati di Micronesia",
        /*     SGP */ "Singapore",
        /*     TON */ "Tonga",
        /*     DMA */ "Dominica",
        /*     BHR */ "Bahrain",
        /*     KIR */ "Kiribati",
        /*     TCA */ "Turks e Caicos|Caicos",
        /*     STP */ "Sao Tome e Principe|Principe",
        /*     HKG */ "Hong Kong",
        /*     MTQ */ "Martinica",
        /*     FRO */ "Isole Faroe",
        /*     GLP */ "Guadeloupe",
        /*     COM */ "Comore",
        /*     MUS */ "Mauritius",
        /*     REU */ "Reunion",
        /*     LUX */ "Lussemburgo",
        /*     WSM */ "Samoa",
        /*     SGS */ "Georgia del Sud e isole Sandwich del Sud|Isole Sandwich Meridionali",
        /*     PYF */ "Polinesia francese",
        /*     CPV */ "Capo Verde",
        /*     TTO */ "Trinidad e Tobago|Tobago",
        /*     BRN */ "Brunei",
        /*     ATF */ "Terre australi e antartiche francesi",
        /*     PRI */ "Puerto Rico",
        /*     CYP */ "Cipro",
        /*     LBN */ "Libano",
        /*     JAM */ "Giamaica",
        /*     GMB */ "Gambia",
        /*     QAT */ "Qatar",
        /*     FLK */ "Isole Falkland",
        /*     VUT */ "Vanuatu",
        /*     MNE */ "Montenegro",
        /*     BHS */ "Bahamas",
        /*     TLS */ "Timor Est",
        /*     SWZ */ "Swaziland",
        /*     KWT */ "Kuwait",
        /*     FJI */ "Isole Figi",
        /*     NCL */ "Nuova Caledonia",
        /*     SVN */ "Slovenia",
        /*     ISR */ "Israele",
        /*     PSE */ "Territorio Palestinese",
        /*     SLV */ "El Salvador",
        /*     BLZ */ "Belize",
        /*     DJI */ "Djibouti",
        /*     MKD */ "Macedonia",
        /*     RWA */ "Ruanda",
        /*     HTI */ "Haiti",
        /*     BDI */ "Burundi",
        /*     GNQ */ "Guinea Equatoriale",
        /*     ALB */ "Albania",
        /*     SLB */ "Isole Salomone",
        /*     ARM */ "Armenia",
        /*     LSO */ "Lesoto",
        /*     BEL */ "Belgio",
        /*     MDA */ "Moldova",
        /*     GNB */ "Guinea-Bissau",
        /*     TWN */ "Taiwan",
        /*     BTN */ "Bhutan",
        /*     CHE */ "Svizzera",
        /*     NLD */ "Olanda",
        /*     DNK */ "Danimarca",
        /*     EST */ "Estonia",
        /*     DOM */ "Repubblica Dominicana",
        /*     SVK */ "Slovacchia",
        /*     CRI */ "Costa Rica",
        /*     BIH */ "Bosnia-Erzegovina",
        /*     HRV */ "Croazia",
        /*     TGO */ "Togo",
        /*     LVA */ "Lettonia",
        /*     LTU */ "Lituania",
        /*     LKA */ "Sri Lanka",
        /*     GEO */ "Georgia",
        /*     IRL */ "Irlanda",
        /*     SLE */ "Sierra Leone",
        /*     PAN */ "Panama",
        /*     CZE */ "Repubblica Ceca",
        /*     GUF */ "Guiana francese",
        /*     ARE */ "Emirati Arabi Uniti",
        /*     AUT */ "Austria",
        /*     AZE */ "Azerbaijan",
        /*     SRB */ "Serbia",
        /*     JOR */ "Giordania",
        /*     PRT */ "Portogallo",
        /*     HUN */ "Ungheria",
        /*     KOR */ "Corea del Sud",
        /*     ISL */ "Islanda",
        /*     GTM */ "Guatemala",
        /*     CUB */ "Cuba",
        /*     BGR */ "Bulgaria",
        /*     LBR */ "Liberia",
        /*     HND */ "Honduras",
        /*     BEN */ "Benin",
        /*     ERI */ "L`Eritrea",
        /*     MWI */ "Malawi",
        /*     PRK */ "Corea del nord",
        /*     NIC */ "Nicaragua",
        /*     GRC */ "Grecia",
        /*     TJK */ "Tajikistan",
        /*     BGD */ "Bangladesh",
        /*     NPL */ "Nepal",
        /*     TUN */ "Tunisia",
        /*     SUR */ "Suriname",
        /*     URY */ "Uruguay",
        /*     KHM */ "Cambogia",
        /*     SYR */ "Siria",
        /*     SEN */ "Senegal",
        /*     KGZ */ "Kyrgyzstan",
        /*     BLR */ "Bielorussia",
        /*     GUY */ "Guyana",
        /*     LAO */ "Laos",
        /*     ROU */ "Romania",
        /*     GHA */ "Ghana",
        /*     UGA */ "Uganda",
        /*     GBR */ "Regno Unito|Scozia|Gran Bretagna|Irlanda del Nord|Irlanda, del Nord",
        /*     GIN */ "Guinea",
        /*     ECU */ "Ecuador",
        /*     ESH */ "Sahara occidentale|Saharawi",
        /*     GAB */ "Gabon",
        /*     NZL */ "Nuova Zelanda",
        /*     BFA */ "Burkina Faso",
        /*     PHL */ "Filippine",
        /*     ITA */ "Italia",
        /*     OMN */ "Oman",
        /*     POL */ "Polonia",
        /*     CIV */ "Costa d`Avorio",
        /*     NOR */ "Norvegia",
        /*     MYS */ "Malaysia",
        /*     VNM */ "Vietnam",
        /*     FIN */ "Finlandia",
        /*     COG */ "Congo-Brazzaville",
        /*     DEU */ "Germania",
        /*     JPN */ "Giappone",
        /*     ZWE */ "Zimbabwe",
        /*     PRY */ "Paraguay",
        /*     IRQ */ "Iraq",
        /*     MAR */ "Marocco",
        /*     UZB */ "Uzbekistan",
        /*     SWE */ "Svezia",
        /*     PNG */ "Papua Nuova Guinea",
        /*     CMR */ "Camerun",
        /*     TKM */ "Turkmenistan",
        /*     ESP */ "Spagna",
        /*     THA */ "Tailandia",
        /*     YEM */ "Yemen",
        /*     FRA */ "Francia",
        /*     ALA */ "Isole Åland",
        /*     KEN */ "Kenia",
        /*     BWA */ "Botswana",
        /*     MDG */ "Madagascar",
        /*     UKR */ "Ucraina",
        /*     SSD */ "Sudan del Sud",
        /*     CAF */ "Repubblica Centrafricana",
        /*     SOM */ "Somalia",
        /*     AFG */ "afghanistan",
        /*     MMR */ "Myanmar|Birmania",
        /*     ZMB */ "Zambia",
        /*     CHL */ "Chile",
        /*     TUR */ "Turchia",
        /*     PAK */ "Pakistan",
        /*     MOZ */ "Mozambico",
        /*     NAM */ "Namibia",
        /*     VEN */ "Venezuela",
        /*     NGA */ "Nigeria",
        /*     TZA */ "Tanzania",
        /*     EGY */ "Egitto",
        /*     MRT */ "Mauritania",
        /*     BOL */ "Bolivia",
        /*     ETH */ "Etiopia",
        /*     COL */ "Colombia",
        /*     ZAF */ "Sud Africa",
        /*     MLI */ "Mali",
        /*     AGO */ "Angola",
        /*     NER */ "Niger",
        /*     TCD */ "Chad",
        /*     PER */ "Perù",
        /*     MNG */ "Mongolia",
        /*     IRN */ "Iran",
        /*     LBY */ "Libia",
        /*     SDN */ "Sudan",
        /*     IDN */ "Indonesia",
        /*     DIF */ "Distretto Federale",
        /*     TLA */ "Tlaxcala",
        /*     MOR */ "Morelos",
        /*     AGU */ "Aguascalientes",
        /*   MX-CL */ "Colima",
        /*     QUE */ "Queretaro",
        /*     HID */ "Hidalgo",
        /*   MX-MX */ "Stato del Messico",
        /*     TAB */ "Tabasco",
        /*     NAY */ "Nayarit",
        /*     GUA */ "Guanajuato",
        /*     PUE */ "Puebla",
        /*     YUC */ "Yucatan",
        /*     ROO */ "Quintana Roo",
        /*     SIN */ "Sinaloa",
        /*     CAM */ "Campeche",
        /*     MIC */ "Michoacan",
        /*     SLP */ "San Luis Potosi",
        /*     GRO */ "Guerrero",
        /*     NLE */ "Nuevo Leon",
        /*     BCN */ "Bassa California",
        /*     VER */ "Veracruz",
        /*     CHP */ "Chiapas",
        /*     BCS */ "Bassa California del Sud",
        /*     ZAC */ "Zacatecas",
        /*     JAL */ "Jalisco",
        /*     TAM */ "Tamaulipas",
        /*     OAX */ "Oaxaca",
        /*     DUR */ "Durango",
        /*     COA */ "Coahuila",
        /*     SON */ "Sonora",
        /*     CHH */ "Chihuahua",
        /*     GRL */ "Groenlandia",
        /*     SAU */ "Arabia Saudita",
        /*     COD */ "Congo-Kinshasa",
        /*     DZA */ "Algeria",
        /*     KAZ */ "Kazakhstan",
        /*     ARG */ "Argentina",
        /*   IN-DD */ "Daman and Diu",
        /*   IN-DN */ "Dadra e Nagar Haveli",
        /*   IN-CH */ "Chandigarh",
        /*   IN-AN */ "Andamane e Nicobar",
        /*   IN-LD */ "Lakshadweep|Laccadive",
        /*   IN-DL */ "Delhi",
        /*   IN-ML */ "Meghalaya",
        /*   IN-NL */ "Nagaland",
        /*   IN-MN */ "Manipur",
        /*   IN-TR */ "Tripura",
        /*   IN-MZ */ "Mizoram",
        /*   IN-SK */ "Sikkim",
        /*   IN-PB */ "Punjab",
        /*   IN-HR */ "Haryana",
        /*   IN-AR */ "Arunachal Pradesh",
        /*   IN-AS */ "Assam",
        /*   IN-BR */ "Bihar",
        /*   IN-UT */ "Uttarakhand",
        /*   IN-GA */ "Goa",
        /*   IN-KL */ "Kerala",
        /*   IN-TN */ "Tamil Nadu",
        /*   IN-HP */ "Himachal Pradesh",
        /*   IN-JK */ "Jammu e Kashmir",
        /*   IN-CT */ "Chhattisgarh",
        /*   IN-JH */ "Jharkhand",
        /*   IN-KA */ "Karnataka",
        /*   IN-RJ */ "Rajasthan",
        /*   IN-OR */ "Odisha|Orissa",
        /*   IN-GJ */ "Gujarat",
        /*   IN-WB */ "West Bengal",
        /*   IN-MP */ "Madhya Pradesh",
        /*   IN-TG */ "Telangana",
        /*   IN-AP */ "Andhra Pradesh",
        /*   IN-MH */ "Maharashtra",
        /*   IN-UP */ "Uttar Pradesh",
        /*   IN-PY */ "Puducherry",
        /*     NSW */ "Nuovo Galles del Sud",
        /*     ACT */ "Australian Capital Territory",
        /*     JBT */ "Jervis Bay Territorio",
        /*   AU-NT */ "Territori del Nord",
        /*   AU-SA */ "Australia del sud",
        /*     TAS */ "Tasmania",
        /*     VIC */ "Vittoria",
        /*   AU-WA */ "Australia Occidentale",
        /*     QLD */ "Queensland",
        /*   BR-DF */ "Distrito Federal",
        /*   BR-SE */ "Sergipe",
        /*   BR-AL */ "Alagoas",
        /*   BR-RJ */ "Rio de Janeiro",
        /*   BR-ES */ "Espirito Santo",
        /*   BR-RN */ "Rio Grande do Norte",
        /*   BR-PB */ "Paraiba",
        /*   BR-SC */ "Santa Catarina",
        /*   BR-PE */ "Pernambuco",
        /*   BR-AP */ "Amapa",
        /*   BR-CE */ "Ceara",
        /*   BR-AC */ "Acre",
        /*   BR-PR */ "Parana",
        /*   BR-RR */ "Roraima",
        /*   BR-RO */ "Rondonia",
        /*   BR-SP */ "San Paolo",
        /*   BR-PI */ "Piaui",
        /*   BR-TO */ "Tocantins",
        /*   BR-RS */ "Rio Grande do Sul",
        /*   BR-MA */ "Maranhao",
        /*   BR-GO */ "Goias",
        /*   BR-MS */ "Mato Grosso do Sul",
        /*   BR-BA */ "Bahia",
        /*   BR-MG */ "Minas Gerais",
        /*   BR-MT */ "Mato Grosso",
        /*   BR-PA */ "Parà",
        /*   BR-AM */ "Amazonas",
        /*   US-DC */ "Distretto della Colombia",
        /*   US-RI */ "Rhode Island",
        /*   US-DE */ "Delaware",
        /*   US-CT */ "Connecticut",
        /*   US-NJ */ "New Jersey",
        /*   US-NH */ "New Hampshire",
        /*   US-VT */ "Vermont",
        /*   US-MA */ "Massachusetts",
        /*   US-HI */ "Hawaii",
        /*   US-MD */ "Maryland",
        /*   US-WV */ "Virginia Occidentale",
        /*   US-SC */ "Carolina del Sud",
        /*   US-ME */ "Maine",
        /*   US-IN */ "Indiana",
        /*   US-KY */ "Kentucky",
        /*   US-TN */ "Tennessee",
        /*   US-VA */ "Virginia",
        /*   US-OH */ "Ohio",
        /*   US-PA */ "Pennsylvania",
        /*   US-MS */ "Mississippi",
        /*   US-LA */ "Louisiana",
        /*   US-AL */ "Alabama",
        /*   US-AR */ "Arkansas",
        /*   US-NC */ "Carolina del Nord",
        /*   US-NY */ "New York",
        /*   US-IA */ "Iowa",
        /*   US-IL */ "Illinois",
        /*   US-GA */ "Georgia",
        /*   US-WI */ "Wisconsin",
        /*   US-FL */ "Florida",
        /*   US-MO */ "Missouri",
        /*   US-OK */ "Oklahoma",
        /*   US-ND */ "Dakota del Nord",
        /*   US-WA */ "Washington",
        /*   US-SD */ "Dakota del Sud",
        /*   US-NE */ "Nebraska",
        /*   US-KS */ "Kansas",
        /*   US-ID */ "Idaho",
        /*   US-UT */ "Utah",
        /*   US-MN */ "Minnesota",
        /*   US-MI */ "Michigan",
        /*   US-WY */ "Wyoming",
        /*   US-OR */ "Oregon",
        /*   US-CO */ "Colorado",
        /*   US-NV */ "Nevada",
        /*   US-AZ */ "Arizona",
        /*   US-NM */ "Nuovo Messico",
        /*   US-MT */ "Montana",
        /*   US-CA */ "California",
        /*   US-TX */ "Texas",
        /*   US-AK */ "Alaska",
        /*   CA-BC */ "British Columbia",
        /*   CA-AB */ "Alberta",
        /*   CA-ON */ "Ontario",
        /*   CA-QC */ "Quebec",
        /*   CA-SK */ "Saskatchewan",
        /*   CA-MB */ "Manitoba",
        /*   CA-NL */ "Terranova",
        /*   CA-NB */ "New Brunswick|Nuovo Brunswick",
        /*   CA-NS */ "Nuova Scozia",
        /*   CA-PE */ "Isola del Principe Edoardo",
        /*   CA-YT */ "Yukon",
        /*   CA-NT */ "Territori del Nordovest",
        /*   CA-NU */ "Nunavut",
        /*     IND */ "India",
        /*     AUS */ "Australia",
        /*     BRA */ "Brasile",
        /*     USA */ "USA|Stati Uniti d`America|America",
        /*     MEX */ "Messico",
        /*     MOW */ "Mosca",
        /*     SPE */ "San Pietroburgo",
        /*     KGD */ "Kaliningrad",
        /*   RU-IN */ "Repubblica Inguscezia",
        /*   RU-AD */ "Repubblica Adygea",
        /*   RU-SE */ "Ossezia del Nord-Alania Repubblica",
        /*   RU-KB */ "Kabardino-Balkar Republic",
        /*   RU-KC */ "Karachay-Cherkess Republic",
        /*   RU-CE */ "Repubblica cecena",
        /*   RU-CU */ "Chuvash Republic",
        /*     IVA */ "Ivanovo Oblast",
        /*     LIP */ "Lipetsk Oblast",
        /*     ORL */ "Oryol Oblast",
        /*     TUL */ "Tula",
        /*   RU-BE */ "Oblast `di Belgorod",
        /*     VLA */ "Vladimir Oblast",
        /*     KRS */ "Kursk Oblast",
        /*     KLU */ "Kaluga Oblast",
        /*   RU-TT */ "Tambov Oblast",
        /*     BRY */ "Bryansk Oblast",
        /*     YAR */ "Yaroslavl Oblast",
        /*     RYA */ "Ryazan Oblast",
        /*     AST */ "Oblast `di Astrachan",
        /*     MOS */ "Moscow Oblast",
        /*     SMO */ "Smolensk",
        /*   RU-DA */ "Repubblica del Daghestan",
        /*     VOR */ "Voronezh Oblast",
        /*     NGR */ "Novgorod Oblast",
        /*     PSK */ "Pskov",
        /*     KOS */ "Kostroma Oblast",
        /*     STA */ "Kraj di Stavropol `",
        /*     KDA */ "Krasnodar Krai",
        /*   RU-KL */ "Repubblica Kalmykia",
        /*     TVE */ "Tver Oblast",
        /*     LEN */ "Leningrad Oblast",
        /*     ROS */ "Rostov Oblast",
        /*     VGG */ "Oblast `di Volgograd",
        /*     VLG */ "Vologda Oblast",
        /*     MUR */ "Murmansk Oblast",
        /*   RU-KR */ "Repubblica Carelia",
        /*     NEN */ "Okrug autonoma Nenets",
        /*   RU-KO */ "Repubblica di Komi",
        /*     ARK */ "Arkhangelsk Oblast",
        /*   RU-MO */ "Repubblica Mordovia",
        /*     NIZ */ "Nizhny Novgorod Oblast",
        /*     PNZ */ "Penza Oblast",
        /*   RU-KI */ "Kirov Oblast",
        /*   RU-ME */ "Mari El Republic",
        /*     ORE */ "Orenburg Oblast",
        /*     ULY */ "Ulyanovsk Oblast",
        /*   RU-PM */ "Perm Krai",
        /*   RU-BA */ "Repubblica Bashkortostan",
        /*   RU-UD */ "Repubblica di Udmurtia",
        /*   RU-TA */ "Repubblica Tatarstan",
        /*     SAM */ "Samara Oblast",
        /*     SAR */ "Oblast `di Saratov",
        /*     YAN */ "Yamalo-Nenets",
        /*   RU-KM */ "Khanty-Mansi",
        /*     SVE */ "Sverdlovsk Oblast",
        /*     TYU */ "Tyumen Oblast",
        /*     KGN */ "Kurgan Oblast",
        /*   RU-CH */ "Chelyabinsk Oblast",
        /*   RU-BU */ "Repubblica Buryatia",
        /*     ZAB */ "Zabaykalsky Krai",
        /*     IRK */ "Oblast `di Irkutsk",
        /*     NVS */ "Oblast `di Novosibirsk",
        /*     TOM */ "Tomsk",
        /*     OMS */ "Oblast `di Omsk",
        /*   RU-KK */ "Repubblica Khakassia",
        /*     KEM */ "Oblast `di Kemerovo",
        /*   RU-AL */ "Repubblica dell`Altaj",
        /*     ALT */ "Altai Krai",
        /*   RU-TY */ "Repubblica Tuva",
        /*     KYA */ "Krasnoyarsk Krai",
        /*     MAG */ "Magadan Oblast",
        /*     CHU */ "Chukotka Okrug",
        /*     KAM */ "Kamchatka Krai",
        /*     SAK */ "Sakhalin Oblast",
        /*   RU-PO */ "Primorsky Krai",
        /*     YEV */ "Oblast `autonoma ebraica",
        /*     KHA */ "Khabarovsk Krai",
        /*     AMU */ "Oblast",
        /*   RU-SA */ "Repubblica di Sakha|Yakutia Repubblica",
        /*     CAN */ "Canada",
        /*     RUS */ "Russia",
        /*   CN-SH */ "Shanghai",
        /*   CN-TJ */ "Tianjin",
        /*   CN-BJ */ "Pechino",
        /*   CN-HI */ "Hainan",
        /*   CN-NX */ "Ningxia Hui",
        /*   CN-CQ */ "Chongqing",
        /*   CN-ZJ */ "Zhejiang",
        /*   CN-JS */ "Jiangsu",
        /*   CN-FJ */ "Fujian",
        /*   CN-AH */ "Anhui",
        /*   CN-LN */ "Liaoning",
        /*   CN-SD */ "Shandong",
        /*   CN-SX */ "Shanxi",
        /*   CN-JX */ "Jiangxi",
        /*   CN-HA */ "Henan",
        /*   CN-GZ */ "Guizhou",
        /*   CN-GD */ "Guangdong",
        /*   CN-HB */ "Hubei",
        /*   CN-JL */ "Jilin",
        /*   CN-HE */ "Hebei",
        /*   CN-SN */ "Shaanxi",
        /*   CN-NM */ "Nei Mongol|Mongolia Interna",
        /*   CN-HL */ "Heilongjiang",
        /*   CN-HN */ "Hunan",
        /*   CN-GX */ "Guangxi Zhuang",
        /*   CN-SC */ "Sichuan",
        /*   CN-YN */ "Yunnan",
        /*   CN-XZ */ "Xizang|Tibet",
        /*   CN-GS */ "Gansu",
        /*   CN-QH */ "Qinghai",
        /*   CN-XJ */ "Xinjiang Uyghur",
        /*     CHN */ "Cina",
        /*     UMI */ "Isole minori esterne degli Stati Uniti d`America",
        /*     CPT */ "Isola Clipperton",
        /*     ATA */ "Antartide",
        /*     AAA */ "Internazionale|Il mondo|Terra"
#else // MAPCODE_SUPPORT_LANGUAGE_IT
        NULL
#endif // MAPCODE_SUPPORT_LANGUAGE_IT
};

#ifdef __cplusplus
}
#endif

#endif // __INTERNAL_TERRITORY_NAMES_IT_H__
